### ISSUE TITLE
[Change Request]: Reuse initialization logic for Core Repository from Cosmos ecosystem

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#101]
### Summary

We implement Core initialiazation, when it is technically possible to reuse it.

### Gain

We don't need to maintain a piece of a code that is already implemented by 3rd parties. 

### Evidence

N/A

### Implementation ideas

We should wait until Core(Tendermint) or Cosmos will provide reusable functions to accomplish this. Then simply swap out custom logic with theirs. 

### Urgency

Low

**Comment by liamsi** [comment]
Can we close this? Or what is the plan with this issue?

**Comment by renaynay** [comment]
Let's close for now
