### ISSUE TITLE
admin: Define issue triaging process

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#102]
We need to define key players/stakeholders on triaging issues of different types and what is the overall process of triaging to be in async contact/update and create a transparent place for every community member

**Comment by Bidon15** [comment]
Grooming 12/07/2022:

- Moving to mainnet as we need to control(have a process)the stages of the bug dashboard 
- If Incentivize overflow us with bugs, then move this one more to it

**Comment by Bidon15** [comment]
Grooming 01/11/2022:

@MSevey Can we also discuss across teams how we tackle triaging

**Comment by MSevey** [comment]
> Grooming 01/11/2022:
> 
> @MSevey Can we also discuss across teams how we tackle triaging

yes, @YazzyYaz should be involved in this discussion as well. And moving forward what our general triage process is for inbound community issues.
