### ISSUE TITLE
deps: update go-libp2p to v0.24.0  

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1029]
There is a new release that merges go-libp2p-core into go-libp2p. We rely on go-libp2p-core in multiple places, so updating will require multiple reimports and some efforts. All the related libp2p deps should be updated as well, e.g pubsub

https://github.com/libp2p/go-libp2p/releases/tag/v0.22.0

**Comment by Wondertan** [comment]
We should wait for https://github.com/libp2p/go-libp2p-pubsub/pull/498

**Comment by Wondertan** [comment]
The above one is done, but we should also wait for https://github.com/libp2p/go-libp2p-kad-dht/pull/788 and https://github.com/ipfs/go-bitswap/pull/580

**Comment by distractedm1nd** [comment]
@Wondertan reminder that the mentioned PRs are merged

**Comment by Wondertan** [comment]
Thanks, @distractedm1nd. Not big a prio, for now, to jump on this.

Also, we know from #1035 that the newest version of bitswap will cause us flakiness, and updating would require fixing those and CI as an additional burden
