### ISSUE TITLE
deps: revert recent bitswap update

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1035]
The #1010 started to cause us [flakiness](https://github.com/celestiaorg/celestia-node/issues/1032), and we are not confident that it will work in production for the soon release in practice for us, so its better to revert it

**Comment by vgonkivs** [comment]
should fix https://github.com/celestiaorg/celestia-node/issues/1034 and https://github.com/celestiaorg/celestia-node/issues/1032
