### ISSUE TITLE
Remove go-watchdog once we migrate to 1.19

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1039]
Watchdog 'solves' the OOM problem when Go aggressively allocates memory on low RAM systems. The quotes are to emphasize that it does not solve the problem completely and is more like a hack when the real problem is in GO's GC. Fortunately, GO 1.19 [solves](https://tip.golang.org/doc/go1.19#runtime) the problem fundamentally by introducing the soft memory limit

**Comment by Wondertan** [comment]
As https://github.com/celestiaorg/celestia-node/pull/1067 landed, we can now remove it

**Comment by HoytRen** [comment]
I'm trying this. It seems easy but I need some time to test it.
