### ISSUE TITLE
[Feature Request]: metrics for PayForData and last sample requested

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#1040]
| Metric Name                              | Light node | Full Node | Bridge node |
| ---------------------------------------- | ---------- | ----------------- | ----------- |
| Total PayForData messages sent (count)   | x          | x                 | x           |
| Last PayForData message sent (timestamp) | x          | x                 | x           |
| Last sample requested (timestamp)        | x          | x                 |             |
| Last block served (timestamp)            |            |                   | x           |
| Last full sampling request (timestamp)   |            | x                 |             |

Feature request to emit the above metrics with a label that uniquely identifies a node (i.e. peer id). Note that a peer id is bounded on incentivized testnet but unbounded on mainnet so we likely want to remove the label prior to mainnet to avoid issues with high cardinality (see [Prometheus docs](https://prometheus.io/docs/practices/naming/#labels)).

**Comment by rootulp** [comment]
@YazzyYaz and @Wondertan brainstormed additional metrics that may be necessary so I updated the table above

**Comment by distractedm1nd** [comment]
What is meant by "Last full sampling request"? Since bridge nodes don't sample

I'm assuming on every reconstruction or something? Since bridge+full both have a `FullAvailability`

**Comment by rootulp** [comment]
> What is meant by "Last full sampling request"? Since bridge nodes don't sample

Good question! Maybe it pertains to which data root was last requested / retrieved?https://github.com/celestiaorg/celestia-node/blob/9e45ada26417fc4895e33326584b896754cff1c6/service/share/full_availability.go#L58

If so, we can likely update the name to not include `sample` because that seems confusing. @Wondertan likely has input here

**Comment by distractedm1nd** [comment]
Yes that seems the most likely as well, will add there

**Comment by Wondertan** [comment]
I'm not sure we need to track the last requested(sampled) block by Bridge, and I don't remember discussing this, to be honest.

We also need to track the last ___served___ Block from Full nodes besides only Bridges(currently the table sell for Fulls is empty). But we cannot do this right now, as there is no way to differentiate between whole block requests and sampling requests. We can do, though, wrap IPFS blockstore with some metering that sends metrics on each sample/share read, but that's way too granular and actually hits high cardinality issue. Still, this approach does not answer whether this is a block request or a sampling. cc @distractedm1nd 

Another point is metering block serving/requesting right now can be too early considering the new blocksync work. Doing it now will be required redoing it later.

**Comment by distractedm1nd** [comment]
Ok, I implemented it as the last block header broadcasted (served) - since I was thinking "what do only bridge nodes serve"? I'm not really sure what is meant by served then, but i'm sure i'm just thinking about it too complex - can you clarify quickly?

**Comment by Wondertan** [comment]
> last block header broadcasted (served) -

The issue is about the last block served, not the header. But the header would be helpful independently, so let's keep this.

**Comment by musalbas** [comment]
Instead of using PayForData message to infer node uptime in testnets, can't we use the telemetry data directly to infer this? e.g. by adding a metric for uptime / number of sample requests made / blocks downloaded / etc.

cc @YazzyYaz @mojtaba-esk

**Comment by Wondertan** [comment]
@musalbas, yes, we can. The metrics above are not specifically about uptime; for it, we can make a specific metric, just a seconds uptime counter that gets updated every 10 seconds.
