### ISSUE TITLE
config: make node a bootstrapper with a flag option

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#1057]
Right now, we need to create a bootstrapper through editing config.toml
The flag like `--bootstrapper` will ease the creation much more comparing to the current approach.

**Comment by Bidon15** [comment]
cc: @sysrex

**Comment by Wondertan** [comment]
Linking existing discussion for the problem: https://github.com/celestiaorg/celestia-node/issues/63

The original solution is still preferred. The bootstrapper mode is a very special case for our infrastructure. Regular users should not be running nodes in this mode; hence, this build and/or CLI flag should be hidden away from them. If we go with the build flag approach, then it the `celestia version` cmd should show that this is a bootstrapper build binary.

**Comment by renaynay** [comment]
While we did not add a flag, we added env var instead.
