### ISSUE TITLE
shares: implement/import DASing

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#106]
## Context
Celestia light clients heavily rely on DASing and we need to implement it in the Node.

## Implementation 
Luckily, most of it has already been implemented in core. The first step would be copying the code from the Core in the [specific branch](https://github.com/celestiaorg/celestia-core/blob/hlib/block-propagation-2/p2p/ipld/validate.go#L25). It may be needed to copy more code than just the ValidateAvailability function. Then, we should aim to extract all the DASing(share) related code into a separate repository(https://github.com/celestiaorg/celestia-node/issues/21).

**Comment by liamsi** [comment]
My understanding is that this is done now?

**Comment by Wondertan** [comment]
Yes, thank you!
Closed by #177
