### ISSUE TITLE
fix(cmd/cel-key): Add error when no node type is provided to cel-key

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1074]
In our cel-key utility, we should error out with "no node type provided" during the following:

https://github.com/celestiaorg/celestia-node/blob/8657edc37d3911d42de447d9d0c93c4676a148c9/cmd/cel-key/node_types.go#L29-L32

**Comment by nitinmewar** [comment]
can I work on it?

**Comment by distractedm1nd** [comment]
@nitinmewar Yes! Feel free

**Comment by 0xJepsen** [comment]
> can I work on it?

Are you still working on this?
