### ISSUE TITLE
cmd/celestia: Add command to delete celestia repository (datastore)

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#109]
We need something like `unsafe-reset-all` as a subcommand of all node types. The reason for `unsafe-reset-all` being a subcommand of a node type is because when you init a `full` node (for example), it creates a repository called `celestia-full` which corresponds to the full nodes configuration / data. The same is true for other node types.

**Comment by Wondertan** [comment]
Should we remove private keys as well?
