### ISSUE TITLE
Fork DAGStore and extended `ShardAccessor` to return an `io.Reader`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1101]
According to #1099, the [`DAGStore.ShardAccessor`](https://github.com/filecoin-project/dagstore/blob/master/accessor.go#L33) has to return an `io.Reader`. Unfortunately, it does not do so, and we should fork the DAGStore repo and provide such functionality there.

Additionally, we should make issues in the upstream repo to discuss it with the original implementors and potentially submit a fix there to avoid maintenance of the fork.

**Comment by distractedm1nd** [comment]
I didn't see you were assigned when I did this, sorry, just changed assignee to me if thats fine

**Comment by Wondertan** [comment]
Totally fine

**Comment by distractedm1nd** [comment]
@Wondertan Closing because celestiaorg/dagstore#1 is merged
