### ISSUE TITLE
share: `EDSStore.GetCAR`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1109]
## Context

To read an EDS as a byte stream `GetCAR` method is introduced.

## Implementation Details 

 Internally it:
- Converts `DataRoot`'s hash into the [`shard.Key`](https://github.com/filecoin-project/dagstore/blob/master/shard/key.go#L12)
- Acquires `ShardAccessor` and returns `io.ReadCloser` from it

___NOTES:___

- _`DAGStores`'s `ShardAccessor` has to be extended to return an `io.ReadCloser`. Currently, it only returns
  a `Blockstore` of the CAR_
- _The returned `io.Reader` represents actual EDS exchanged over the wire, which should be limited to return the first quadrant_

```go
// GetCAR takes a DataRoot and returns a buffered reader to the respective EDS serialized as a CARv1 file.
// 
// The Reader strictly reads the first quadrant(1/4) of EDS, omitting all the NMT Merkle proofs.
// Integrity of the store data is not verified. 
// 
// Caller must Close returned reader after reading.
func (s *EDSStore) GetCAR(context.Context, DataRoot) (io.ReadCloser, error)
```

## Refs

Depends on #1101 
Depends on https://github.com/celestiaorg/celestia-node/issues/1104
Depends on #1107

**Comment by distractedm1nd** [comment]
We will need to update the comment when we update the ADR after #1377
