### ISSUE TITLE
ipld: change docs to remove mention of IPFS

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#112]

**Comment by liamsi** [comment]
Is it these two mentions that are confusing?
https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/ipld/read.go#L20-L21

https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/ipld/write.go#L16

I kinda agree as this sounds like we are using the public IPFS network. Should be a simple fix to mention that this is done via bitswap now. Or simply say that this is done on the p2p layer without even stating how.

**Comment by Wondertan** [comment]
These mentions were removed so closing
