### ISSUE TITLE
ci:lint: update golangci-lint to 1.49

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#1124]
We should update our ci:lint version to 1.49 and fix all new warnings.

<img width="1760" alt="Снимок экрана 2022-09-19 в 14 11 16" src="https://user-images.githubusercontent.com/40579846/191005192-f83cade8-d1a1-46a9-8c6f-b8642c59329b.png">

**Comment by distractedm1nd** [comment]
Done in #1067

**Comment by vgonkivs** [comment]
ooops. Did not see that PR 😅
