### ISSUE TITLE
[Feature Request]: migrate badger logs to TRACE level

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#1154]
### Implementation ideas

Currently, our badger logs are overwhelming other types of logs in `DEBUG` level. 
In addition, the CPU and RAM consumption are sky-rocketing.

Hence, it will be beneficial to migrate the badger logs to `TRACE` level

**Comment by HoytRen** [comment]
I want to try this because it really bothers me.

**Comment by Wondertan** [comment]
This can be solved under log pkg. When we set Debug we should exclude it for the noisy modules

**Comment by HoytRen** [comment]
Thanks Wondertan for your suggestion.

I found in

https://github.com/celestiaorg/celestia-node/blob/cec6a2d6535870910478cac27f44c19dcd6316af/nodebuilder/store.go
Line: 129

We can remap the log level, but it is usually not a good idea.

Then, let me try your way.
