### ISSUE TITLE
all: don't populate protocol ids with chain_id in global space

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1189]
Instead, each protocol like HeaderEx should have an option or config to receive and prepend a chain ID in the constructor and not during global initialization.

**Comment by Wondertan** [comment]
- [  ] HeaderEx: [`header/p2p/service.go`](https://github.com/celestiaorg/celestia-node/blob/main/header/p2p/exchange.go#L29)
- [  ] FraudSync: [`fraud/sync`](https://github.com/celestiaorg/celestia-node/blob/main/fraud/service.go#L23)

**Comment by distractedm1nd** [comment]
Oh, this is solved by #1168
