### ISSUE TITLE
Panic during syncing from genesis for a full/light node types

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#1243]
### Celestia Node version

6340d4566bf48b5b2d3bbfcab22ecd86b677a82e

### OS

macOS 12.0.1

### Install tools

make go-install

### Steps to reproduce it

1. Initialise a full or a light node
2. Start sync

### Expected result

Syncing happens with no panicking 

### Actual result

After reaching close to the tip of the chain - we see panic errors popping up forcing node to shut down

### Relevant log output

```Shell
panic: runtime error: slice bounds out of range [:8] with capacity 0

goroutine 1330 [running]:
github.com/celestiaorg/nmt.(*Hasher).HashLeaf(0xc00a0eec30, {0x0, 0x0, 0x0})
	/Users/bidon4/go/pkg/mod/github.com/celestiaorg/nmt@v0.10.0/hasher.go:101 +0x295
github.com/celestiaorg/celestia-node/share/ipld.(*namespaceHasher).Sum(0xc00a0c7f00?, {0xc0018bc000?, 0xc009ba3db0?, 0xc00a59fb68?})
	/Users/bidon4/go/src/github.com/celestiaorg/celestia-node/share/ipld/namespace_hasher.go:64 +0xb0
github.com/multiformats/go-multihash.encodeHash({0x6a6e3a0, 0xc00a0eec60}, 0x7701, 0x30)
	/Users/bidon4/go/pkg/mod/github.com/multiformats/go-multihash@v0.2.0/sum.go:54 +0x42
github.com/multiformats/go-multihash.Sum({0xc009bed5e0, 0x61, 0x70}, 0x1?, 0x7701?)
	/Users/bidon4/go/pkg/mod/github.com/multiformats/go-multihash@v0.2.0/sum.go:30 +0x90
github.com/ipfs/go-cid.Prefix.Sum({0xc00a0a52b0?, 0x8?, 0x8?, 0xc00a0eeb10?}, {0xc009bed5e0?, 0xc00a59fd08?, 0x4c60438?})
	/Users/bidon4/go/pkg/mod/github.com/ipfs/go-cid@v0.3.2/cid.go:548 +0xa5
github.com/ipfs/go-bitswap/message.newMessageFromProto({{{0x0, 0x0, 0x0}, 0x0}, {0x0, 0x0, 0x0}, {0xc00a0eeb10, 0x1, 0x1}, ...})
	/Users/bidon4/go/pkg/mod/github.com/ipfs/go-bitswap@v0.8.0/message/message.go:222 +0x1bb
github.com/ipfs/go-bitswap/message.FromMsgReader({0xe6277d8, 0xc00a0d3740})
	/Users/bidon4/go/pkg/mod/github.com/ipfs/go-bitswap@v0.8.0/message/message.go:416 +0x118
github.com/ipfs/go-bitswap/network.(*impl).handleNewStream(0xc00038b680, {0x6a819f0?, 0xc00a0cf380})
	/Users/bidon4/go/pkg/mod/github.com/ipfs/go-bitswap@v0.8.0/network/ipfs_impl.go:413 +0x39c
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc00a0dadb0, 0x24}, {0xef593a8?, 0xc00a0cf380})
	/Users/bidon4/go/pkg/mod/github.com/libp2p/go-libp2p@v0.21.0/p2p/host/basic/basic_host.go:568 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/Users/bidon4/go/pkg/mod/github.com/libp2p/go-libp2p@v0.21.0/p2p/host/basic/basic_host.go:411 +0x715
```

### Notes

Logs for Light Node: https://gist.github.com/Bidon15/0475816f1364883e4e2f2f92057b312a

Logs for Full Node: https://gist.github.com/Bidon15/4d2a8a07a217289df9807cc85eeb627f

**Comment by Bidon15** [comment]
Another Note: This is not reproducible once you restart a crashed instance of either Full or Light Nodes

However, if we initialise from scratch, this bug reproduces stably 😓 

Another log from a 2nd light node created from scratch: https://gist.github.com/Bidon15/949d7b188459a1cf35ed64c1ab4cb2d9

**Comment by distractedm1nd** [comment]
Am getting a different panic from a light node:

https://gist.github.com/distractedm1nd/728b45bf5ac5bfafc5f301fefdf8d4ba

We get 97 when we expect 96 bytes

**Comment by Wondertan** [comment]
64+8+1

**Comment by Bidon15** [comment]
cc: @YazzyYaz and @MSevey 

This is affecting current Arabica upgrade

**Comment by Wondertan** [comment]
Weird though why the type byte is added there in the first place

**Comment by MSevey** [comment]
Does node have simple integration tests that mock syncing a node? 

If not, seems like this is the time to prioritizing doing that.

**Comment by renaynay** [comment]
Yes we have a lot of integration tests that would catch something specifically like this @MSevey 

Our only explanation at the moment is that there's an old node serving old data on arabica on the bitswap level.

**Comment by MSevey** [comment]
> Yes we have a lot of integration tests that would catch something specifically like this @MSevey 
> 
> 
> 
> Our only explanation at the moment is that there's an old node serving old data on arabica on the bitswap level.

Ah, interesting, so a compatibility issue then. 

Which then begs the question, do we need to bother fixing it? Since we are still on testnet, we don't have a compatibility promise right? There's definitely value in understanding the root cause, but we knew we were breaking compatibility with this release. So nodes just need to upgrade.
