### ISSUE TITLE
Improvement: propose optimal real world daser configuration values for each node type

### ISSUE THREAD

**Issue by derrandz** [celestiaorg/celestia-node#1261]
# Description

In the `nodebuilder/das/config.go` file, we propose default configuration values for the daser that are not based on any real world experimentation, thus we cannot be sure about their optimal-ness.
Also, in the future, we will be proposing different configurations depending on the node type.

Thus we need to experiment with multiple configuration values for each node types and propose the most optimal configurations as defaults

# Origin

> note: @derrandz, this is where `node.Type` will be passed eventually to have different Configs for each type

_Originally posted by @Wondertan in https://github.com/celestiaorg/celestia-node/pull/1225#discussion_r1001843996_

# Pre-requisites

1. Access to DASing benchmark tests
2. Access to a theoretical calculator for the DASing process
3. Access to the concurrency calculator (_concurrency based on the hardware setup_)

# Owners
@derrandz

**Comment by renaynay** [comment]
We already have different values (6 routines for `full` and 16 for `light`). Closing as non-relevant at the moment.
