### ISSUE TITLE
fix(nodebuilder): clean up `Config` usage pattern

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1287]
We need to clean up Config usage pattern in our module configs. Somewhere we use ptr, and somewhere a value. Let's use ptr everywhere.

_Originally posted by @Wondertan in https://github.com/celestiaorg/celestia-node/pull/1199#discussion_r1006537136_

**Comment by renaynay** [comment]
Issue is resolved, we use ptr everywhere in config / cfg.Validate pattern throughout nodebuilder subpkgs.
