### ISSUE TITLE
cmd: Add better/more thorough descriptions to CLI commands/flags

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#129]
We need to revisit our current descriptions for commands/flags available on the celestia binary and double check to ensure they are thorough enough.

**Comment by renaynay** [comment]
Currently: 
```
  init        Initialization for Celestia Node. Passed flags have persisted effect.
  keys        Manage your bridge node account keys
  start       Starts Node daemon. First stopping signal gracefully stops the Node and second terminates it.
```

**Comment by YazzyYaz** [comment]
Hi @renaynay can I get more clarity on how do you want to ensure they're thorough? Happy to submit a PR, I'm just lacking some context on the desired outcome here.

**Comment by renaynay** [comment]
Hey @YazzyYaz , sorry for not giving you more context, i realise i just tagged you without much explanation. I think it would be nice if you could review our command line flags as they are and see if there are descriptions that aren't explanatory enough, or if we have confusing naming, etc. Is that okay?

**Comment by Bidon15** [comment]
Grooming 01/11/2022:

Plan to finish before ITN

**Comment by ramin** [comment]
a little out of date and we've done lots of work on flags, --help etc, so closing and we can re-open for specific commands that maybe cause confusion as they arrive
