### ISSUE TITLE
Further clarify relation of abci-app in the embedded case

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#130]
### Summary

ADR-001 described the relation between node and core+abci-app. Since then, there was a slight pivot to embed the tendermint process in node directly (ADR-002). ADR 002 does not yet clearly describe how the abci-app fits into the equation.

### Gain

No doubt on the relationship between node and abci-app and which components "drives" which. Also, the implications for the user interface (on the command-line) if any should be clarified. 

### Evidence

https://github.com/celestiaorg/celestia-node/pull/97#discussion_r726020336

### Implementation ideas

Previously the idea was that the app binary would be used to init core and the app. Now that node embeds the core node, it seems to be necessary that the node exposes the same cli as the app. This needs to be done in a way that does not require writing a lot of code (ideally, the corresponding commands are just "passed through" to the cli of node, similar to how the app, exposes the [tendermint node's cli](https://github.com/cosmos/cosmos-sdk/blob/7e6151e93c4d48da813aba37d475df2393ca087b/server/tm_cmds.go#L9) already).

### Urgency

High

**Comment by liamsi** [comment]
Didn't we remove the embedded case for now? can we close this then?

**Comment by renaynay** [comment]
Yes @liamsi

**Comment by renaynay** [comment]
However, we will be revisiting the concept of embedding celestia-app once we think about how full nodes can serve state.
