### ISSUE TITLE
Error 1 on installing celestia

### ISSUE THREAD

**Issue by ZenTHOR23** [celestiaorg/celestia-node#1312]
ubuntu@ip-_________:~/celestia-node$ make install
--> Building Celestia
--> Installing Celestia
'./build/celestia' -> '/usr/local/bin/celestia'
install: cannot create regular file '/usr/local/bin/celestia': Permission denied
make: *** [Makefile:47: install] Error 1

**Comment by Wondertan** [comment]
`make install` requires `sudo` privileges or try `make go-install`
