### ISSUE TITLE
cmd/celestia: Extract common parsing logic into single function

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1331]
DRY the parsing logic inside the `PersistentPreRunE` fields for each node type (`bridge`, `light`, `full`).

**Comment by HoytRen** [comment]
I finished the modification, but the ignore file of git cause a problem that I can't add new files in '/cmd/celestia/'.

@Wondertan I see that you are the latest modifier of relative content [#889f2a20](https://github.com/celestiaorg/celestia-node/commit/889f2a2015b9a3a48153133c5005718b7af5d0e2), and here isn't file or folder named 'celestia' in root currently, then I need your conformation of change 'celestia -> /celestia/' at line 18 of .gitignore.

Or should I ignore this problem, leave the ignore file unchanged and take 'git add -f' ?
