### ISSUE TITLE
BEFP verification mechanism creates incorrect erasure encoded data

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-node#1355]
When creating a bad encoding fraud proof, we are currently adding the namespace to the data, this will result in always creating a BEFP that is verified as a valid fraud proof despite it being generated from perfectly good data.

We need to stop adding the namespace data to the shares that get encoded, so that they match the share data that gets erasure encoded. see #1354 and discussion in [here](https://github.com/celestiaorg/celestia-node/pull/1338#discussion_r1020161713)

**Comment by Wondertan** [comment]
@renaynay, it is not a fraud area anymore as it moved now to the BEFP is now part of the share pkg
