### ISSUE TITLE
error checking balances & submitting PFD, v0.5.0-rc5

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#1381]
### Celestia Node version

v0.5.0-rc5, golang 1.19.1

### OS

Ubuntu 21.04

### Install tools

```
ver="1.19.1"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
```

then

```
cd $HOME
rm -rf celestia-node
git clone https://github.com/celestiaorg/celestia-node.git
cd celestia-node/
git checkout tags/v0.5.0-rc5
make install
make cel-key
```

And finally, import wallet with Arabica token, start node.

### Steps to reproduce it

Run light node: `celestia light start --core.ip https://limani.celestia-devops.dev/ --core.grpc.port 9090 --gateway.addr localhost --gateway.port 26659 --keyring.accname keplr`

When running the light node, with an account funded with Arabica tokens (celestia1c425ckmve2489atttx022qpc02gxspa29wmh0d), I am experiencing the following behavior:

**Checking balance - Port 26659**
Request: `curl -X GET http://localhost:26659/balance`
Response: `curl: (7) Failed to connect to localhost port 26659 after 6 ms: Connection refused`

**Checking balance - Port 26658**
Request: `curl -X GET http://localhost:26658/balance`
Response: none, and below:
```sh
2022-11-17T17:51:47.871-0500	ERROR	rpc	go-jsonrpc@v0.1.8/server.go:97	RPC Error: unmarshaling request: EOF
2022-11-17T17:51:47.871-0500	WARN	rpc	go-jsonrpc@v0.1.8/server.go:103	rpc error: unmarshaling request: EOF
```

I have also queried other addresses using `curl -X GET http://localhost:26659/balance/celestia1c425ckmve2489atttx022qpc02gxspa29wmh0d` with the same results.

---

**PFD**
Request:
```sh
curl -X POST -d '{"namespace_id": "0c204d39600fddd3",
  "data": "f1f20ca8007e910a3bf8b2e61da0f26bca07ef78717a6ea54165f5",
  "gas_limit": 70000}' http://localhost:26659/submit_pfd
```
Response: `curl: (7) Failed to connect to localhost port 26659 after 0 ms: Connection refused`

---

**Rollmint with Cosmwasm**
Response: 
```sh
11:26PM INF submitting block to DA layer height=1 module=BlockManager
11:26PM ERR DA layer submission failed error="Post \"http://localhost:26659/submit_pfd\": dial tcp [::1]:26659: connect: connection refused" attempt=1 module=BlockManager
11:26PM ERR DA layer submission failed error="Post \"http://localhost:26659/submit_pfd\": dial tcp [::1]:26659: connect: connection refused" attempt=2 module=BlockManager
```

### Expected result

The balance of the account running the node or account specified after `/balance/`

### Actual result

above in steps to reproduce

### Relevant log output

For Rollmint:
```sh
p://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused; failed to retrieve block: Get \"http://localhost:26659/namespaced_data/000000000000ffff/height/7000\": dial tcp [::1]:26659: connect: connection refused" module=BlockManager
11:33PM ERR DA layer submission failed error="Post \"http://localhost:26659/submit_pfd\": dial tcp [::1]:26659: connect: connection refused" attempt=13 module=BlockManager
```

**Comment by renaynay** [comment]
@jcstein It is because you do not enable gateway -- unfortunately you have to pass `--gateway` flag to enable the REST gateway. We have to open an issue to add it to the docs.

**Comment by Bidon15** [comment]
this issue should also be resolved by this PR 
https://github.com/celestiaorg/celestia-node/pull/1378

**Comment by renaynay** [comment]
Actually @distractedm1nd we should short circuit when a user provides `--gateway.addr` or `--gateway.port` without specifying `--gateway`? 

We do this elsewhere I believe.

**Comment by Wondertan** [comment]
`--gateway 127.0.0.1:55555` 🙂

**Comment by jcstein** [comment]
okay thank you all. so the `--gateway` flag is passed with no args?

**Comment by jcstein** [comment]
hoping to update docs in 1 go

**Comment by jcstein** [comment]
seeing an error when i pass the gateway flag before other gateway flags

Start node: `root@stein-debug:~# celestia light start --core.ip https://limani.celestia-devops.dev/ --core.grpc.port 9090 --gateway --gateway.addr localhost --gateway.port 26659 --keyring.accname keplr`

Error: `Error: gateway: invalid listen address format: localhost`

**Comment by Wondertan** [comment]
@jcstein, i didn't suggested a working solution 😅, but hinted the way we can simplify flags into one, instead of 3. The tradeoffs between both ways are yet be analyzed.

**Comment by jcstein** [comment]
last one worked fwiw :)

**Comment by jcstein** [comment]
this issue should be resolved with this PR https://github.com/celestiaorg/docs/pull/322 😅 

I am still curious how it is possible to pass in localhost? or if it is not?

**Comment by renaynay** [comment]
localhost is default @jcstein, closing as seems to have been resolved
