### ISSUE TITLE
[BUG] header/sync: Repeat sync on same header, running light node on Arabica.

### ISSUE THREAD

**Issue by zklim** [celestiaorg/celestia-node#1399]
### Celestia Node version

Semantic version: v0.5.0-rc5 Commit: 039facd94104c741f8fa995e80f1321776ae4ad3 Build Date: Sat Nov 26 11:37:54 +08 2022 System version: amd64/linux Golang version: go1.19.1

### OS

Windows Subsystem for Linux Distributions: Ubuntu-22.04

### Install tools

Installation follow official docs https://docs.celestia.org/nodes/light-node/

### Steps to reproduce it

Just start running light node and the warning pops up sometime.

### Expected result

No warning

### Actual result

Warning of sync attempt to an already synced header.
![Capture](https://user-images.githubusercontent.com/53001910/204080730-2f6ba11d-93f6-4c05-9d47-942979c4cdc1.PNG)

### Relevant log output

```Shell
2022-11-26T14:16:22.032+0800    WARN    header/sync     sync/sync.go:173        sync attempt to an already synced header        {"synced_height": 36471, "attempted_height": 36471}
2022-11-26T14:16:22.032+0800    WARN    header/sync     sync/sync.go:177        PLEASE REPORT THIS AS A BUG
```

**Comment by renaynay** [comment]
Thank you for reporting @zklim

**Comment by zklim** [comment]
Recently did not see warning of repeat sync but getting new warning now.

![Capture](https://user-images.githubusercontent.com/53001910/204508574-87460a91-bd27-4e81-94e1-02fe397589c0.PNG)

**Comment by renaynay** [comment]
Likely to have been resolved with `syncedHead` implementation -- will reopen if we see it again.
