### ISSUE TITLE
cmd/celestia: Create `config` command with subcommands to manage config

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1414]
`celestia bridge config remove` --> deletes config
`celestia bridge config init` --> initialises with the passed in config or default conf if nothing passed
`celestia bridge config reinit` --> takes config if it exists, applies the diff (to add new sections)

these commands would also have to take a `p2p.network` flag to know which repository to target or a `--node.store` flag if custom.

**Comment by Wondertan** [comment]
I would also suggest something like `print` subcmd going further

**Comment by superfiredoge** [comment]
Hey👋, I would love to work on this issue!

**Comment by dixitaniket** [comment]
I would like to work on this!

**Comment by dixitaniket** [comment]
Hey, I need a bit more clarification on reinit. Does it just essentially replace the config.yml file, and in case it does not exist, it would init the config with the custom config file? or is it something else?

**Comment by Wondertan** [comment]
@dixitaniket
>  takes config if it exists, applies the diff (to add new sections)

So it does not remove/replaces, but applies a diff, which is a bit trickier 🙂
