### ISSUE TITLE
Add flag to pass address of remote Core node

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#142]
This flag should tell Node to use a remote Core node instead of starting an embedded Core node process.

**Comment by vgonkivs** [comment]
Hello @renaynay . May I take this one?

**Comment by renaynay** [comment]
Yes that would be awesome @vgonkivs !

**Comment by vgonkivs** [comment]
Thank you. I have a small question. Do I need to pass a protocol with the remote address, since `NewRemote(protocol, remoteAddr string)` requires also a core protocol or should I use the default one?

**Comment by Wondertan** [comment]
@vgonkivs, thank you for taking over this.IIRC, there is no default protocol, so we should pass one. 

Ideally, we would have one flag for a remote node that contains both protocol and address, so the string from the flag would be split into two strings: protocol, addr. Also, If the flag is passed, then core.Config.Remote should be true.

Unfortunately, we don't have a framework for parsing flags and passing them into Node/Config yet and this might be tricky to implement at first. My suggestion is to use a [functional pattern](https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md) for build-time options/configuration over `NewNode`. So there would be a `Remote` option which receive a single string fro the flag, configuring the Node to run over the remote Core.

**Comment by vgonkivs** [comment]
Thanks for the hint @Wondertan , I will check the link. Actually I would like to suggest passing protocol + address by merging it via `@`. So we could easily split it into two parts. What do you think?

**Comment by Wondertan** [comment]
Let's follow usual format like: `tcp://127.0.0.1:26657`
