### ISSUE TITLE
node: migrate `Blockstore` over `eds.Store.Blockstore` for FN/BNs

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1422]
## Context

Right now, we have a global `Blockstore` over `Datastore`. As per #1099, we need to migrate to another global `Blockstore` provided by `eds.Store`, which is compatible with the new block storage.

Mainly, we should stop providing the existing `Blockstore` and a new one instead. We should also double-check that we aren't writing anywhere in the new `Blockstore` and that it is provided to `Bitswap`

**Comment by distractedm1nd** [comment]
Closed by #1719
