### ISSUE TITLE
header/core: Put Blocks into the `eds.Store` in `Listener`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1423]
## Context

Right now, the `Listener` stores the block data into `ipfs.Blockservice` during `ExtendedHeader` and EDS construction. As per #1099, we are now migrating to new storage for blocks - `eds.Store` and `Listener` should store the EDS/Block there.

This will likely require changes to the `header.MakeExtendedHeader` and likely simplify it by removing dependency on `ipfs.Blockservice`

**Comment by renaynay** [comment]
Completed as part of ShrEx implementation
