### ISSUE TITLE
eds: `Store.CARBlockstore`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1427]
`CARBlockstore` method returns a [`Blockstore`][blockstore] interface implementation instance, providing random access
over share and NMT Merkle proof in a specific EDS identified by DataHash. It is required for FNs/BNs to enable [reading
data by namespace](#reading-data-by-namespace).

___NOTES:___

- _The Blockstore does not store whole Celestia Blocks, but IPFS blocks. We represent Merkle proofs and shares in IPFS
  blocks._

```go
// CARBlockstore returns an IPFS Blockstore providing access to individual shares/nodes of a specific EDS identified by 
// DataHash and registered on the Store. NOTE: The Blockstore does not store whole Celestia Blocks but IPFS blocks. 
// We represent `shares` and NMT Merkle proofs as IPFS blocks and IPLD nodes so Bitswap can access those.
func (s *Store) CARBlockstore(DataHash) (blockstore.Blockstore, error)
```

**Comment by distractedm1nd** [comment]
Closed with #1395 , must have not linked correctly.
