### ISSUE TITLE
fix(share): removing eds.Store reliance on `FS`

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1438]
We should use[FS](https://pkg.go.dev/io/fs#FS) and pass it to the EDS store instead of relying directly on the `os.Open`. This way, we can easily pass testing FS impl and enable EDSStore to be tested in memory.

**Comment by ef3n9r98** [comment]
Hi @distractedm1nd, it's great to see you have active repos with many good first issues! I know some devs who'd be interested in working on this. Is there a budget for fixing any of your issues, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by Jpserrat** [comment]
Hey guys, can I work on this?

**Comment by distractedm1nd** [comment]
@Jpserrat Yes! Feel free to reach out to me for guidance/any questions

**Comment by Jpserrat** [comment]
@distractedm1nd Thanks for your quick response on this and sorry for the delay on my side. I already did the PR but I have some questions. 
Running make test I got some failing tests with error message:  NotFound desc = account cosmos1hh846ae9gqs9p00hdkpp4gv37ma9y7q7ysuljt not found (Not related to this issue)

Do you know what I can do?

**Comment by Jpserrat** [comment]
@distractedm1nd I noticed that I got it all wrong, I now understand that it is only the FS interface, but I'm not sure where exactly in the eds store it's supposed to be replaced

**Comment by distractedm1nd** [comment]
@Jpserrat Hey thanks for working on this! Basically we don't want to pass a path, but an FS interface to the EDS Store constructor - I took a look at what you did and its very close to what it should be I think, just without the dependency and using the FS interface instead. I think this should be possible but tell me if you run into any blockers

**Comment by Jpserrat** [comment]
@distractedm1nd Did the changes, thanks a lot for your patience and help

**Comment by distractedm1nd** [comment]
@Wondertan What is the in-memory `fs.FS` implementation you had in mind to use in testing?

**Comment by distractedm1nd** [comment]
I see no reason to need to test the eds Store in memory. We have a good test suite and it works perfectly fine with tempdir in the filesystem, which we need anyways in swamp etc. Abstracting this makes it more complicated for no reason, so closing.
