### ISSUE TITLE
Rename `PFD` => `PFB`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#1447]
## Context

1. https://github.com/celestiaorg/celestia-app/issues/962

## Problem

This repo still uses the previous name `PFD`:

1. https://github.com/celestiaorg/celestia-node/blob/b7e4b3d1db7cb6a809a40ff0afb2ec556ed98cc9/state/metrics.go#L14
1. https://github.com/celestiaorg/celestia-node/blob/cb920512f3cf9a155385fbff6f9a5cc7780f986b/api/gateway/state.go#L18

## Proposal

Rename `PFD` => `PFB`. Note this may be considered a breaking change because it implies changing an endpoint path

**Comment by distractedm1nd** [comment]
Places to rename:
[ ] Gateway
[ ] RPC
[ ] API ADR

**Comment by renaynay** [comment]
@distractedm1nd we need to rename endpoints inside of state/core_accessor as well @distractedm1nd
