### ISSUE TITLE
node|cmd: Rework the Node's Dev type. 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#145]
I like the idea of Dev mode and it makes total sense. Regarding the implementation design though, I have some objections to raise.

First, `Dev` shouldn't be a Node Type/Mode and instead every Type/Mode should have a Dev sub-mode. The further we go, the more functionality of full-node and light-node will diverge and we simply won't be able to have one `Dev` Mode/Type to cover both Full and Light dev/test needs.

Then, the first point also affects CLI UX, so instead of having another root `dev` command, we should add a generic `--dev` flag to `cmd.Start` which forces the Node of any type to be run in a Dev mode. We may also hide the `--dev` flag from help, so regular users won't see it, as they don't need to.

Lastly, we should make `--dev` functionality being part of `node` package API, like it is right now, but with different API. I propose `node.New` to have funtional options, like `.., ...Option)` with the first one as `node.Dev`, which just says to build a node for development/testing purposes as in this PR(Later on, lots of other functional options will be added). Those who will embed our Node will also be able to run it in the Dev mode with the option.

Also, it might make sense to run a Dev Node on the extising/custom Config and not only on default as it is done in the PR.

_Originally posted by @Wondertan in https://github.com/celestiaorg/celestia-node/issues/131#issuecomment-945750707_

**Comment by renaynay** [comment]
we will no longer need a `dev` mode for the foreseeable future
