### ISSUE TITLE
Invalid `NoAnnounceAddress` 

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/celestia-node#1457]
One of no-announce addresses use `tcp` instead of `udp` - node is not listening on this address.

https://github.com/celestiaorg/celestia-node/blob/b220fa3504a7fc2b82f32eba9378b2446dd6a60d/nodebuilder/p2p/config.go#L51

This should be: `"/ip4/127.0.0.1/udp/2121/quic"`.

**Comment by Wondertan** [comment]
Oh, good catch, @tzdybal  mind making a quick PR?
