### ISSUE TITLE
availability/full: Implement happy path EDS retrieval via `ShrEx/EDS`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1464]
## Context

The `FullAvailability` implementation is responsible for checking the availability of the whole EDS by retrieving and reconstructing it. As we are improving our EDS retrieval logic, the new ___happy path___  over `eds.Client` integrates into the  ___fallback path___ with the following flow.

## New Flow
* Check if `eds.Store` contains the data already. If not, we fetch it with one of the ___paths___. 
* ___happy path___ EDS
  * Take peers passed to the `ShareAvailable`
    * If no peers were given, use discovered peers via `Discovery.Peers`
  * Request peers using `eds.Client`
* ___fallback path___ EDS
  * If ___happy path___ EDS operation does not finish within `BlockTime` timeout -- run `eds.Retriever` and wait until
    one of the paths finishes.
* Store EDS in `eds.Store`

The flow should be implemented by composing specified `Getter`s. In essence, `FullAvailability` should only depend
on correctly composed `Getter` and call `GetShares` method, awaiting its success and verifying availability.

**Comment by distractedm1nd** [comment]
Closed by #1729
