### ISSUE TITLE
[Feature Request]: Make JSON encoding consistent with Celestia-Core

### ISSUE THREAD

**Issue by preston-evans98** [celestiaorg/celestia-node#1476]
### Implementation ideas

# Background
Section 9 of [rfc 8359](https://www.rfc-editor.org/rfc/rfc8259.txt) allows JSON parsers to silently truncate numeric types to arbitrary ranges and precisions. Since this "feature" is actually implemented in [production JSON parsers](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin/18755261#18755261), JSON integer types are unreliable. 

To circumvent this issue, Tendermint serializes *some* `int` and all `int64` fields as strings (see [here](https://github.com/tendermint/tendermint/pull/7670/files)), and relies on application-level logic to convert those strings to appropriate integer types.

As a fork of Tendermint, Celestia-core inherits this behavior. So, for example, a serialized block header looks like this: 

```
{
	"header": {
		"version": {
		        "block": "11"
		},
		"chain_id": "arabica-2",
		"height": "45963",
		"time": "2022-11-29T00:14:29.836769661Z",
		"last_block_id": {
		"hash": "3B5F0613A6CB7C60BEB1DDADE9461475E5603122293E2E07E770DFE91F2A6D6C",
		"parts": {
			"total": 1,
			"hash": "8FA8BFE8AD2A3C69A888470445E254D1266D286939FBA679539D93380616471B"
		}
		},
		...
	},
}
```

On the other hand, the celestia-node `/header/` RPC endpoint uses standard JSON encoding for the tendermint header, representing numeric types as JSON numbers. 

```
{
	"header": {
		"version": {
		        "block": 11
		},
		"chain_id": "arabica-2",
		"height": 45963,
		"time": "2022-11-29T00:14:29.836769661Z",
		"last_block_id": {
		"hash": "3B5F0613A6CB7C60BEB1DDADE9461475E5603122293E2E07E770DFE91F2A6D6C",
		"parts": {
			"total": 1,
			"hash": "8FA8BFE8AD2A3C69A888470445E254D1266D286939FBA679539D93380616471B"
		}
		},
		...
	},
}
```

Since celestia-node inherits its types from celestia-core, this divergence was likely introduced in the custom marshalling logic [here](https://github.com/celestiaorg/celestia-node/blob/main/header/header.go#L160)

## Steps to Reproduce

Compile Celestia Node version `v0.5.0-rc5`:
```
$ celestia version
Semantic version: v0.5.0-rc5
Commit: 039facd94104c741f8fa995e80f1321776ae4ad3
Build Date: Mon Nov 28 17:05:56 CST 2022
System version: amd64/darwin
Golang version: go1.19
```

Start the Celestia node on Arabica testnet:
```
celestia light start --core.ip https://limani.celestia-devops.dev --gateway --gateway.port 26659
```

Wait a few minutes for the node to sync, then fetch a header:
```
curl -X GET http://localhost:26659/header/300
```
Compare the output with the output of `celestia-core` at the same height

```
curl -X POST -H "Content-type: application/json" 'http://limani.celestia-devops.dev:26657/blockchain?minHeight=300&maxHeight=300'
```

## Impact

This inconsistency prevents the use of standard Tendermint libraries including [tendermint-rs](https://github.com/informalsystems/tendermint-rs) with celestia-node.

**Comment by Wondertan** [comment]
Hello @preston-evans98 and thanks for reporting this diversion. 

I looked at the both attached json samples, but could not find any difference between them. Are they correct?

**Comment by preston-evans98** [comment]
If you look closely, you should see that the first one has `"height": "45963"` (notice the quotes around the number) while the second has `"height": 45963`. The same is true of `version.block` field.

**Comment by distractedm1nd** [comment]
Nice catch @preston-evans98, thanks for opening this issue
The custom logic was only meant to change the encoding of one type (`crypto.PubKey`) to use amino, as the default JSON output cannot be unmarshaled back otherwise.

Will look into fixing the other fields

**Comment by preston-evans98** [comment]
@distractedm1nd Any progress on this?

**Comment by preston-evans98** [comment]
@distractedm1nd I'm still seeing this problem on the latest testnet

```
$ curl -X GET localhost:26659/header/300
{"validator_set": {...} "header":{"version":{"block":11},"chain_id":"mocha","height":300,"time":"2022-12-08T21:20:52.05495665Z", ...}}
```

```
$ ./celestia version
Semantic version: v0.6.4
```
