### ISSUE TITLE
share: `Getter` interface and `IPLDGetter`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1488]
## Overview

In celestia-node, we have various sources to get the data from, and in order to compose them, we introduce
the `Getter` interface.

```go
// Getter interface provides a set of accessors for shares by the Root.
// Automatically verifies integrity of shares(exceptions possible depending on the implementation)
type Getter interface {
  // GetShare gets Share by coordinates in EDS.
  GetShare(context.Context, *Root, row, col int) (Share, error)
  
  // GetEDS gets all the shares in the form of EDS square.
  GetEDS(context.Context, *Root) (*rsmt2d.EDS, error)
  
  // GetSharesByNamespace gets all the shares of the given namespace.
  // Shares are returned in a row-by-row order if the namespace spans multiple rows.
  GetSharesByNamespace(context.Context, *Root, namespace.ID) (NamespaceShares, error)
}

// NamespaceShares represents all the shares with proofs of a specific namespace of an EDS.
type NamespaceShares []RowNamespaceShares

// RowNamespaceShares represents all the shares with proofs of a specific namespace within a Row of an EDS.
type RowNamespaceShares struct {
	Shares []Share
	Proof  *ipld.Proof
}

// Verify checks for the inclusion of the NamespacedShares in the Root and verifies their belonging 
// to the given namespace.
func (NamespaceShares) Verify(*Root, namespace.ID) error
```

### `IPLDGetter`

`IPLDGetter` stems from the existing implementation of `ShareService`, but omits to embed of `Availability`.
`IPLDGetter` verifies data integrity as it's a default IPLD behavior.

**Comment by distractedm1nd** [comment]
`IPLDGetter` shouldn't know about `eds.Store` - and because the results from the queries are not full EDSes it cannot store/cache them there anyways - but this can happen on the blockservice level (which would need to be wrapped like [this](https://github.com/walldiss/celestia-node/blob/shrex_nd/share/eds/adapters.go)).

**Comment by Wondertan** [comment]
The caching is about `GetShares` case, which requests the full EDS underneath. The `FullAvailability` will be changed to use `GetShares` instead and this caching is exactly the place where FN will store retrieved data.
