### ISSUE TITLE
share/get: `CascadeGetter`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1491]
## Overview

`CascadeGetter` implements `Getter` that composes multiple `Getters`. The composition is ordered with priority.
For every `Getter` operation, the first registered `Getter` is used. If it fails with an error or timeout from a configured
deadline controlled by context, the following `Getter` is used, and so forth, until one of them succeeds.

`CascadeGetter` must not verify date integrity and leave it up to the composing implementations.

**Comment by distractedm1nd** [comment]
Closed with #1628
