### ISSUE TITLE
node/share: Integrate `share.Getter`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1492]
## Overview

After implementing a set of `Getter`s, we must integrate and compose them according to node type requirements.

## Integration matrix 

The table below describes the composition of different Getters per node type.

|      | `StoreGetter` | `ShrExGetter` | `IPLDGetter` | `CascadeGetter` | `TeeGetter` |
|------|---------------|---------------|--------------|-----------------|-------------|
| `LN` |               | ___X___       | ___X___      | ___X___         |             |
| `FN` | ___X___       | ___X___       | ___X___      | ___X___         | ___X___     |
| `BN` | ___X___       |               |              |                 |             |

___NOTES___:

- ___X___ - node type uses column's `Getter` impl
- Columns are ordered by priority and should be supplied to `CascadeGetter` in the order, if applicable
- `TeeGetter` wraps the `CascadeGetter`
- `FN` should have a configuration option to be run with `IPLDGetter` only to enable more experiments with reconstruction.

**Comment by distractedm1nd** [comment]
Closed by #1729
