### ISSUE TITLE
Should light nodes download all available evidence?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#1503]
## Context

Evidence was moved from the the data square back to the Tendermint block in https://github.com/celestiaorg/celestia-core/pull/897 and https://github.com/celestiaorg/celestia-app/pull/1079. This has implications on the responsibilities of light nodes because now evidence isn't being DAS. It seems necessary for light nodes to download all evidence. Tagging @Wondertan @evan-forbes for awareness

**Comment by Wondertan** [comment]
@rootulp, this has to happen eventually in the form of FPs that LNs have to actively listen. They aren't fully trust minimized until we have that. Currently, LNs may follow a wrong fork caused by equivocation.
