### ISSUE TITLE
tests: TestEventLoop is flaky

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#154]
In #153 tests failed once from:
```
=== RUN   TestEventLoop
    event_test.go:38: 
        	Error Trace:	event_test.go:38
        	Error:      	Received unexpected error:
        	            	failure to retrieve data square: merkledag: not found
        	Test:       	TestEventLoop
```

**Comment by Wondertan** [comment]
@renaynay, I am starting to suspect, that this is not flakiness, but a real hidden bug, by which data is not found seriously.

**Comment by Wondertan** [comment]
Well, no

I run `go test ./service/block/ -run TestEventLoop -count 100` locally and hundred executions did not fail. With race flags, it happens though. Seems like flakiness.

**Comment by Wondertan** [comment]
Ok, so finally I found the reason, and am confident about it:
* Block processing involves the calculation of extended square and NMT trees two times
	* This simply takes a lot of time in the background while the main thread simply starts to expect the result erlier

**Comment by adlerjohn** [comment]
How long is a long time? For how big a square?
