### ISSUE TITLE
Consider moving project docs to a separate docs specific repo

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#16]
Currently, we are following the pattern of celestia-core and tendermint to include docs in the repo in [here](https://github.com/celestiaorg/celestia-node/pull/13), but ideally, docs/specs/adrs should be extracted into a separate repo.

**Comment by liamsi** [comment]
I agree with docs/specs. ADRs should be as close to the code they are affecting as possible though.

**Comment by liamsi** [comment]
It's happening 🎉 (thanks @YazzyYaz): https://github.com/celestiaorg/docs

I think we can close this one here.
