### ISSUE TITLE
service/block: request Commit from core to construct ExtendedHeader

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#161]
In tendermint/core Block's body only contains `LastCommit` while technically the `Commit` of the block is available and has to be propagated along with a [ExtendedHeader](https://github.com/celestiaorg/celestia-node/pull/153). Thus, to construct ExtendedHeader we need to request `Commit` from the core using [RPC API Commit](https://docs.tendermint.com/master/rpc/#/Info/commit).

**Comment by renaynay** [comment]
I forgot what we decided.. are we going to implement this before devnet or can we go the easier route? 

**Easier route IMO:** 
just keep `Block` in memory and wait until we get the next raw block, and take the `LastCommit` from that block and stick it in the `ExtendedHeader` of the previous block, pipe it through to Header Service for it to publish to the header topic?

**Comment by Wondertan** [comment]
@renaynay, That's not easier IMHO. We can discuss why. But implementing this issue is literally 4 loc which includes if err != nil check.

**Comment by renaynay** [comment]
No problem, if it's super quick to implement, do you mind taking it on then?

**Comment by renaynay** [comment]
You assigned me to the issue, that's why I'm wondering.

**Comment by Wondertan** [comment]
Checkout updated comment

**Comment by Wondertan** [comment]
In a place where you create an ExtendedHeader
