### ISSUE TITLE
Error: module/header: misconfiguration of syncer: invalid trusting period duration: 0s

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#1616]
### Celestia Node version

v0.6.2

### OS

macOS

### Install tools

```bash
cd $HOME
rm -rf celestia-node
git clone https://github.com/celestiaorg/celestia-node.git
cd celestia-node/
git checkout tags/v0.6.2
make go-install
make cel-key
```

### For Mocha
```bash
celestia light init --p2p.network mocha
celestia version
celestia light start --core.ip https://rpc-mocha.pops.one --p2p.network mocha
```

### For Arabica
```bash
celestia light init --p2p.network arabica
celestia version
celestia light start --core.ip https://limani.celestia-devops.dev --p2p.network arabica
```

### Expected result

Node starts as expected

### Actual result

For Mocha: https://app.warp.dev/block/OtvvB0MvH0kQCHwd61DjhI
```bash
Semantic version: v0.6.2
Commit: 534ec0df88fd885d69c04daf41c0ba10e4e1512f
Build Date: Wed Jan 18 10:37:26 EST 2023
System version: arm64/darwin
Golang version: go1.19.1
Error: module/header: misconfiguration of syncer: invalid trusting period duration: 0s
```

For Arabica: https://app.warp.dev/block/Yzii9DJhAf1tNce07a7pqV
```bash
Semantic version: v0.6.2
Commit: 534ec0df88fd885d69c04daf41c0ba10e4e1512f
Build Date: Wed Jan 18 10:37:26 EST 2023
System version: arm64/darwin
Golang version: go1.19.1
Error: module/header: misconfiguration of syncer: invalid trusting period duration: 0s
```

### Relevant log output

```bash
Above
```

**Comment by jcstein** [comment]
i removed my `~/.celestia-light-mocha` and `…arabica-2` directories entirely to test (following instructions I made [here](https://docs.celestia.org/nodes/celestia-node/#errors) a while back). [reinitialized](https://app.warp.dev/block/Zw20TIAT4ImvviCOjOGHeZ) the node and tried to start, but all failed:

[start 1](https://app.warp.dev/block/5AZM0kDSlqUr91RlsmjOaX)
[start 2](https://app.warp.dev/block/k5lBLteN92wM9wS8ge1DBm)
[start 3](https://app.warp.dev/block/2UYGaW9TL5t9j88k1eF02i)
[start 4](https://app.warp.dev/block/NoRPu6Qjv8JXKJjqseOggS)
[start 5](https://app.warp.dev/block/dhcsviWVLrlUQSOwH0kYLQ)

**Comment by Wondertan** [comment]
@jcstein, `invalid trusting period error` is thrown because the value is missing in the config, which can be fixed by manually adding it in the config and full config re-init. 

The posted logs are a different issue, which is now tracked in https://github.com/celestiaorg/celestia-node/issues/1623

**Comment by jcstein** [comment]
Thanks for explaining @Wondertan! Sounds good
