### ISSUE TITLE
Get Celestia version from git tags in Makefile 

### ISSUE THREAD

**Issue by orlandorode97** [celestiaorg/celestia-node#163]
### Summary

Get Celestia version from git tags in Makefile 

### Gain

The gain for this change is to get the `celestia` command-line version dynamically from git tags instead of having a hardcoded value.

### Evidence

This article is applying something similar: https://dev.to/eugenebabichenko/generating-pretty-version-strings-including-nightly-with-git-and-makefiles-48p3

### Implementation ideas

Instead of having a hardcoded value for the `celestia` version, we could run a shell command in the Makefile to get the version dynamically from the git tags.

### Urgency

Don't Know

**Comment by renaynay** [comment]
This was fixed by @tzdybal

**Comment by renaynay** [comment]
Wait nevermind @tzdybal only fixed the commit, but we don't have node tags yet, so reopening until we make a release.
