### ISSUE TITLE
[Feature Request]: Document perms and auth tokens

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#1633]
### Implementation ideas

Need an equivalent of this in our (node) docs (godoc + markdown/running node):
- https://docs.filecoin.io/developers/reference/json-rpc/introduction/#permissions
- https://docs.filecoin.io/developers/reference/json-rpc/introduction/#authentication

Useful info from @renaynay:
> You have you init + start a node, then from command line, do
```
celestia <node_type> auth [public|read|write|admin]
```

That is actually sufficiently covered by the help on CLI:
``` 
celestia light auth --help                                                                                     15:29:27
Signs and outputs a hex-encoded JWT token with the given permissions. NOTE: only use this command when the node has already been initialized and started.

Usage:
  celestia light auth [permission-level (e.g. read || write || admin)] [flags]
```

**Comment by renaynay** [comment]
https://node-rpc-docs.celestia.org/
