### ISSUE TITLE
[Feature Request]: Inclusion Proof API

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-node#1664]
### Implementation ideas

All Rollup Nodes that run a Celestia Light Node will need proof that a roll-up block is included in the Celestia Block.

This will be the case for every rollup, not only rollkit rollups. 

For now, we can assume the happy case that the sequencer will provide this proof and not die in the process. 

The preferable interface for this Inclusion proof retrieval will be: 
GetProof (  celestial height, namespaceID, commitment) 
VerifyProof ( inclusion proof, commitment)

The Commitment is generated like [this](https://github.com/celestiaorg/celestia-app/blob/11f3094c53628dfafe3715f1be6af3efaccc7d31/x/blob/types/payforblob.go#L135).

**Comment by Wondertan** [comment]
Noting that this was completed by blob module
