### ISSUE TITLE
libheader: Refine configuration parameters names and descriptions 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1667]
E.g. we have `MinResponses` and a comment
> // the target minimum amount of responses with the same chain head

Personally, even with being in context, I don't understand what's the purpose of this config field

Also, we have `DefaultScore`. It's clear what it does, but it's very arguable if it needs to be configured at all by the user in the config.

So in essence, this issue is about removing unnecessary configuration params and refining docs and names for it is necessary

**Comment by vgonkivs** [comment]
vote for 2.
