### ISSUE TITLE
Incorrect assumption for empty blocks on mocha

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-node#1677]
Currently, when creating the extended header, we're making the assumption that the square is empty if there are no transactions. Most of the time this is the case, but when there is evidence, this is not the case as evidence (in v0.11.1 of celestia-app and below) is also included in the square.

https://github.com/celestiaorg/celestia-node/blob/534ec0df88fd885d69c04daf41c0ba10e4e1512f/header/header.go#L45-L77

one simple solution to this is to simply always split the block into shares and create the extended data square, instead of conditionally using the minimum data availability header function (which should likely only be used for unit testing purposes).

**Comment by Wondertan** [comment]
@evan-forbes, Was there an evidence to cause such bug?

Do I understand correctly that evidence won't be included in the block in 0.12? Can we still avoid recomputing empty eds for 0.12 and further?

**Comment by Wondertan** [comment]
So we should take https://github.com/celestiaorg/celestia-node/pull/1678 and make a 0.6.4 with it to fix syncing for Bridges, but do not merge it main. 

Cc @renaynay

**Comment by Wondertan** [comment]
@evan-forbes, also out of curiosity, have you already investigated why evidence was produced? Was there a real equivocation or is it a bug somewhere?

**Comment by Wondertan** [comment]
@evan-forbes, we decided to cherry-pick your https://github.com/celestiaorg/celestia-node/pull/1678 for 0.6.4 only

**Comment by evan-forbes** [comment]
> we decided to cherry-pick your https://github.com/celestiaorg/celestia-node/pull/1678 for 0.6.4 only

yeah, that makes the most sense. We might even want to ditch that change and use the one that checks for evidence

> we decided to cherry-pick your https://github.com/celestiaorg/celestia-node/pull/1678 for 0.6.4 only

yeah, that makes the most sense. We might even want to ditch that change and use the one that checks for evidence

> also out of curiosity, have you already investigated why evidence was produced?

yeah, some small validator did actually double sign

**Comment by Wondertan** [comment]
> yeah, that makes the most sense. We might even want to ditch that change and use the one that only adds one additional condition for evidence

Your PR is OK as long as it works. Does not have to be super clean as it's temporary.

> yeah, some small validator did actually double sign
Some one is playing games its seems 😁

**Comment by evan-forbes** [comment]
closing as completed then, pls reopen if needed
