### ISSUE TITLE
bugfix(libs/syncer): data race in syncer

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#1681]
Currently, we have two simultaneous processes in the syncer:
1)  Syncing headers;
2) Appending headers in the store.
In case of a lot amount of synced headers, appending might take some time, but on the other hand, we can start another round of syncing and, `store.Head()` will return us not the latest synced head.

Proposal:
Track latest synced header in syncer.

**Comment by Wondertan** [comment]
I understand the problem, but why is it a data race?

**Comment by vgonkivs** [comment]
Bc of reading from the store, while writing into it

**Comment by Wondertan** [comment]
Yeah, but it's synchronized
