### ISSUE TITLE
make go-install doesn't replace existing installations

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#1694]
### Celestia Node version

v0.6.4

### OS

MacOS

### Steps to reproduce it

```
$ git checkout v0.6.4
$ make go-install
```

### Expected result

I expected the installed version to be `v0.6.4`

### Actual result

`make go-install` didn't replace my previous installation so when I ran `celestia version`, I saw the previous version I had installed.

```
$ celestia version
Semantic version: v0.6.2
Commit: 534ec0df88fd885d69c04daf41c0ba10e4e1512f
Build Date: Mon Jan 30 20:00:07 EST 2023
System version: arm64/darwin
Golang version: go1.19.5
```

### Notes

I was able to resolve by removing my existing installation and then re-installing:

```shell
$ which celestia
/usr/local/bin/celestia
$ rm /usr/local/bin/celestia
$ make go-install
```

**Comment by ramin** [comment]
tried and worked here
