### ISSUE TITLE
Docker image not released with latest

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#1702]
### Celestia Node version

v0.6.4

### OS

n/a

### Install tools

The Docker image for `celestia-node` was not made for `0.6.4` - latest is `0.6.3` https://github.com/orgs/celestiaorg/packages/container/celestia-node/67344277?tag=latest

### Steps to reproduce it

n/a

### Expected result

Latest = `0.6.4`

### Actual result

No container built for `0.6.4`

### Relevant log output

```Shell
docker run -e NODE_TYPE=light -e P2P_NETWORK=mocha ghcr.io/celestiaorg/celestia-node:0.6.4 celestia light start --core.ip https://rpc-mocha.pops.one --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network mocha
Unable to find image 'ghcr.io/celestiaorg/celestia-node:0.6.4' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

**Comment by MSevey** [comment]
@jrmanes is already working on fixing the docker images for all the repos, this is a duplicate.

**Comment by andy108369** [comment]
The right container image tag for mocha should be `ghcr.io/celestiaorg/celestia-node:sha-747c9e5` acc. to https://github.com/celestiaorg/celestia-node/releases/tag/v0.6.4
