### ISSUE TITLE
tests: `TestSubscriber` can hang / sometimes fails due to `context deadline exceeded`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#173]
## Proof
![image](https://user-images.githubusercontent.com/22449364/140793098-2ed9d761-37ec-4a5f-976c-9daae0ed53d9.png)

## Refs
Found in #171 

## Possible solution
There has to be a small 200 milliseconds timeout after the first Subscription on PubSub Topic. Basically, we need to ensure that peers notified each other about joining a topic before they are sending the msg. Otherwise, msg will never find a recipient.

**Comment by Wondertan** [comment]
Unfortunately, hangs still may happen. ibp2p/go-libp2p-pubsub#452 to rescue

**Comment by renaynay** [comment]
Flakey failures still happening despite libp2p fix. 

`context deadline exceeded`
