### ISSUE TITLE
[Feature Request]: Add build directory to celestia node when installing

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#1744]
### Implementation ideas

Hey guys,

so in the latest versions of celestia node, only `make install `wont work because it will error out because theres no `build` directory. So we need to either add this in or change the docs to include both `make build `and `make install`

EDIT: it actually needs `sudo make install` too, would be best if we can avoid sudo here

**Comment by Wondertan** [comment]
The [installation](https://github.com/celestiaorg/celestia-node#installation) section mentions that the `make build` should be done first. 

The `sudo` is required to install the binary into `/usr/local/bin`. We have it to avoid relying on `GOBIN` and follow standard Linux directories for binaries. If a user wants to rely on `GOBIN`, it can use `make go-install`

**Comment by jcstein** [comment]
I'm going to add to docs `make build`, as I think this will resolve the issues without adding "`sudo`" to the docs
