### ISSUE TITLE
bug(nodebuilder/share): providing `shrex.Getter` and its dependencies cause unexpected error in first sampling attempt

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#1771]
Quoted from @renaynay in #1770 :

> This PR reverts providing shrex-getter and its associated components to light nodes as they are both unnecessary for now and are buggy, causing the following error to occur:

> light node tries to sample a recent header and fails on the first try with

```
"PT2agmOhBwBuDZu++Vq+LGcATmrI9UZbJKEsvlHKlls=", "err": "getter/shrex: GetShare is not supported; getter/ipld: failed to retrieve share: promise channel was closed", "errCauses": [{"error": "getter/shrex: GetShare is not supported"}, {"error": "getter/ipld: failed to retrieve share: **promise channel was closed**"}]} 
```

> but succeeds on a second try when the catchUp routine inside the DASer samples once again over that height.

> For now, we will remove this feature (which will only impact the "speed" of the RPC call for requesting data by namespace) and debug it at a later date.

**Comment by walldiss** [comment]
Resolved https://github.com/celestiaorg/celestia-node/pull/1855
