### ISSUE TITLE
share: Full Availability

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#179]
## Background
Right now we have defined `share.Availability` interface in #171. The PR also contains a Light Availability implementation that uses Data Availability sampling to validate that shares are available. Similar to Light Availability, there should be Full Availability which instead of fetching randomized samples, fetches the whole square of shares.

## Design
The new `fullAvailability` structure should satisfy `share.Availability` interface and be placed in `service/share` directory. The `SharesAvailable` method should implement logic similar to `share.Service.GetShares`, basically loading all shares committed to the `share.Root`. 

## Side Notes
Essentially, this implements Full Node syncing logic, if combined with a DASer(#166). So when the DASer uses light light availability it performs sampling over random shares. Respectively, if the DASer depends on Full Availability it will perform fetching of all the shares, basically doing full sync.

**Comment by adlerjohn** [comment]
Instead of the full original square or the full data square, only a subset is needed (up to 3/4), and then you can reconstruct everything.

**Comment by Wondertan** [comment]
@adlerjohn, thanks for the detalization. `share.Service.GetShares` assumes extended square reconstruction

**Comment by renaynay** [comment]
This is related to `BlockService` as `BlockService` relies on `FullAvailability` to reconstruct the blocks.

**Comment by Wondertan** [comment]
> This is related to BlockService as BlockService relies on FullAvailability to reconstruct the blocks.

This is not exactly correct, as BlockService may rely on ShareService.GetShares only

**Comment by renaynay** [comment]
Then what's the point of the `FullAvailability` impl? and having `Availability` be an interface? Share service could then just identify the node type and run light or full based on `full` or `light` node type.

**Comment by Wondertan** [comment]
> Share service could then just identify the node type and run light or full based on full or light node type.

@renaynay missed this somehow. SharesService should not be aware of Node types. Simply, that's a dependency cycle. `Availability` interface is alose useful for https://github.com/celestiaorg/celestia-node/issues/180 and unissued NamespaceAvalability which would only ensure availability of some Namespace. Also, there can be helper implementations of the interface to combine different strategies into one, like having Light and Namespace availability together to get all the security from DASing while also ensuring you are storing all your namespaced application data.
