### ISSUE TITLE
modp2p: exctract bitswap into modshare

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1804]
Currently, we setup bitswap and supporting blockservice in the p2p module. However, we should move it to modshare. 
Even bitswap is a p2p protocol; it is semantically part of a share module. Its whole purpose is to serve shares in our usecase.

**Comment by ameya-deshmukh** [comment]
@Wondertan is this still available? Would love to pick it up

**Comment by renaynay** [comment]
yes it is @ameya-deshmukh , go ahead :)

**Comment by vgonkivs** [comment]
Done in scope of Shwap
