### ISSUE TITLE
share: [optimization] Random Tree walk for Light Availability

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#182]
## Background
Right now we have Light Availability that samples 2D space i.e. data square and requests random samples directly. Instead, we should perform a randomized walk for one sample per Row and optionally for Column for data square. This way, light clients will always sample Row amount of sample plus Column amount(optionally).

**Comment by Bidon15** [comment]
We can close this as there are a lot of parts that should be redesigned spec wise
