### ISSUE TITLE
share: Extend `Getter` to enable requesting proofs and adjust all the implementations

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1838]
## Overview
Current `Getter`'s method `GetSharesByNamespace` always gets __data and proofs __ by namespace, and the goal is to extend the interface enabling getting __only proofs without data__.

## Motivation
This is required for the Available method of https://github.com/celestiaorg/celestia-node/issues/1835, which checks whether some data blob is included in the main chain.

## Details
The recommended way to achieve the goal is to extend `GetSharesByNamespace` with options defined next to the interface and make each implementation handle them. An alternative could be to make separate `GetProofsByNamespace`

## Refs
Depends on #1837

**Comment by distractedm1nd** [comment]
Do we really still want this?

**Comment by Wondertan** [comment]
We have it already as a separate GetProof method. It's required for Rollkit

**Comment by Wondertan** [comment]
I see the value in this optimisation long-term. Does not hurt to keep an issue
