### ISSUE TITLE
service/share: Implement parallelisation for `GetSharesByNamespace`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#184]
Implement parallelisation for `GetSharesByNamespace` when there are multiple rows that contain the given `namespace.ID`.

**Comment by vgonkivs** [comment]
Hi @renaynay , may I take this one?

**Comment by renaynay** [comment]
Hey @vgonkivs we are currently debugging an issue with ipld + bitswap, so will wait on @Wondertan for further notice. But after that bug is fixed, that would be great!

**Comment by vgonkivs** [comment]
Ok, then I will wait until the bug will be fixed.

**Comment by renaynay** [comment]
It's been fixed! @vgonkivs

**Comment by vgonkivs** [comment]
Great. So If I understand correctly, `rowRootCIDs` and `namespacedShares` in` GetSharesByNamespace` should fill concurrently, right? Since appending is not a thread safe operation, should I protect  it by adding a local mutex or mutex should be added to `service` ?

**Comment by renaynay** [comment]
I would say the best approach is: 

step 1: figure out which rows (`rowRootCIDs`) contain the given `nID`
step 2: loop over the `rowRootCIDs` and spawn a go routine on each row to return the `namespacedShares` from that row
step 3: if even 1 error occurs, `return nil, err`.

step 2 is the only one that should be happening concurrently.
