### ISSUE TITLE
state: `SubmitPayForBlob` should support multiple blobs

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#1840]
## Overview

The current version of `SubmitPayForBlob` only supports sending only one data blob. At the same time, v0.12.0 of the app introduced the PFB version capable of sending multiple blobs per transaction, which includes them into the chain atomically. The goal is to extend `SubmitPayForBlob` to leverage the new PFB.

## Motivation 

This is required for the `Submit` method of https://github.com/celestiaorg/celestia-node/issues/1835, which allows sending multiple Blobs per call. We could implement each blob as a separate transaction, but then we lose atomicity between their transaction inclusion.

## Details

The recommended path is to extend the method to achieve the goal

**Comment by renaynay** [comment]
@evan-forbes are there any plans to provide an endpoint in app for this ^ ?

**Comment by evan-forbes** [comment]
we don't have any plans atm the use a different endpoint other than the standard one for tendermint that accepts arbitrary txs.

**Comment by Wondertan** [comment]
We don't need any custom endpoints to implement this

**Comment by renaynay** [comment]
so basically `data` field will be `[][]byte` ?

**Comment by Wondertan** [comment]
We should also allow sending two blobs with different namespaces
