### ISSUE TITLE
Import celestia-app commands into node cli

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-node#187]
If we are going to embed the celestia-app, we need a way to interact with it in order to set up a network and submit transactions. We are unable to to do these things in #176, because we don’t have the binary for celestia-app available. Two options are to install the celestia-app binary in CI/tests, or install the commands into celestia-node's cli. With either of those options, we would be able to run the typical init bash script that already exists in celestia-app, and then start the embedded celestia-app node.

Importing the celestia-app commands into the root command of celestia-node would enable us to have access to all of the needed commands, along with simplifying our devnet deployment in the short term. However, this approach would bloat the celestia-node's cli, and might add a small bit of complication as we adapt those commands to fit a celestia-node deployment. For at least the short term, I think this is best approach.

More importantly, I think this issue gives us something to think about for our offsite as we fully explore the relationship between the app and celestia-node.

ref #130

**Comment by Wondertan** [comment]
Just to clarify, this is only for Bridge Node

**Comment by renaynay** [comment]
This issue was relevant when we had an embedded core node option, but now we only rely on app for state interaction. Closing.
