### ISSUE TITLE
Enable the app's grpc server

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-node#189]
In #176, we added the possibility to embed the app inside of a celestia-node. However, we did not start the app's grpc server. This will be necessary for basic functionality of the app, such as the ability to query any state (including what we need in #28). Originally, I was planning on adding in the server in #176, but I figured that it would be better to coordinate this around our broader rpc strategy for celestia-node. 

Typically, the app's grpc server is started when calling the start command [here](https://github.com/celestiaorg/cosmos-sdk/blob/568e61059a5275d63fae7980e196ff7b6ce07426/server/start.go#L324), but to better fit with celestia-node, we will need to start the app programatically. Therefore, we can probably just make an adapter for the `grpc.Server` that turns it into a [`Service`](https://github.com/celestiaorg/celestia-core/blob/1609bde2a41604fff1ebcb202e0e9cce1048fb3b/libs/service/service.go#L23-L56), or something similar.

**Comment by Wondertan** [comment]
Just to clarify. This is only for Bridge node

**Comment by renaynay** [comment]
Not relevant anymore as embedded option has been removed.
