### ISSUE TITLE
docs: Add documentation about supported environment variables

### ISSUE THREAD

**Issue by smuu** [celestiaorg/celestia-node#1896]
### Implementation ideas

There is no documentation about environment variables you can use with `celestia-node`. You only figure them out when talking to people, creating knowledge silos, which should be avoided.

Example: https://github.com/celestiaorg/celestia-node/pull/1881/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R80

**Comment by ramin** [comment]
we've reduced this down to just `CELESTIA_HOME` which is still kind of a poweruser usage, and using different folder layouts as a flag is well documented

**Comment by Wondertan** [comment]
@ramin, there is also CELESTIA_CUSTOM, jfyi

**Comment by ramin** [comment]
ah my quick search of `os.Getenv` skipped that one we look up with `os.LookupEnv` 👊
