### ISSUE TITLE
node: Implement `Service` interface 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#19]
Implement a `Service` interface that will represent all of the "services" that will be constructed and registered on the node via DI (such as [dig](https://github.com/uber-go/dig)). I recommend this gets implemented in the `node` package rather than a separate package, but I am open to hearing arguments for separating it from `node`.

The interface should contain at a bare minimum the following behaviours: 
* Start
* Stop

**Comment by Wondertan** [comment]
As per sync discussion with @renaynay, there are two problems that the `Service` interface is meant to solve:
* Unify lifecycle methods of Components/Services in one interface.
* Ability to get Components/Services from a single map by a service/component key with the goal of runtime switchability by `Start`/`Stop`.

However, we decide to use FX which already provides a unified way to manage Componets/Services lifecycles through `fx.Lifecycle`, removing the need to have a Service interface. Also, each Component/Service can be directly accessed from `Node` struct for any purpose, so having a unified map of services is not necessary. Therefore, we decided not to go with `Service` interface.

**Comment by renaynay** [comment]
@Wondertan do you also mind posting a snippet of code or something like that that shows how lifecycles can be managed by the node via fx?

**Comment by Wondertan** [comment]
```go
type FooService struct {...}

func NewFooService() *FooService {...}

func (fs *FooService) Start(context.Context) error {...}

func (fs *FooService) Stop(context.Context) error {...}

// NOTE: Lifecycle is automatically provided to FX and we can receive from every constructor, if requested. As you can see, requests are done by writing the code - __magikkk__
func serviceBuilder(lc fx.Lifecycle) *FooService {
	fs := NewFooService()
	lc.Append(fx.Hook{
		OnStart: func(ctx context.Context) error {
			return fs.Start(ctx)
		},
		OnStop: func(ctx context.Context) error {
			return fs.Stop(ctx)
		}
	})
	return fs
}

func app() {
	fx.New(fx.Provide(serviceBuilder))
}
```

* When we start/stop `fx.App`, which gets started/stopped when we do `Node.Stop`, we also call start/stop for each hook in the right order. 

* In case we need to start/stop a Component/Service in runtime, we can keep a reference(populated by FX) on it in Node struct and directly call Start or Stop to enable/disable it.

**Comment by renaynay** [comment]
@Wondertan thanks
