### ISSUE TITLE
Initiate the embedded app's network for testing

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-node#190]
#176 introduced the ability to embed the app instead of the kvstore. This means that in order to use the app for testing, we will have to run a script, similar to [this one](https://github.com/celestiaorg/lazyledger-app/blob/master/contrib/single-node.sh), to initiate the network before we actually start the embedded node.

**Comment by renaynay** [comment]
Not relevant, no more embedded node
