### ISSUE TITLE
Gateway RPC server won't enable when it's configured from config.toml

### ISSUE THREAD

**Issue by easy2stake** [celestiaorg/celestia-node#1915]
### Celestia Node version

v0.7.1

### OS

Ubuntu 20.04.5 LTS

### Install tools

Golang version: go1.19.1

### Steps to reproduce it

1. Start the celestia bridge using the following:

```
ExecStart=/celestia/go/bin/celestia bridge start --node.config <path-to-config.toml-file> \
                                --p2p.network blockspacerace \
```

2. config.toml file should contain:
```
[Gateway]
  Address = "127.0.0.1"
  Port = "26659"
  Enabled = true
```

  
  

### Expected result

Gateway RPC server should be available on:
```
netstat -tpln  | grep 26659
tcp        0      0 127.0.0.1:26659         0.0.0.0:*               LISTEN      3238005/celestia
```

### Actual result

Gateway RPC server won't start.

### Notes

**WORKAROUND:**
It **CAN** be enabled if specified as a flag on the start command such as:
```
ExecStart=/celestia/go/bin/celestia bridge start --node.config <path-to-config.toml-file> \
                                --p2p.network blockspacerace \
                                --gateway  <<< This flag here. 
                                
```

**Comment by renaynay** [comment]
This is reproducible and an actual bug, thanks for reporting @easy2stake
