### ISSUE TITLE
(shrex/peer-manager): hash validation on subjective node start

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#1917]
### Implementation ideas

When full node started on already existing network, it has a chance to receive `shrex.Sub` message about hashes that were recent, but not the latest network head (networkhead - 1, networkhead -2 ...). In this case peer-manager will create invalidated pools for those header hashes and will wait for validation. If node is lagging behind network head a lot and won't be able to reach those headers, peer-manager might make a false positive blacklist decision. It would block those hashes with all peers for the remaining node run time.

**Comment by Wondertan** [comment]
Or we can get the header by datahash somehow

**Comment by renaynay** [comment]
Would rather not index, would rather extend message by one field.

**Comment by Wondertan** [comment]
We also agreed that indexing wont work without backward sync
