### ISSUE TITLE
Implement deletion of "expired" non-reserved data blobs

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#1931]
See https://github.com/celestiaorg/celestia-app/issues/1507

(May not be necessarily required pre-mainnet.)

**Comment by liamsi** [comment]
related issues: 
- https://github.com/celestiaorg/celestia-node/issues/671
- https://github.com/celestiaorg/celestia-node/issues/272

**Comment by renaynay** [comment]
Closing in favour of pruning epic.
