### ISSUE TITLE
Syncing issues when connected to a pruned node

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#1946]
### Celestia Node version

0.6.4

### OS

ubuntu 20.04

### Steps to reproduce it

install bridge node and connect it to a pruned celestia-app node

### Expected result

n/a

### Actual result

logs look like this (node is still on chain head but ofc cant get previous blocks):

```
 INFO        header/sync        sync/sync_head.go:150        new network head        {"height": 467388, "hash": "251ADA711E01D987F8BC4BED37C52FD58D6161D6308F1D8F9AD6D8A4EEB62BC7"}
Mar 20 18:14:18 val03-tia-t celestia[2263355]: 2023-03-20T18:14:18.164+0100        INFO        header/sync        sync/sync.go:191        syncing headers        {"from": 12801, "to": 467388}
Mar 20 18:14:18 val03-tia-t celestia[2263355]: 2023-03-20T18:14:18.165+0100        ERROR        header/sync        sync/sync.go:201        syncing headers        {"from": 12801, "to": 467388, "err": "RPC error -32603 - Internal error: height 12802 is not available, lowest height is 366858"}
```

**Comment by renaynay** [comment]
I will close this issue in the meantime in favour of an [epic to explore support for pruning in the DA network](https://github.com/celestiaorg/celestia-node/issues/1875) (for this case, we are concerned with headers, not blockdata as that will be handled in a different epic).
