### ISSUE TITLE
nodebuilder/share: Make fx.Invoke(share.EnsureEmptySquareExists) part of baseComponents

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1975]

**Comment by Chirag018** [comment]
Out of curiosity, why are we adding this option, ie, invoking, and checking for empty squares?

**Comment by Chirag018** [comment]
Got it, as it ensures we check for empty squares exists, if so notify us!

**Comment by renaynay** [comment]
It is unclear why we needed this issue to begin with, so I am closing this as unplanned for now. Thank you for your work regardless @Chirag018 🙏🏻
