### ISSUE TITLE
bad encoding: Bridge node needs to be able to generate a BEFP

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#1989]
Related to discussions that will come from https://github.com/celestiaorg/celestia-core/issues/989. 

Currently, the bridge node only receives block data and the data root in the block header from core - so if the data root is invalid, the bridge node will panic when it extends the block data and compares the data roots. It cannot generate / broadcast a BEFP bc it doesn't have the DAH. 

We need to discuss this further with core team.

**Comment by cmwaters** [comment]
Isn't it able to compute the DAH as the merkle tree of all the rows and roots of the EDS that it has reconstructed?

My limited understanding was that a bad encoding proof was simply:
- The badly encoded row or column
- The inclusion proof of that row root or row column to the data root.

**Comment by renaynay** [comment]
Yeah your understanding is correct @cmwaters . 

After further discussion with both @Wondertan and @evan-forbes, this isn't really a big issue: 

* If all bridge nodes are honest, censored block data coming from core would be caught via panic dataroot mismatch
* If any bridge nodes are malicious and are providing a fraudulently encoded block, full nodes will catch that anyway and generate/broadcast the BEFP.

So in the first case, honest bridges will stall the network on censored block data and in the 2nd case, full nodes will alert the network via BEFP.
