### ISSUE TITLE
bridge: node sends out huge number of 'dropping message to peer 12D3XXXX: queue full'

### ISSUE THREAD

**Issue by HoytRen** [celestiaorg/celestia-node#1992]
### Celestia Node version

v0.8.0

### OS

ubuntu 20.04, 22.04

### Install tools

source install with default makefile.

### Others

no change with all defaults.

### Steps to reproduce it

run node as usual, wait maybe 1 day.

### Expected result

Don't see too much spam messages in log.

### Actual result

hundreds of  message like 'celestia[344985]: 2023-03-31T15:23:53.187+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWGHqdPFz6e3D5Miwh5vrDv5TvF4JQW6iiYUA8VibJQCpF: queue full' per new block.

### Relevant log output

```Shell
Mar 31 15:23:53 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:23:53.186+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWJf5C2hmCTAkVFFeYsMFfydE4AkPkdA47bZBfAm6KxeW5: queue full 
Mar 31 15:23:53 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:23:53.186+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWNML73KwmzF71zHc3VjdhrwLoA3PexC63t8Kbc1ekJ7RN: queue full 
Mar 31 15:23:53 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:23:53.187+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWKa3xiNNf71V73L6Z9tEEC9gdGhaAKrvK3pK2tSYv1Rnn: queue full 
Mar 31 15:23:53 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:23:53.187+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWJqhvFkPKNHwmdbaVCVEM2ReNhTWCvStLGKqvFKWjzkHv: queue full 
Mar 31 15:23:53 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:23:53.187+0800        INFO        pubsub        go-libp2p-pubsub@v0.9.3/floodsub.go:95        dropping message to peer 12D3KooWGHqdPFz6e3D5Miwh5vrDv5TvF4JQW6iiYUA8VibJQCpF: queue full 
Mar 31 15:24:01 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:24:01.041+0800        INFO        header/store        store/store.go:353        new head        {"height": 134016, "hash": "66B3B9AD473574ECDD9058B76BD2C1DA29935640C7EF0CD52A0259256BBFD12E"} 
Mar 31 15:24:11 vmi1095034.contaboserver.net celestia[344985]: 2023-03-31T15:24:11.712+0800        INFO        header/store        store/store.go:353        new head        {"height": 134017, "hash": "30516AB385173D4886C82438EF8F0FE795EF763EF3F80B88B6BCC54909B40A0B"}
```

### Notes

I'm not sure this is just some spam message or here is a real bug, because I don't see a heavy load from my host. the established connections is low too. The node seems refused every connections. Simply suppress this message may not be safe.

I checked the code, this message seems come from the inner side of the pubsub module, I see it is used a lot in the code (at least 20 relative files), It's too difficult for me to locate the source of this problem, then we may need somebody who is more familiar with this module and the workflow of node than me to evaluate this issue. Or someone may give me any direction then I will try to evaluate it again.

**Comment by renaynay** [comment]
Thank you @HoytRen
