### ISSUE TITLE
node: Implement node structure

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#20]
Implement a basic `Node` structure that contains node-specific information, for example: 
* config
* libp2p host (up to @Wondertan how he wants to implement it)
* registeredServices

The following should be implemented:

- [ ] type Node
- [ ] NewNode( config )
- [ ] Node.Start()
- [ ] Node.Stop()
- [ ] Node.RegisterService() (this will be called from within the specific service's constructor)

**Comment by Wondertan** [comment]
I don't think we would need `RegisterService` with [DI](https://github.com/uber-go/dig). I'll do a basic project skeleton with it next week. You will see how it simplifies things.
