### ISSUE TITLE
fix: reduce `opts.MaxTableSize` to default for LNs

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2021]
We set badger's opts.MaxTableSize to  `64 << 20`, so that badger takes about 80mb in memory all the time. in go-badger-ds, they mention that they do not notice a significant performance impact with it set to 64, and it can be reduced to the default for LNs. But we need to actually profile light nodes first, to see how it actually effects performance!

Related: #2020

**Comment by renaynay** [comment]
Done
