### ISSUE TITLE
bridge: Observed storage bloat

### ISSUE THREAD

**Issue by AlexToTheMoon** [celestiaorg/celestia-node#2046]
### Celestia Node version

v0.8.2, 8e36597a82f3b6574669d57160844078b8bdb82d

### OS

Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-60-generic x86_64)

### Install tools

Compiling from repo.
make build

### Steps to reproduce it

ExecStart=/data/celestia/go/bin/celestia bridge start --node.config="/data/celestia/.celestia-bridge-blockspacerace-0/config.toml" --metrics.tls=false --metrics --metrics.endpoint otel.celestia.tools:4318 --p2p.network blockspacerace-0

### Expected result

Bridge node space consuming no more than ~2-3gb per 24hrs

### Actual result

![celestia TG](https://user-images.githubusercontent.com/87909854/230871509-eb56086c-0d77-4bb1-8720-63a109bc8ab9.png)

### Relevant log output

```Shell
Also want to share some logs I havent seen before, I found while resyncing bridge node : 

2023-04-10T09:12:06.366Z        ERROR   shrex-eds       shrexeds/server.go:93   server: writing status to stream        {"err": "stream reset"}
2023-04-10T09:12:06.366Z        ERROR   shrex-eds       shrexeds/server.go:93   server: writing status to stream        {"err": "stream reset"}
2023-04-10T09:12:06.370Z        ERROR   shrex-eds       shrexeds/server.go:106  server: writing ods to stream   {"hash": "F2D7832AD5B276C9AE6197ADE4AB98483F667DFB5FC1A32A7004C95AC1993315", "err": "writing ODS bytes: stream reset"}
2023-04-10T09:12:06.370Z        ERROR   shrex-eds       shrexeds/server.go:106  server: writing ods to stream   {"hash": "2AD3A261FC2B635254B8E145784EAA9AA8C9783C972F3711A1F2603CE9D8988E", "err": "writing ODS bytes: stream reset"}
```

### Notes

Looks like Bridge node pruning module, may occur failures.
Found myself jailed in the morning and reason was out of disk space. Was surprised that all space was taken by Bridge node.. In my calculation in average consumption I had enough space for ~2 month forward (even if space consumption doubled in size)
Unfortunately in the panic didnt create screen shots but data folder of bridge node was almost 300gb..
For now moved to a another node where I have more that 1TB of space (Could run on this server from beginning but didnt want use Hetnzer for validator node)
While resyncing bridge node, bridge folder was max 28gb and right now on 90% sync 
9.2G    ./.celestia-bridge-blockspacerace-0
Which means some pruning working but may occur failure like it happened with me last night.

**Comment by pciavald** [comment]
Same issue here, got jailed for running out of disk space during the night (ZKValidator)

**Comment by gaia** [comment]
Same issue here, 24GB in 30 minutes in the bridge's data folder. ran out of space and it impacted our uptime.

**Comment by renaynay** [comment]
@AlexToTheMoon the stream reset errors you're seeing are unrelated to the storage bloat.
@pciavald the pubsub messages are also unrelated.

**Comment by renaynay** [comment]
@distractedm1nd do you think the badger fixes addressed this issue? Can we close?

**Comment by distractedm1nd** [comment]
Yea this is fixed by last release
