### ISSUE TITLE
metrics: Granular control `--metrics` flag for which metrics to enable

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2076]
For example: 

```
--metrics
```
would enable **all** metrics

```
--metrics p2p,header
```

would enable only p2p and header metrics

**Comment by renaynay** [comment]
This would also alleviate need for separate `--p2p.metrics` flag

**Comment by Wondertan** [comment]
cc @derrandz

**Comment by vgonkivs** [comment]
Is it still relevant, @renaynay? Is there a use case when the user needs to enable one particular metric and does not need another? Our metrics do not spam with garbage(as e.g. some traces), so having all metrics enabled looks fine to me.

cc @Wondertan

**Comment by ramin** [comment]
my take is this is a kinda "nice to have" vs core functionality

**Comment by vgonkivs** [comment]
My point is that collecting all metrics vs collecting enabled only some of them does not affect us much. You would anyway open a dashboard for the chosen metric and check it.

**Comment by vgonkivs** [comment]
The only thing that I'd suggest to improve here is the way of how we are initing metrics. we have two different approaches across the node repo: through [params.metric  ](https://github.com/celestiaorg/celestia-node/blob/2294805ce4146058e9777976de08600354762ad4/core/exchange.go#L44) and through [invoking the function](https://github.com/celestiaorg/celestia-node/blob/2294805ce4146058e9777976de08600354762ad4/nodebuilder/settings.go#L99). Imo, the second approach looks better and does not require extra [exported](https://github.com/celestiaorg/celestia-node/blob/2294805ce4146058e9777976de08600354762ad4/nodebuilder/settings.go#L81) variables

**Comment by walldiss** [comment]
@renaynay  What are the benefits of having granular metrics? My perspective is:
- The overhead from collecting unnecessary metrics is negligible.
- The use case for partial metrics remains unclear.

**Comment by walldiss** [comment]
We discussed the subject internally and decided to move away from granular control for metrics and use single flag for all metrics at once.
