### ISSUE TITLE
bridge: error `failed to retrieve shares by namespace` when running rollup on v0.9.0

### ISSUE THREAD

**Issue by smuu** [celestiaorg/celestia-node#2089]
### Celestia Node version

v0.9.0 & v0.9.1

### OS

Docker (Alpine Linux)

### Install tools

https://github.com/rollkit/local-celestia-devnet/blob/v0.9.0/Dockerfile

`local-celestia-devnet` starts a consensus full node in validating node and starts a bridge node connected to it.
The rollup directly connects to the bridge using the `26659` port. There is no celestia light node involved.

### Steps to reproduce it

1. Have docker & docker compose installed
2. Clone https://github.com/rollkit/gm
3. In one terminal, run `docker compose -f docker/docker-compose.yaml up celestia`
4. In another terminal, run `docker compose -f docker/docker-compose.yaml up gm`
5. Please wait until it is up & running

### Expected result

No errors

### Actual result

- See an error in gm (second terminal): `ERR failed to retrieve block from DALC`
- And the first terminal, you should see a lot of the following message: `gateway gateway/util.go:9       serving request      {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}`

**Comment by jrmanes** [comment]
cc: @jrmanes

**Comment by Bidon15** [comment]
@smuu  please provide more celestia-node context in the issue
Like, the bridge node is started with a consensus full node. 
As well as there is no light node involved IIRC 🙏

**Comment by smuu** [comment]
Updated description as I have the same bug in `v0.9.1`

**Comment by renaynay** [comment]
@smuu does it work on earlier version?

**Comment by smuu** [comment]
> @smuu does it work on earlier version?

Can't reproduce the error with `v0.8.2`.

**Comment by walldiss** [comment]
Resolved by https://github.com/celestiaorg/celestia-node/pull/2074

**Comment by smuu** [comment]
> Resolved by #2074

This PR commit d375373 is included in `v0.9.x`, but I encountered this error in those versions.

**Comment by smuu** [comment]
This comes from the changes in https://github.com/celestiaorg/celestia-node/pull/2074/files#diff-8d18fdcd01756b908640b77156572fe8af0520e027691bd88beeaf8cdca5085dR114-R117 where internal error handling was changed.
Before, it was returning `{"data":null,"height":1}` and now `"getter/store: failed to retrieve shares by namespace: data not found"`. So this can be fixed on rollkit by handling the returned error correctly.
