### ISSUE TITLE
[Feature Request]: make p2p.Info RPC API public

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#2094]
### Implementation ideas

Currently, the p2p.info requires admin permissions to do lookups
https://node-rpc-docs.celestia.org/#p2p

Maybe moving to public to ease requirements on curling

**Comment by ramin** [comment]
@Bidon15 we removed the public permission, only support `read` `write` `admin`. Does it still make sense to promote this from admin, maybe make it `read`?

**Comment by Wondertan** [comment]
The p2p info is sensitive and has to be token gated
