### ISSUE TITLE
ipld: Extract IPLD plugin into separate repository

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#21]
## Goal
For ShareExchange and DASing to work we need to use IPLD implementation of NMT, which is currently located in Core. The Node needs to use it as well, so we need to extract the plugin with supporting functions into a separate repo to be used by both Core and Node repos. 

## Actions
* [ ] Create new repo #111 
* [ ] Cherry-pick plugin and `ipld` package from https://github.com/celestiaorg/celestia-core/pull/427
* [ ] Define what logic should be in the repo and what should be part of Node repo.
* [ ] Update core and close https://github.com/celestiaorg/celestia-core/issues/296
* [x] https://github.com/celestiaorg/celestia-node/issues/114

**Comment by liamsi** [comment]
Are we still planning to move this into a separate repo? I think for now we are fine with this living in node (instead of core). Should we close this and revisit once a need arises?

**Comment by renaynay** [comment]
@liamsi post mainnet likely

**Comment by liamsi** [comment]
ref: https://github.com/celestiaorg/celestia-node/issues/656

I think we can close this for now. Feel free to re-open if needed.

**Comment by Bidon15** [comment]
Grooming 12/07/2022: 

1. Moving to Post-Mainnet
2. Extraction should be done after  #878

**Comment by Bidon15** [comment]
Grooming 01/11/2022:

There is no reason to follow-up/track this issue due to a different approach and core/app won't use it
