### ISSUE TITLE
MAKEFILE: Consider renaming swamp to integration

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2104]
## Context

https://github.com/celestiaorg/celestia-node/pull/1999#issuecomment-1514634576

https://github.com/celestiaorg/celestia-node/blob/b8c24bfd76784b4c0f1c2d19d67d0cd3776af556/Makefile#L108-L109

## Problem

It isn't immediately obvious that swamp tests == integration tests. What does swamp mean? Are external contributors expected to know that swamp == integration?

## Proposal

Consider renaming swamp to integration

**Comment by rootulp** [comment]
Feel free to close if I'm the only person who has been confused by this

**Comment by Wondertan** [comment]
@renaynay, its not a good first issue, because we haven't decide with the renaming

**Comment by Wondertan** [comment]
@rootulp, I understand the confusion, and I think this falls under the documentation problem. If we would have a Readme section that explains what we mean by Swamp we would minimize the problem.

**Comment by renaynay** [comment]
I think `make-test-integration` is easier to intuitively understand than `make-test-swamp` since we have `make-test-unit` `make-test-race` etc.
@Wondertan
