### ISSUE TITLE
[Feature Request]: Change CID to reduce round trips for Bitswap to 1

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-node#2116]
### Implementation ideas

Currently, the CID is the hash of the nodes inside the NMT or the hash of the Share. 

Therefore a Light Node will ask for the child hashes of a row root as the CIDs. And then traverse the NMT to the Share. This means we have log(EDS square size) amount of roundtrips as this is the height of the NMT tree. 

The idea is to have the position in the share derive the CID. To uniquely identify the share, you would use the hash(height of celestia, index in the square). The index would be from [0, EDS squaresize ^2 -1]. 

After an IWANT[h1,h2,h3...], you will be getting a (share, path to share, celestis-height) as a response. The path is the merkle proof to the share. From this proof, you can derive the position inside the square. Now you can point to the shares directly without traversing the tree.

Bitswap is content addressable and expects the CID to match the data. Therefore the hash would need to match the data provided on a Bitswap level. Fortunately, it supports custom hash schema. 

custom_hash(share,path,height) = hash(height,extract_index(path))

The resulting effect would be to reduce the Network load on Sampling Light Nodes.

**Comment by musalbas** [comment]
Why not just request the actual coordinates of the share, without sending proof?

**Comment by nashqueue** [comment]
The LN is requesting the coordinates. (through the index) . 

You need to send the Merkle proof of the Root. Basically, instead of traversing the ODS and giving you one Node at a time, Bitswap will give you all relevant nodes at once.

**Comment by ramin** [comment]
should be taken care of with shwap

**Comment by nashqueue** [comment]
I think we can close this now with Shawp 🚀
