### ISSUE TITLE
“context deadline exceeded” error when I query shares.

### ISSUE THREAD

**Issue by danielgxm** [celestiaorg/celestia-node#2118]
### Celestia Node version

0.9.1

### OS

kubuntu 22.04.2

### Install tools

go version go1.20.3 linux/amd64

### Steps to reproduce it

I'm learing this tutorial : https://docs.celestia.org/developers/node-tutorial/ . Everything is OK but I got a error "context deadline exceeded" when I query shares. 

I start a light node with `celestia light start --core.ip https://grpc-blockspacerace.pops.one --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network blockspacerace`

### Expected result

It should return a message like this: 
{
  "shares": [
    "DCBNOWAP3dMBAAAAG/HyDKgAfpEKO/iy5h2g8mvKB+94cXpupUFl9QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  ],
  "height": 4249
}

### Actual result

context deadline exceeded

**Comment by danielgxm** [comment]
![图片](https://user-images.githubusercontent.com/6936589/233575400-e6af4cff-3397-4da0-a491-353c5e24219a.png)

**Comment by renaynay** [comment]
Will be fixed by https://github.com/celestiaorg/celestia-node/pull/2108
