### ISSUE TITLE
testing/integration: implement shrex suite

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#2119]
As Shrex is a new feature in the node repo, we need to take care of covering it on an integration level. 
There are 2 ways of achieving this. 

1. Swamp tests 
2. DevOps + App are coming up with the solution of making robusta + this https://github.com/celestiaorg/celestia-app/pull/1586 to be available to run on every PR

**Comment by Wondertan** [comment]
We have ShrexEDS part coverage in Swamp via syncing tests and ShrexND are missing
