### ISSUE TITLE
testing/integration: implement blob suite

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#2120]
As blob module is a new feature in the node repo, we need to take care of covering it on an integration level.
There are 2 ways of achieving this.

1. Swamp tests
2. DevOps + App are coming up with the solution of making robusta + this https://github.com/celestiaorg/celestia-app/pull/1586 to be available to run on every PR

Ref: https://github.com/celestiaorg/celestia-node/issues/1841

**Comment by vgonkivs** [comment]
https://github.com/celestiaorg/celestia-node/blob/main/nodebuilder/tests/blob_test.go
