### ISSUE TITLE
Bridge node returns errors when rollup requests data that does not exist

### ISSUE THREAD

**Issue by smuu** [celestiaorg/celestia-node#2128]
### Celestia Node version

v0.9.0 and v0.9.1

### OS

Docker (Alpine Linux)

### Others

This was introduced by https://github.com/celestiaorg/celestia-node/pull/2074 probably [this lines](https://github.com/celestiaorg/celestia-node/pull/2074/files#diff-8d18fdcd01756b908640b77156572fe8af0520e027691bd88beeaf8cdca5085dR114-R117).

### Steps to reproduce it

To reproduce this behavior, you will start a consensus validator and DA bridge using `local-celestia-devnet` and start the gm rollup on top of it.

1. Clone [rollkit/gm](https://github.com/rollkit/gm)
2. Navigate to the `docker` directory
3. Start local-celestia-devnet with `docker compose up celestia`
4. Open a second shell
5. Start the rollup node with `docker compose up gm`
6. Wait until you see errors in the first shell
7. To clean up, you can use `docker compose down`

### Expected result

That celestia-node does not throw errors when a rollup requests data that does not exist.
The rollup receives an error as a response, and they can handle this appropriately.

A rollup requests all data from his namespace. So this would clutter the log with many errors when running many rollups.

### Actual result

```
docker-celestia-1  | 2023-04-25T11:57:57.633Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:57.735Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:57.837Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:57.938Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.040Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.142Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.243Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.345Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.446Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
docker-celestia-1  | 2023-04-25T11:57:58.548Z   ERROR   gateway gateway/util.go:9serving request  {"endpoint": "/namespaced_data", "err": "getter/store: failed to retrieve shares by namespace: data not found"}
```

**Comment by renaynay** [comment]
@smuu I don't understand the issue here - does the Rollup get an unintelligible error or no error at all? What's wrong with the client-side portion of this?

**Comment by renaynay** [comment]
@smuu Can we close this?
