### ISSUE TITLE
service/header: change Broadcaster from interface to struct

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#214]

**Comment by renaynay** [comment]
Now that `BlockService` is only responsible for reconstructing block from shares and `HeaderService` is responsible for constructing new `ExtendedHeader`s and broadcasting them, `broadcaster` doesn't need an interface and can be a private struct instead.

**Comment by Wondertan** [comment]
@renaynay should we close this one already?

**Comment by renaynay** [comment]
Not until #327 is merged.
