### ISSUE TITLE
bug(shares/GetSharesByNamespace): missing response type `ErrNamespaceNotFound`

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2145]
In the current implementation, the response from a shrex-nd server for "Hey, my EDS store doesn't have that EDS, so I can't give you the ND" and "Hey, that EDS is in my store, and the data you are looking for doesn't exist in it" are the same. This causes many issues in the stack, leading to a timeout for `GetSharesByNamespace` calls, even when the correct response has been found. This will clearly require a protocol breaking change.

This must also be fixed in CascadeGetter, which should recognize the difference between `ErrNotFound`, which moves onto the next getter, and `ErrNamespaceNotFound`, which should return the data and error.

This means IPLDGetter should also return a `share.ErrNamespaceNotFound` for the same reason.

**Comment by nashqueue** [comment]
Is this related : https://github.com/rollkit/rollkit/issues/897 ?

**Comment by distractedm1nd** [comment]
@nashqueue yes, partially

**Comment by jcstein** [comment]
I'm getting something similar on a rollup, just every so often though

```bash
da  | 2023-05-03T19:44:32.020Z	ERROR	ipld	ipld/namespace_data.go:216	getLeavesWithProofsByNamespace:could not retrieve node	{"nID": "\ufffd\ufffd\ufffdy\ufffdq\u0016\ufffd", "pos": 0, "err": "context canceled"}
```

**Comment by jcstein** [comment]
I made an issue for the error above, as I believe the error is different, but related https://github.com/celestiaorg/celestia-node/issues/2174
