### ISSUE TITLE
`failed to find peers: routing: not found`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2152]
### Celestia Node version

v0.9.1

### OS

mac, using docker image

### Install tools

same as #2151 

### Steps to reproduce it

same as #2151 

### Expected result

no error, finds peers

### Actual result

<img width="2168" alt="scrot 2023-05-01 at 10 19 11 PM" src="https://user-images.githubusercontent.com/46639943/235565674-2c00412d-495e-4533-86a2-01493aa150f3.png">

### Relevant log output

https://gist.github.com/jcstein/8a0be27717c7bf3365102749b6c8f504

### Notes

https://testnet.mintscan.io/celestia-incentivized-testnet/account/celestia1dryz4jmgwde8v25ea5rem955n0rrlnvx8kmtjz

**Comment by renaynay** [comment]
Thanks for the report @jcstein

**Comment by jcstein** [comment]
You're welcome @renaynay!

**Comment by jcstein** [comment]
it appears that the frequency may have increased, based on these [logs in a gist](https://gist.github.com/jcstein/1ce241893593bdec0de39b9ea633ac91)🤔

**Comment by renaynay** [comment]
Hopefully should be fixed by v0.9.2 @jcstein, going to close this for now and re-open if issue persists

**Comment by jcstein** [comment]
Yep! It seems like it was resolved 🤞
