### ISSUE TITLE
`getLeavesWithProofsByNamespace:could not retrieve node`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2174]
### Celestia Node version

v0.9.2

### OS

mac/linux

### Steps to reproduce it

This is from running a rollup and the full logs can be found [here](https://drive.google.com/file/d/1bWFBiqsH9dY3-3IjL0uJ7p_j0Zl6vxe3/view?usp=share_link)

### Expected result

shares are retrieved, no error

### Actual result

`ERROR   ipld    ipld/namespace_data.go:216  getLeavesWithProofsByNamespace:could not retrieve node  {"nID": "\ufffd\ufffd\ufffdy\ufffdq\u0016\ufffd", "pos": 0, "err": "context canceled"}`

**Comment by jcstein** [comment]
Seeing this occur on v0.11.0-rc1 of node:

```Shell
ERROR	ipld	ipld/namespace_data.go:216	getLeavesWithProofsByNamespace:could not retrieve node	{"nID": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0008\ufffd\ufffdy\ufffdq\u0016\ufffd", "pos": 0, "err": "context canceled"}
```

**Comment by Wondertan** [comment]
@walldiss, @distractedm1nd, seems like we cancel ShrexND and move to IPLD and then it also gets canceled

**Comment by jcstein** [comment]
cc @tuxcanfly
