### ISSUE TITLE
tests: TestExtendedHeaderBroadcast hangs

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#218]
![image](https://user-images.githubusercontent.com/22449364/142520408-84bb80b1-3e90-4200-a3c6-58c43e29a80a.png)

Again, cc @renaynay

**Comment by renaynay** [comment]
This is on CI or locally @Wondertan ? I can't repro locally.

**Comment by Wondertan** [comment]
All of those are also on CI

**Comment by renaynay** [comment]
Waiting to see if this issue pops up again.

**Comment by Wondertan** [comment]
This test does not exists anymore so closing
