### ISSUE TITLE
Write basic project skeleton with DI

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#22]
## Goal
The project is intended to grow with a variety of components and services in it. To remove the time and mental overhead of writing and updating node initialization logic, where we build and order all the components ourselves, we should delegate that to a [DI](https://github.com/uber-go/fx). There are multiple options, but Uber's one is solely based on reflection and does not involve code-generation. Even reflection is considered to be slow, the slowness manifests only on node build time, not the runtime.

**Comment by liamsi** [comment]
Can you push your changes to some branch and link them here maybe? I think that will make the purpose of this issue clearer. I see how dependency injection can be useful but this issue seems somewhat detached as it merely signals the intention to use a particular DI library.

**Comment by liamsi** [comment]
Oh I see, you are suggesting to use uber's application framework (which makes use of uber's DI library) too. https://github.com/celestiaorg/celestia-node/pull/29

I don't have any preference here. Let's make the issues more descriptive than "let's use library X, Y". You can use whatever libraries you want. Just keep in mind the following:
 - a large dependency graph is undesirable from many perspectives (security, complexity)
 - the user should not be forced in dealing with completely different UX (e.g. different config file formats, or very different ways to invoke commands).
