### ISSUE TITLE
share/p2p: Shrex should not discard peers from a single failure 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2213]
We agreed to drop peers in case of a single failure in Shrex protocols. However, this is too aggressive, and on real networks, various non-critical failures happen that can be solved with a simple retry.

We decided to implement this later with future refactorings, as currently, the retry implementation brings complexity. Until that point, we will also have more data from metrics to prove that retries are needed.

**Comment by distractedm1nd** [comment]
This isnt being done, so closing

**Comment by Wondertan** [comment]
> This isnt being done (...), so closing

😁

Let's rephrase this one instead of closing. We still _are going to_ drop peers and will need to implement retries.

On the second read, this issue just states that we agreed on dropping peers(still true) and not that it's is implemented, so there is nothing even to rephrase.


I think we should reopen this and keep as an issue for retries linked to shrex hardening/next step higher order issue

@distractedm1nd
