### ISSUE TITLE
nodebuilder/test: find a way to test BEFP with App/Core generating them

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2216]
Since #2215, we have skipped BEFP testing due to a bug. However, we still must test BEFPs, and the only way is to make validators sign over a faulty header. This requires changes to the App/Core to allow us generating a fraud at a certain height.

**Comment by Wondertan** [comment]
cc @evan-forbes, @rootulp and @cmwaters if have any ideas on how to accomplish this

**Comment by cmwaters** [comment]
Should be too difficult, the light package in core has a bunch of tests with fabricated headers. It has this keys struct which it uses to create all the keys of the validators and to generate headers
