### ISSUE TITLE
share/p2p: ShrexEDS should produce BEFP

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2225]
Right now, FN only produces BEFPs during reconstruction, but it can happen over shrex as well, so we must accommodate for that

**Comment by Wondertan** [comment]
In the current flow, the ShrexEDS falls back to IPLD reconstruction which will eventually generate BEFP so we are safe. However, we don't need to fallback as we already have a proof that block is incorrect.

**Comment by distractedm1nd** [comment]
I see, so the fix would be to catch the error on content integrity mismatch during `Put` and generate a BEFP?

**Comment by Wondertan** [comment]
I think it would be during `ReadEDS`. This is where EDS compute happens, which can throw ErrBysantine, so it should be handled properly.

**Comment by vgonkivs** [comment]
I'm not sure about `ErrByzantine` in ReadEDS, because ReadEDS uses `ComputeExtendedDataSquare` that does not check for the byzantine error. But I think Having such a check for the EDS in rsmt2d will be good.

**Comment by Wondertan** [comment]
Good point

**Comment by vgonkivs** [comment]
The other case is to do "Repair" inside ReadEDS. As we already have the ods, we can simply repair the eds and catch BEFP if it appears.

**Comment by vgonkivs** [comment]
Also, for this particular case, we should do an extra check in order to verify the inclusion of the shares to avoid a situation when we get invalid ods from some peer and generate a BEFP
