### ISSUE TITLE
feat: dagstore recovery when shard mounts cannot be found locally

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2233]
The only case we have seen so far for dagstore corruption is when the index contains shards whose mounts cannot be found on disk. These heights are clearly unrecoverable until we resample over them. Because other components of the node assume these heights have already been sampled, there is currently no mechanism to "audit" the dagstore's indexes to ensure that we can retrieve all shards we think we have. Since we have the datahash for these shards, we can possibly use shrex as some sort of remote mount as a fallback when we cannot find them locally (but this is just a quick idea, needs research).

**Comment by ramin** [comment]
will be irrelevant after shwap
