### ISSUE TITLE
Kernel Panic 

### ISSUE THREAD

**Issue by dakk** [celestiaorg/celestia-node#2236]
### Celestia Node version

0.9.5, but we experienced the same problem also on previous versions

### OS

Ubuntu 22.04.2 LTS

### Install tools

The node is running on a proxmox container using a systemd service with this the following ExecStart:

```
/usr/local/bin/celestia light start --core.ip https://grpc-blockspacerace.pops.one/ --core.grpc.port 9090 --keyring.accname my_celes_key --metrics.tls=false --metrics --metrics.endpoint otel.celestia.tools:4318 --gateway --gateway.addr 0.0.0.0 --gateway.port 26659 --p2p.network blockspacerace
```

### Actual result

As we already told here (https://medium.com/@openbitlab/our-celestia-light-node-performance-in-the-itn-9a7291b9b90b), our Celestia dedicated server is randomly crashing with a kernel panic; this time we were able to log the klog using netconsole.
Even if we changed (for this reason) the server, the farm and the provider, the issue is still happening on the new server.

A similar issue is happening also to another user: https://github.com/celestiaorg/celestia-node/issues/2097#issuecomment-1523015566 

If @blockonaut solved the problem by using an Intel CPU, we suspect is an issue with AMD Ryzen CPUs.

### Relevant log output

```Shell
https://gist.github.com/dakk/3fb35a850ce29ad6e45178503fb4cba2
```

**Comment by Wondertan** [comment]
> If @blockonaut solved the problem by using an Intel CPU, we suspect is an issue with AMD Ryzen CPUs.

I can confirm crashes happen on AMD Ryzen CPUs server, but never happened on my Intel based laptop

**Comment by Wondertan** [comment]
@renaynay, do you know which CPU your Droplet is running?

**Comment by dakk** [comment]
It crashed again today also on the latest 0.10 version

**Comment by mindstyle85** [comment]
hey guys, just wanna chime in that i know of at least 3 validators with bridges that use AMD Ryzen 9 and that works, dont know about EPYC

**Comment by AviaOne** [comment]
Semantic version: v0.10.0
Commit: cd8d0b9afd6dd982c43ab306cb9b160e985c6da1

Bridge is crashing around every 10 hours, seems the new version did not change anything.

All details : Screenshots and /var/log/syslog here :
https://discord.com/channels/638338779505229824/1077529191530106890/1110838893785391225

**Comment by Wondertan** [comment]
@AviaOne, thanks for reporting. Can you share more information about the hardware, arch, and os you run with? 

I checked the posted logs and didn't see anything suspicious there(besides the goroutine dump which is irrelevant). Can you collect more logs coming from dmesg?

**Comment by spidey-169** [comment]
Bridge node is crashing for me too, frequently, every couple of hours. It just gets stuck after sometime and only gives canonical-log messages without generating new headers. Running on Hetzner AX61 nodes

`May 24 17:38:41 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:38:41.155+0200        INFO        canonical-log        swarm/swarm_listen.go:132        CANONICAL_PEER_STATUS: peer=12D3KooWFiSKtzC35BbL2KyUyXjW1oZSdKw1xr9FhToBNrGU4kGy addr=/ip4/109.205.181.232/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="inbound"
May 24 17:39:20 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:39:20.979+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWHwvrkwErLWPbtkEKs2icba8xennZqscQz17XNYmV1HRB addr=/ip4/89.117.62.12/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 17:43:02 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:43:02.895+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWFVx58aB5aMPjr2ULx16e9N2hVqbQQurdug3WsiwdfaBo addr=/ip4/91.107.205.207/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 17:47:02 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:47:02.899+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWNkwiS2FXNyyxYBK6UQe69jLVyTZYYWmKGgKn1aXARNjd addr=/ip6/2a01:4f8:221:4267::2/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 17:48:15 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:48:15.375+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWQh61NWiVJUPcDQ3ybQFFXUduv6wK1b9DcfQFHzz3Mq1F addr=/ip4/38.242.196.71/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 17:52:51 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:52:51.204+0200        INFO        canonical-log        swarm/swarm_listen.go:132        CANONICAL_PEER_STATUS: peer=12D3KooWFiSKtzC35BbL2KyUyXjW1oZSdKw1xr9FhToBNrGU4kGy addr=/ip4/109.205.181.232/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="inbound"
May 24 17:57:41 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T17:57:41.139+0200        INFO        canonical-log        swarm/swarm_listen.go:132        CANONICAL_PEER_STATUS: peer=12D3KooWRFa8fMzSwQLo9e9PH1hUwZpagvAfHfnkNrSBUXekj1A4 addr=/ip4/161.97.128.237/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="inbound"
May 24 18:00:13 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T18:00:13.026+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWMqN5YdunKJSj5WMXWDaoHjhLQ6t65tcw9m4TzMq4P6Ad addr=/ip4/154.53.52.35/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 18:01:13 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T18:01:13.797+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWLr6vFGtyL1R5SHPDhB7vsEaTtCS5rgNLWyLCWw3dN8SN addr=/ip4/81.102.139.165/udp/33469/quic-v1 sample_rate=100 connection_status="established" dir="outbound"
May 24 18:05:20 Ubuntu-2004-focal-amd64-base celestia[1003213]: 2023-05-24T18:05:20.798+0200        INFO        canonical-log        swarm/swarm_dial.go:500        CANONICAL_PEER_STATUS: peer=12D3KooWDvboUhCmJPxtjeYDW7q7Drm9VoxnTCfEznvgwTn8KcR6 addr=/ip4/173.249.36.233/udp/2121/quic-v1 sample_rate=100 connection_status="established" dir="outbound"`

**Comment by Wondertan** [comment]
@spidey-169, so does it crash or get stuck? By crashing, we mean Kernel Panic.

**Comment by spidey-169** [comment]
> @spidey-169, so does it crash or get stuck? By crashing, we mean Kernel Panic.

Looks like it actually gets stuck for me and that happens within an hour. So not crashing but freezing.

**Comment by Wondertan** [comment]
@spidey-169, pls make then another issue with freezing, and we can discuss your freezing problem there

**Comment by AviaOne** [comment]
"Can you share more information about the hardware, arch, and os you run with?" 
I gave you already these information, 
Please go check again with the same link (above), and check carefully the screenshots.
Same time, you will see the ligne number inside/var/logs where we can see Kernel Panic
Thanks

**Comment by AviaOne** [comment]
/var/log/dmesg[](url)
[dmesg.txt](https://github.com/celestiaorg/celestia-node/files/11560417/dmesg.txt)

**Comment by AviaOne** [comment]
/var/log/syslog
Please have a look ligne 85328 you will see the Kernel panic..
[syslog.txt](https://github.com/celestiaorg/celestia-node/files/11560440/syslog.txt)

There is an other Kernel Panic in these logs, should be found...

**Comment by AviaOne** [comment]
???

**Comment by renaynay** [comment]
@AviaOne @Wondertan is actively looking into this issue, thanks for your patience.

**Comment by AviaOne** [comment]
KERNEL PANIC to the validator with the same issues.
This is not the best solution but it can be an alternate ans help to keep the bridge alive and improve the uptime.
Inside your server (bridge v0.10.2), add the following in this file `sudo nano /etc/sysctl.conf`
`kernel.panic = 20`
It will reboot after a panic after 20 seconds, and you will not need to do it manually from the hosting interface !

**Comment by Wondertan** [comment]
@AviaOne, good tip.


A small update. We were not able to reproduce the panic on kernel 6.x

**Comment by AviaOne** [comment]
A lot of validators are in the same case and waiting an update for this issue.
Would you like to get the root access to my server ? 
I can't use it for something else than this bridge shuting down every 3 hours !
You will be able to reproduce the panic on kernel 6.x :-) and working directly on this issues facing by many validators...

**Comment by Wondertan** [comment]
> A lot of validators are in the same case and waiting an update for this issue.

It takes a while to understand what's really happens. What's clear is that this is a networking issue, specifically of the TCP stack. There are quite a few points that talk over TCP within the node:
* libp2p
* CoreClient
* Telemetry
* HTTP server
* RPC server

We are still in the process of locking into it. The interesting thing is that I couldn't reproduce the panic on 6.x after running for a week, while on 5.x it crashed almost every night.  So I am particularly curios on this point
> You will be able to reproduce the panic on kernel 6.x :-)

Also, does this happen only for BNs? Do you run validator on the same machine/cluster or connect to remote node?

**Comment by AviaOne** [comment]
Hi @Wondertan ,
I made this huge mistake, running the bridge on the same server with my validator !
This will definitely create a huge damage on my reputation to be selected as validator for the mainnet. 
It completely destroyed my uptime and pushed me down with the ranking of newbies !
I was running both on a dedicated server high grade, now the bridge have been isolate and stay alone.
My offer to get the root access on this bridge node is still OK.
It will be easy to reproduce the panic issue, it happen every 12 hours minimum ! 
That's really the best place to track this issues...
