### ISSUE TITLE
State Sync failure 

### ISSUE THREAD

**Issue by AlexToTheMoon** [celestiaorg/celestia-node#2237]
### Celestia Node version

celestia-appd, 0.13.0, 6ba60e18fec27d3e3a42a71be082e255913cf4cf 

### OS

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-71-generic x86_64)

### Install tools

From source 

### Steps to reproduce it

SNAP_RPC="http://65.108.44.149:36657"; \
LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
BLOCK_HEIGHT=$(($LATEST_HEIGHT - 4000)); \
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash); \
echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH

sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ; \
s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ; \
s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ; \
s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"|" $HOME/.celestia-app/config/config.toml

### Expected result

Snapshot restored.

### Actual result

ERR State sync failed err="snapshot restoration failed: app version mismatch. Expected: 1, got: 0" module=statesync

### Relevant log output

```Shell
6:40PM INF Applied snapshot chunk to ABCI app chunk=16 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=17 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=18 format=2 height=549000 module=statesync total=20
6:40PM INF Applied snapshot chunk to ABCI app chunk=19 format=2 height=549000 module=statesync total=20
6:40PM ERR State sync failed err="snapshot restoration failed: app version mismatch. Expected: 1, got: 0" module=statesync
```

### Notes

 I noticed that my snapshot service not producing state synced snapshots anymore (It been working  perfectly since testnet launched). I have my state synced machine setup through private connection to my RPC/Snapshot node (archive node, no pruning) which making snapshots  :
 snapshot-interval = 2000
 snapshot-keep-recent = 3
 And now every time I try state sync I got error : 
 State sync failed err="snapshot restoration failed: app version mismatch. Expected: 1, got: 0" module=statesync
 All what I found regarding versions is that Snapshot node binaries were compiled on : 
 go version go1.20.3 linux/amd64 
 On state sync machine celestia-appd binaries were compiled on:
 go version go1.19 linux/amd64
 But both got : version: 0.13.0, commit: 6ba60e18fec27d3e3a42a71be082e255913cf4cf

**Comment by renaynay** [comment]
please open this issue on celestiaorg/celestia-app please @AlexToTheMoon

**Comment by AlexToTheMoon** [comment]
Ok sry, mixed up
