### ISSUE TITLE
`context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2250]
### Celestia Node version

v0.10.0

### OS

Ubuntu

### Steps to reproduce it

https://docs.celestia.org/developers/optimism/

### Expected result

Data is retrieved

### Actual result

After the error in https://github.com/celestiaorg/celestia-node/issues/2241, the error in this issue occurs.

### Relevant log output

```Shell
op-node_1      | t=2023-05-24T10:43:56+0000 lvl=warn msg="unable to retrieve data from da"        origin=0x7e1ab53b2a7278daf02bfe802162f10081463714534069d6509a8dbd9c5571ba:2804 err="share sequence has [23/84$
s but needed 0 shares"
op-node_1      | t=2023-05-24T10:47:26+0000 lvl=warn msg="unable to retrieve data from da"        origin=0x90622c2dd2813ec77f3f39539e5182d03fd28131ff4c3f3907152c925f0cce4f:2816 err="Get \"http://da:26659/name
spaced_data/e8e5f679bf7116cb/height/562992\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
op-node_1      | t=2023-05-24T10:49:56+0000 lvl=warn msg="unable to retrieve data from da"        origin=0xae7007627a3cedbd97ae35588f5de368cb463ed92b20119c948aaa1873d865dd:2826 err="Get \"http://da:26659/name
spaced_data/e8e5f679bf7116cb/height/563005\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```

### Notes

[Full logs available here](https://github.com/jcstein/logs/blob/main/v0.10.0-run-3.log)

**Comment by Wondertan** [comment]
I looked into it, and its not the celestia-node produced error. It's either go-cnc client or optimism's code. 

What's clear is that this problem is either the timeout is too low, or the node fails to retrieve data.
Do you run this over the synced-up node? If so, how do you check it's synced?

**Comment by tuxcanfly** [comment]
@Wondertan yeah this was happening after the node has been synced up and running for a while.

although the logs above show `share sequence has [23/84$s but needed 0 shares` this also occurs following a `head request to trusted peer failed `
