### ISSUE TITLE
bug: discovery cannot find peers after network disconnect 

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#2258]
### Problem

I had experienced network going offline for few seconds while running node. It caused 2 problems related to discovery:
 - Network disconnect caused discovery to lose all peers and never recover the peer amount until node restart restart. 
 - After restart discovery was able to find enough peer, but lost them due to peer enforced disconnects shortly after. Even tho discovered peers has been disconnected, lowering size of discovery set, the new discovery search was not triggered.
 
<img width="861" alt="Screenshot 2023-05-26 at 16 25 47" src="https://github.com/celestiaorg/celestia-node/assets/13818348/d34f0ae9-110f-403e-9b2d-83649e2671f6">
<img width="861" alt="Screenshot 2023-05-26 at 16 27 59" src="https://github.com/celestiaorg/celestia-node/assets/13818348/87aee829-2f11-4236-b687-3b9adc9029ea">

[log.txt](https://github.com/celestiaorg/celestia-node/files/11575685/log1.txt)

 The problem in discovery is related to new search trigger not working correctly. Solutions options:
 -  Quick fix would be to trigger discovery once in period of time.
 - Debug the triggering condition logic and find the root cause

**Comment by Wondertan** [comment]
> Even tho discovered peers has been disconnected, lowering size of discovery set, the new discovery search was not triggered.

How do you know the discovery was not triggered?

**Comment by Wondertan** [comment]
> peer enforced disconnects shortly after

What do you mean by "peer enforced"? Remote peers disconnected from your node?

**Comment by walldiss** [comment]
>I remember @distractedm1nd had a similar issue. We concluded that we were out of peers as they all got disconnected and in the backoff. Could this explain this issue?

I think the answer is no. I've made a metric for it.
<img width="861" alt="image" src="https://github.com/celestiaorg/celestia-node/assets/13818348/b64e0921-cd0a-4fad-9438-8ec7d111c55a">

>How do you know the discovery was not triggered?

There is no discovery events in logs. It is attached to the issue

>What do you mean by "peer enforced"? Remote peers disconnected from your node?

Yes, peer disconnected from my node. Check `removed peer` metric

**Comment by Wondertan** [comment]
Ok. Makes sense. I am inclined to investigate the code and if we find no answer until Monday, we can do a quick fix.

**Comment by ramin** [comment]
no longer happening
