### ISSUE TITLE
No 0.10.1 container available

### ISSUE THREAD

**Issue by bert2002** [celestiaorg/celestia-node#2265]
### Celestia Node version

0.10.1

### OS

Docker

### Steps to reproduce it

Hi,
it seems there is no docker container available yet. When will it be released?

```
# docker pull ghcr.io/celestiaorg/celestia-node:v0.10.1
Error response from daemon: manifest unknown
```

### Expected result

Docker container tagged with the same version.

### Actual result

Tagged container not available.

**Comment by Wondertan** [comment]
> docker pull ghcr.io/celestiaorg/celestia-node:v0.10.1

We accidentally missed adding `v` in the release. Now, that it fixed, try again
