### ISSUE TITLE
Blob Module usage example 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2278]
In https://github.com/celestiaorg/celestia-node/pull/2273 we introduced the most anticipated feature for celestia-node. 

Now, we need something similar to https://github.com/renaynay/da-rpc-client-tutorial/blob/main/main.go to showcase how easy it is to use and submit and retrieve data through celestia-node

**Comment by Chirag018** [comment]
Hey, @Wondertan would like to work on this
