### ISSUE TITLE
node: Implement graceful shutdown

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#228]
Related to #82.

Reference [this article](https://rudderstack.com/blog/implementing-graceful-shutdown-in-go/) for new ideas.

**Comment by Wondertan** [comment]
it's unrelated to the node's logic. Node logic implements graceful shutdown. Pls create another one if the issue still persists, but AFAIU, the new DASer logic fixes this and improves shutdown logic substantially, so I am closing this. cc @walldiss
