### ISSUE TITLE
share/ipld: don't use `MustCidFromNamespacedSha256` to avoid panicking

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2285]
https://github.com/celestiaorg/celestia-node/issues/2282 showed that LN can panic if the wrong namespace size is given. This is due to `MustCidFromNamespacedSha256`, which may seemed like a good idea along ago, but now it's DOS vector that we should prevent.

**Comment by Wondertan** [comment]
The essence of the issue here is to remove all the usages of `MustCidFromNamespacedSha256` in the non test code. Instead, we should use the version that returns an error. We should also ensure that the error returned from `CidFromNamespacedSha256` is wrapped with a user-friendly error explaining the severity of the issue. Specifically, it means that Vadlidators encoded incorrect data.

**Comment by ramin** [comment]
will be resolved by shwap
