### ISSUE TITLE
gateway: /submit_pfb uses namespace ID without version byte

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/celestia-node#2292]
### Celestia Node version

v0.11.0-rc1

### OS

darwin/arm64

### Install tools

go-cnc v0.3.0

### Steps to reproduce it

Submit PFB to the endpoint `http://127.0.0.1:26657/submit_pfb`

### Expected result

PFB is accepted and transaction data is returned

### Actual result

Unable to submit PFB to the endpoint, as it errors

### Relevant log output

```
unsupported namespace id length: id [...] must be 28 bytes but it was 29 bytes
```

https://github.com/celestiaorg/go-cnc/actions/runs/5136913174/jobs/9244284199?pr=55#step:5:80

### Notes

cc @rootulp

**Comment by Wondertan** [comment]
@tuxcanfly, JFYI, it's a gateway issue, not rpc

**Comment by Wondertan** [comment]
However, this does not seem to be an actual problem on celestia-node side:
* I double-checked the code, and we don't set any restrictions on the size
* The linked failed test is in go-cnc, not the node.

Considering these two facts, I am closing the issue.

**Comment by rootulp** [comment]
I think the celestia-node Gateway API is broken b/c https://github.com/celestiaorg/docs/issues/781#issuecomment-1572568518 so will wait until that is resolved.

Also related https://github.com/celestiaorg/celestia-node/issues/2300 and https://github.com/celestiaorg/celestia-node/issues/2301

**Comment by Wondertan** [comment]
@rootulp, Josh meant RPC is broken, not the gateway

**Comment by rootulp** [comment]
Fixed comment above.
