### ISSUE TITLE
shares: Implement the `SharesService`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#23]
Implement `SharesService` in package `shares`. 

Implement: 
- [x] type `Share`
- [x] Constructor function for `SharesService`

The `SharesService` contains the following methods / functionality: 
- [x] `Start`
- [x] `Stop`

For `ShareExchange`, a `light` node only requires the ability to request shares and perform sampling (random share requests across random peers), and store the shares they receive, while a `full` node should be able to serve those share requests as well as perform requests.

`ShareStore` only applies to `light` nodes as `full` nodes store full blocks, so if the node is a `full` node, `ShareStore` should be disabled.

---
```go
type Service interface {
	GetShare(ctx context.Context, dah header.DataAvailabilityHeader, row, col int) (Share, error)
	GetShares(context.Context, DataAvailabilityHeader) ([]Shares, error)
	GetSharesByNamespace(context.Context, DataAvailabilityHeader, namespace.ID) ([]Shares, error)
	
	Start(context.Context) error
	Stop(context.Context) error
}
```

- [x] GetSharesByNamespace depend on https://github.com/celestiaorg/celestia-node/issues/5

**Comment by renaynay** [comment]
Should there be a pruning mechanism / threshold for `light` nodes ShareStore? cc @Wondertan @liamsi

**Comment by liamsi** [comment]
I think full storage nodes certainly need pruning (not necessarily for devnet/testnet but for mainnet). 

Light nodes download even less shares. Hence, pruning for light nodes is even less of a priority. That said, if light nodes get subjectively re-initialized we might consider overwriting the existing header (and shares) store. So that way we would have implicit pruning: whenever the light node gets re-initialized it throws away old headers and corresponding shares.

**Comment by renaynay** [comment]
5 November 2021: 

TODO: 

- [ ] Integrate `GetSharesByNamespace` into `shares.Service` inside #170 
- [ ] Implement `GetShares` (ability to reconstruct whole square) -- this is already implemented somewhere, so mostly copy and paste, but better to refactor it a bit for networking, concurrency, and storage optimisations (but this can be left for post Devnet, just need to document it in an issue).

**Comment by Wondertan** [comment]
Reopen as there is still one simple todo left

**Comment by renaynay** [comment]
TODO: 
- [ ] `GetShares`

**Comment by Wondertan** [comment]
@renaynay, GetShares are required for Full Availability so start with this one
