### ISSUE TITLE
Ability to override namespace version

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2300]
## Context

https://github.com/celestiaorg/celestia-node/blob/d53efbd03851c487bd96ff0c88fb92c4d1ed89d1/api/gateway/state.go#L144-L148

## Problem

There is no way for a user to override the `NamespaceVersion` of their blob when using celestia-node's Gateway API endpoint for `submit_pfb`

## Proposal

Add an optional parameter for `NamespaceVersion`

**Comment by ramin** [comment]
no longer SubmitPFB in gateway
