### ISSUE TITLE
Rename `nID` to `namespace` where applicable

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2301]
## Context

https://github.com/celestiaorg/celestia-node/blob/c77f6db35fe57ccef4110d0c7815e53a24921948/share/get.go#L52

## Problem
In a few locations in this repo, `nID: namespace.ID` is used when I think a namespace is being passed (i.e. version + ID).

## Proposal

1. Rename `nID` to `namespace` or `ns` where applicable. 
2. Replace the usage of the NMT type [`namespace.ID`](https://github.com/celestiaorg/nmt/blob/5466a618180e5127dc2beef2e9641849953cc1c2/namespace/id.go#L8) with celestia-app type [Namespace](https://github.com/celestiaorg/celestia-app/blob/348f795d8635324db4cca0367b599b5edc5c2fdb/pkg/namespace/namespace.go#L8)

**Comment by Wondertan** [comment]
Re 2. We want to move on Namespace from the app once it becomes a single slice. IIRC, with aligned on that in sync. When and how can we do it? Node team can help there

**Comment by Wondertan** [comment]
> I don't think celestia-app can make this change in the short-term b/c it's breaking and we've already cut celestia-app v1.0.0-rcs. 

That's fair. The good thing is the change is not consensus-breaking, so we can still do it. Adding it to my list of things to take during share pkg extraction.

Meanwhile, cleaning up and defining the type in celestia-node makes total sense. Assigning this on me.

**Comment by Wondertan** [comment]
@rootulp, thinking about this more, the namespace in NMT should be called just the namespace then as well because NMT commits to the version as well thus, it operates over namespaces rather than IDs. I am not sure anymore it is worth renaming in celestia-node only without nmt
