### ISSUE TITLE
v0.10.3 has a broken PR added 

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#2311]
### Celestia Node version

0.10.3

### OS

n/a

### Steps to reproduce it

https://github.com/celestiaorg/celestia-node/pull/2277/files

Error: failed to resolve DNS record: lookup https://rpc-blockspacerace.pops.one/: no such host

### Expected result

expected it should work with domains too

### Actual result

n/a

**Comment by walldiss** [comment]
Thank you for this one! I've create a fix, that will allow to use url with schema. For now, please use only host part:
```
--core.ip rpc-blockspacerace.pops.one
