### ISSUE TITLE
`make: *** [lint-imports] Error 1`

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2324]
## Context

I'm trying to verify the contents of a branch locally before publishing a PR. I'm hitting an error on `make lint` that I think is caused b/c I don't have a tool installed locally.

## Problem

```
$ make lint
--> Running imports linter
/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/rpc_test.go
make: *** [lint-imports] Error 1
$ make lint-imports
--> Running imports linter
/Users/rootulp/git/rootulp/celestia/celestia-node/cmd/celestia/rpc_test.go
make: *** [lint-imports] Error 1
```

## Proposal

Add a step to CONTRIBUTING.md to install https://github.com/incu6us/goimports-reviser#with-go or https://github.com/incu6us/goimports-reviser#with-brew

**Comment by rootulp** [comment]
`goimports-reviser` appears installed per 

```
$ goimports-reviser --help
Usage of goimports-reviser:
  -apply-to-generated-files
...
```

but I'm still observing this error.

**Comment by Wondertan** [comment]
Thank you @rootulp!

**Comment by ramin** [comment]
we've removed this from `make lint` for better or worse, though it remains in Makefile
