### ISSUE TITLE
schema not working as intended in 0.10.4

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#2333]
### Celestia Node version

0.10.4

### OS

ubuntu 20.04

### Steps to reproduce it

so it seems some forms of --core.ip flag dont work, like  `localhost` and for some `http://localhost` and `http://localhost:26657/` and adding 127.0.0.1 seems to work

while the last 2 work for some, i would think it has to do with their hosts file, eg if they have:
 /etc/hosts  127.0.0.1 localhost

### Expected result

the --core.ip flag should work with just localhost, or with http/https normally

### Actual result

Error: failed to resolve DNS record: lookup : no such host

and 

Error: invalid IP address or hostname given: ::1

**Comment by Wondertan** [comment]
Supposed to be fixed by https://github.com/celestiaorg/celestia-node/pull/2332

**Comment by mindstyle85** [comment]
yeah unfortunately it isnt, if you check the BSR validator channel you will see

**Comment by Wondertan** [comment]
@mindstyle85, why do you think the linked PR won't fix it? Have you tried it?

**Comment by mindstyle85** [comment]
@Wondertan oh i didnt, i assumed that PR was merged into 0.10.4 hehe
