### ISSUE TITLE
blob: NewBlobV0 constructor

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2346]
There is no point for users to import constants when we can have a constant constructor. We can add constructors for each versions and assume the highest number is always a default

**Comment by distractedm1nd** [comment]
Does this refer to v0 share or v0 namespace, or both? Like, what kind of namespace is expected here? Will it just be a []byte that is parsed using the future #2345 ?

**Comment by Wondertan** [comment]
It's for share versions. The constructor would take namespace which would have its own versioning.

**Comment by Wondertan** [comment]
This is actually implemented
