### ISSUE TITLE
gateway: set CORS headers for browser support

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2363]
@smuu was recently hacking on celestia-node and wasn't able to use any of our APIs in the browser because of CORS issues. We should add CORS headers on both gateway and RPC and allow all the origins

**Comment by Wondertan** [comment]
Ideally, the port the RPC server listens on should not be exposed to WAN. It can be shared in LAN or within datacenter clusters. Even if there is a rare usecase for remote usage, it's better to filtering on IP firewall level, rather than polluting config with HTTP headers for gateway.

**Comment by renaynay** [comment]
https://github.com/celestiaorg/celestia-node/pull/2373
