### ISSUE TITLE
Update docs to explain what the gateway and RPC APIs are for / what the difference is

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#2369]
https://docs.celestia.org/category/node-api/

**Comment by Wondertan** [comment]
Closing in favour of https://github.com/celestiaorg/docs/issues/810

**Comment by musalbas** [comment]
OK, but as a reminder, engineering teams should be responsible for docs about their product, so can someone from the node team be assigned to that issue please?
