### ISSUE TITLE
cli: rpc should be able to get token automatically if node is running with the same user

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2372]
When the admin auth token is generated at the start, we can store it in the Keystore, which CLI can access for read-only purposes and get the token to us.

**Comment by distractedm1nd** [comment]
Having trouble understanding this. Do you mean specifically for the RPC cli?

**Comment by renaynay** [comment]
He means that using an rpc cli on the same machine as the running machine should just access already-signed admin token inside keystore of node

**Comment by renaynay** [comment]
Like on start - node generates admin auth token and stores it in keystore

RPC cli can look there if env var is not set.

**Comment by jcstein** [comment]
would it be possible to also add a flag that disables auth on same machine? i.e. `--disable.auth` cc @itsdevbear

**Comment by jcstein** [comment]
from @Wondertan 
"/keys/NJ3XILLTMVRXEZLUFZVHO5A is where the auth token is stored
The file is json formatted and contains body field which is the key"

however, it will need more formatting to get the usable string

**Comment by Wondertan** [comment]
> would it be possible to also add a flag that disables auth on same machine? i.e. --disable.auth

Disabling auth means disabling it everywhere. We could hack our way to see if the request is coming from `loop/localhost` interface but it's a bit more complicated to implement and it makes it work for the whole machine rather than the same user, which is a better approach.

**Comment by Wondertan** [comment]
> "/keys/NJ3XILLTMVRXEZLUFZVHO5A is where the auth token is stored
The file is json formatted and contains body field which is the key"

> however, it will need more formatting to get the usable string

This is when you want to access the file yourself to get the token, but ideally, we would solve with the proposed solution which would do all the formatting automatically.

**Comment by jcstein** [comment]
awesome, thank you for the context!

**Comment by Wondertan** [comment]
Mind to make a new issue?

**Comment by jcstein** [comment]
https://github.com/celestiaorg/celestia-node/issues/2526 🫡

**Comment by Wondertan** [comment]
Local dev net should be able to access the key through the CLI

**Comment by nashqueue** [comment]
We need the auth token outside of local-celestia-devnet, which is inside a docker. Can you explain what you mean by accessing the auth token through the CLI? @Wondertan
