### ISSUE TITLE
fix(share/eds/store): optimize `Put`

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2390]
The `Put` operation takes too much time and grows too quickly with increasing block sizes. This creates both a concern for newly produced blocks entering our network as well as historical block sync. There are a lot of low hanging fruit to optimize, the biggest being indexing from memory.

1. Indexing is currently done reading the CAR from disk, directly after writing it
    - There is an opportunity here to create a new mount that lets you pass a byte array that contains the CAR file, so that it doesn't need to be read from disk for the `Initializing` state (indexing)
2. Inverted index could use a faster, non-LSM backend
3. writeProofs and writeQuadrants themselves could be optimized

**Comment by musalbas** [comment]
>grows too quickly with increasing block sizes

The source of that issue may be this line: https://github.com/celestiaorg/celestia-node/blob/44786bb2e6d6c98f853d185413cbb66567fa5aba/share/eds/inverted_index.go#L45

`Has` takes a lot longer on a live network with blocks:

![image](https://github.com/celestiaorg/celestia-node/assets/5038597/603c8edc-8eec-4221-8fed-182a74a19b53)

...compared to isolated tests not on a live network where Badger is not even used:

![image](https://github.com/celestiaorg/celestia-node/assets/5038597/c5c8ff65-433b-4da0-9304-b32c25626c5c)
