### ISSUE TITLE
[Feature Request]: Improve Dockerfile build process and add custom tagging option in Celestia's reusable docker pipeline

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2412]
### Implementation ideas

_Disclaimer: this issue is a WIP and may need editing_

This is a feature request to publish arm64/darwin, amd64/darwin, arm64/linux docker images.

We currently do not publish arm64-compatible docker images for arm64/linux, arm64/darwin, or amd64/darwin. These some of the most common versions that our users use. 

@jbowen93 reported that:
his team at @astriaorg needed to update [the docker images](https://github.com/astriaorg/celestia-node/pkgs/container/celestia-node/105364936?tag=v0.11.0-rc5) they maintain because Celestia’s images 
- don’t support arm64
- are “scratch” images with just the go binary so we can’t shell in and use debug tooling

Regarding the inability to shell in, I have faced this issue before when working with @tuxcanfly on debugging the CelOPstia setup.

**Comment by jcstein** [comment]
cc @jbowen93 for clarification on the flavor of arm you're looking for?

**Comment by jbowen93** [comment]
I don't think this is actually an issue. Adding some feedback from our team. 

> But the issue basically is this: [ghcr.io](http://ghcr.io/) expects images to be in OCI format, which docker doesn't completely abide by. Setting provenance: false fixes it by telling docker to hide some metadata that cause ghcr to display unknown/unknown

> Ok, this might not be 100% correct according to this: https://github.com/docker/build-push-action/issues/820#issuecomment-1486849546

> It only builds arm images for semver tag pushes. I haven't gotten it all working e2e yet with the new images, but the arm image for Celestia node should be okay

cc: @superfluffy @steezeburger

**Comment by SuperFluffy** [comment]
@jcstein `arm64/linux` is the only one needed I think; `arm64/darwin` is probably not necessary since most people on macOS probably just run some flavor of virtualized linux as part of their docker/podman/kind/k8s/minikube/rancher zoo.

Especially when running tests with random genesis hashes it's nice to have a test/demo/smth else docker image that contains `curl` and `jq` so that `celestia-app` can be queried and the hash extracted as part of setting up `celestia-node`

**Comment by jcstein** [comment]
thanks @jbowen93, I think the unknown/unknown is from celestia upstream as well, it is on these images too https://github.com/celestiaorg/celestia-node/pkgs/container/celestia-node/105006714?tag=v0.11.0-rc5

and thank you @SuperFluffy - should i change this issue to be specific to issues with being able to shell in the image?

**Comment by steezeburger** [comment]
I think a succinct list that describes ideal fixes and features is as follows:
* fix celestia-app and celestia-node `Dockerfile`s to get rid of `unknown/unknown` images 
* always build arm and amd in https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml
* add `jq` and `curl` to images
  * alternatively, i think we can continue creating a custom image from your image, adding jq and curl, but it would be nice to have the ability to add a custom tag prefix when using the reusable docker pipeline. Right now only a semver pattern is supported. This would let us have images like `celestia-node:test-v1.0.0-rc5` or similar.

**Comment by jcstein** [comment]
cc @celestiaorg/celestia-node & @celestiaorg/devops

**Comment by Bidon15** [comment]
Thanks for flagging this! 
We are planning to get this done in beginning of Q3.
