### ISSUE TITLE
Can't submit PFBs with ledger 

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#2415]
### Celestia Node version

4d986940d662649eba4b0d3daa85268318204ff2

### OS

macosx

### Install tools

via makefile

### Steps to reproduce it

add a key from ledger (after manually compiling with ledger flag #2413) and then:
`celestia rpc blob Submit 0x42690c204d39600fddd3 '"gm"'` (from 
yields:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "Unexpected characters"
  }
}
```
and sometimes
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "ledger nano S: hidapi: unknown failure"
  }
}
```

### Expected result

it just works 

### Actual result

it doesn't

**Comment by renaynay** [comment]
Closing as duplicate of #2416 

All one issue: integrate ledger support
