### ISSUE TITLE
libs: Add expiry for JWT

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2420]
Add expiration to JWT generation

**Comment by Wondertan** [comment]
Besides, we should keep support for indefinite tokens

**Comment by cristaloleg** [comment]
Do we want a fixed TTL for the token? or better to give a config param which configures this?

> Besides, we should keep support for indefinite tokens
In other words - token with no TTL is still a correct token (assuming signature is correct).
