### ISSUE TITLE
Inconsistency in casing in node RPC responses

### ISSUE THREAD

**Issue by zvolin** [celestiaorg/celestia-node#2423]
### Celestia Node version

6654cdf

### OS

Archlinux 6.3.6-zen

### Install tools

docker

### Steps to reproduce it

Based mostly on the API documentation: https://node-rpc-docs.celestia.org/#p2p
Most of the API responses use snake_case fields naming convention, however whole P2P module, SyncState response and GetSharesByNamespace response use PascalCase naming.

### Expected result

Uniform naming conventions for all the API surface

### Actual result

Some methods use PascalCase naming of fields

### Relevant log output

```Shell
Example GetSharesByNamespace response:

[{
    "Shares":[
        "AAAAAAAAAAAAAAAAAAAAAAAAAE3BWIMKXpgB8QMBAAAEAP////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////8="
    ],
    "Proof":{}
}]
```

**Comment by vgonkivs** [comment]
Hello @zvolin. Thanks for creating an issue.

**Comment by ramin** [comment]
spoken with @vgonkivs and verified that a lot of the casing here was cleaned up a long while ago and probably before launch. 

The only cases where we are not doing "snake_case" and letting the raw Struct fields be serialized are in the P2P module where we are exposing libp2p types directly, namely [metrics.Stats](https://github.com/libp2p/go-libp2p/blob/master/core/metrics/reporter.go#L13) and [peer.AddrInfo](https://github.com/libp2p/go-libp2p/blob/master/core/peer/addrinfo.go#L11) which we agree it is livable with to allow living with considering we'd expect a consumer on end of JSON-RPC to likely use these types and not want us to mask or embed them into types we own for serialization

given that, we can mark this done if all in agreement
