### ISSUE TITLE
[Feature Request]: Unify the representation of jsonProof and pb.Proof

### ISSUE THREAD

**Issue by zvolin** [celestiaorg/celestia-node#2427]
### Implementation ideas

Hi,
I think it'd be nice if the `jsonProof` and `pb.Proof` had the same representations. My use case is that I'm generating most of the celestia types from protobuf definitions and that would allow me to re-use the pb-generated proof type in node rpc api calls without translating between types.

Currently those two look like so
[jsonProof](https://github.com/celestiaorg/nmt/blob/master/proof.go#L51)
```go
type jsonProof struct {
	Start                   int      `json:"start"`
	End                     int      `json:"end"`
	Nodes                   [][]byte `json:"nodes"`
	LeafHash                []byte   `json:"leaf_hash"`
	IsMaxNamespaceIDIgnored bool     `json:"is_max_namespace_id_ignored"`
}
```

[pb.Proof](https://github.com/celestiaorg/celestia-node/blob/main/share/p2p/shrexnd/pb/share.proto#L28)
```protobuf
message Proof {
  int64 start = 1;
  int64 end = 2;
  repeated bytes nodes = 3;
  bytes hashleaf = 4;
}
```

Eg the protobuf definition could be changed like so to allow for seamless transitions:
```protobuf
message Proof {
  int64 start = 1;
  int64 end = 2;
  repeated bytes nodes = 3;
  bytes leaf_hash = 4;
  bool is_max_namespace_id_ignored = 5;
}
```

I know this would be a breaking change tho, so curious to hear your opinion

**Comment by zvolin** [comment]
Also it looks like in[ `eds/byzanine`](https://github.com/celestiaorg/celestia-node/blob/main/share/eds/byzantine/pb/share.proto) the proof has `leaf_hash` field, not `hashleaf`.
Could there be just one proto definition for proof?

**Comment by vgonkivs** [comment]
Hello @zvolin. Thanks for creating an issue. Yes, I think it makes sense to keep them consistent. Will extend protocol struct with one more field

**Comment by Wondertan** [comment]
I am also thinking about removing is-max-namespace-ignore field in JSON instead. This is a system wide param, rather than per proof, so we can simplify things by removing it. 

@vgonkivs, also consider unifying the BEFP proof proto definition if possible

**Comment by vgonkivs** [comment]
@Wondertan it's just 1 byte and I don't think it will take much place. Also, please not that json representation is from nmt repo. Anyway, I've created an issue in the nmt and proposing to move all photo-proof code there - closer to the implementation.
https://github.com/celestiaorg/nmt/issues/219

**Comment by zvolin** [comment]
> it's just 1 byte

iirc bools are encoded as 4 bytes on wire

**Comment by vgonkivs** [comment]
Yes, they Are encoded as i32 but protobuf also uses a form of variable-length encoding called "variant" encoding. That means that smaller values can be encoded using fewer bytes. So, it's possible that `true`/`false`  can be represented in a single byte.

**Comment by zvolin** [comment]
@Wondertan I don't think that the recently linked pull request resolves the problem mentioned. It is only related in a sense that it fixes the json representation of something, but it doesn't touch the `Proof` at all.

Ideally, I'd like to have it completed once
- there is a single protobuf definition for `Proof` (currently I've noticed at least 2, which have different field namings, from `share/p2p` and `share/eds`)
- their json `Proof` representation is consistent with the  `Proof` from the `nmt` module (or at least they have the same field names)

I'm happy to discuss those, but please reopen as this PR wasn't really related

**Comment by zvolin** [comment]
I think the problem there is that in the linked commit there is a message:

> Partly fixes https://github.com/celestiaorg/celestia-node/issues/2427

Github only cares about the part `fixes https://github.com/celestiaorg/celestia-node/issues/2427`. If you want to link a PR to the issue, just use `mention` instead of `fixes` as this is a keyword in github's understanding

**Comment by Wondertan** [comment]
Thanks for noting @zvolin. This issue is definitely not resolved. It was closed due to the “fixes” keyword in https://github.com/celestiaorg/go-header/pull/82.

**Comment by vgonkivs** [comment]
ooooops, yes, my fault. Sorry. 
Regarding the current issue: I've created an issue in the nmt repo, so we can have a single representation of the pb.Proof and in case nmt.Proof will be modified, json/pb representations will be also modified.

**Comment by vgonkivs** [comment]
Hello @zvolin, we moved a pb definition of proof to the nmt library. You can find it [here](https://github.com/celestiaorg/nmt/blob/master/pb/proof.proto). The last thing is to rename  `IsMaxNamespaceIDIgnored` to `IsMaxNamespaceIgnored` which I believe will be done in the scope of https://github.com/celestiaorg/nmt/issues/206
