### ISSUE TITLE
Create Github Action to trigger on PR merge to celestia-node `main` branch

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/celestia-node#243]
Create a [Github Action](https://docs.github.com/en/actions) that is triggered when a PR is merged to the [celestia-node](https://github.com/celestiaorg/celestia-node) `main` branch.

This can initially just be a placeholder action.

**Comment by adlerjohn** [comment]
@jbowen93 is this still needed?

**Comment by ramin** [comment]
our GitHub actions have astral traveled through many galaxies, to where i'd safely say "this is done"
