### ISSUE TITLE
Support SSL for connecting to consensus node API with --core.ip

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#2439]

**Comment by JB273** [comment]
What we know works already:
For celestia-appd version 0.11.1 (mocha):
`celestia-appd query bank balances celestia1g486scr5t24jywkql8ld2uuw6clws2fckclhlj --node https://rpc-mocha.pops.one:443`

**Comment by JB273** [comment]
It looks like the node client expects to be able to connect to both RPC and gRPC on the same hostname.
To add SSL with a proxy many are now using different hostnames and forward to the correct port, eg:

- `https://rpc-mocha.pops.one:443` forwards to local port 26657
- `https://grpc-mocha.pops.one` forwards to local port 9090

Currently we can only give one hostname through the `--core-ip` flag, this looks like to be a part of the issue

**Comment by malise800** [comment]
From I could figure, I think the celestia-node CoreAccessor client doesn't support SSL. 

https://github.com/celestiaorg/celestia-node/blob/main/state/core_access.go#L85-L112

**Comment by malise800** [comment]
now it also seems the RPC node provider will need to update their infrastructure to also support proxied grpc connection : https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-3-publishing-grpc-services/

**Comment by ramin** [comment]
closing in favor of https://github.com/celestiaorg/celestia-node/issues/2931
