### ISSUE TITLE
Bridge nodes are constantly rebooting after block height 24k+ in robusta-64

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#2459]
### Celestia Node version

v0.11.0-rc6

### OS

k8s/docker/alpine

### Others

In metrics since 21:10 11/07/2023 at height 24k -> we see that nodes starts to suddenly reboot themselves

<img width="1445" alt="Screenshot 2023-07-12 at 08 43 44" src="https://github.com/celestiaorg/celestia-node/assets/1822365/7ae09c80-bf6b-4521-adac-31a6ba41a046">

### Steps to reproduce it

Start syncing a bridge node from genesis

### Expected result

No reboots -> bridge nodes reach the tip of the chain

### Actual result

Reboots starts with such such logs

- `node failed to start`
- `2023-07-12T06:40:39.945107038Z stderr F 2023-07-12T06:40:39.940Z	WARN	shrex-sub	shrexsub/pubsub.go:83	unregistering topic	{"err": "no validator for topic robusta-64/eds-sub/v0.1.0"}`
- `2023-07-11T19:26:27.51014414Z stderr F 2023-07-11T19:26:27.509Z	WARN	dagstore	dagstore@v0.0.0-20230413141458-735ab09a15d6/dagstore.go:572	failed to recover state of shard : unexpected end of JSON input; skipping`
- `2023-07-11T21:35:43.547463363Z stderr F 2023-07-11T21:35:43.530Z	ERROR	core	core/listener.go:128	listener: handling new block msg	{"height": 37696, "hash": "9B5D7F772F7B513E4F3608CB74C3EB1699709ACEC0892D841E0D640E5725B16E", "err": "storing EDS: context canceled"}`

### Relevant log output

```Shell
look for grafana dashboards
```

### Notes

There were no reboots before 21:10 11/06/2023 for all 4 bridge nodes

**Comment by ramin** [comment]
@Bidon15 @walldiss is this still an issue?

**Comment by Bidon15** [comment]
it's fixed IIRC @walldiss 

> @Bidon15 @walldiss is this still an issue?

**Comment by Wondertan** [comment]
It's fixed
