### ISSUE TITLE
automated CHANGELOG.md check for celestia-node

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/celestia-node#246]
There should be an automated step that ensures that a CHANGELOG.md file is appropriately updated for all merges to the `main` branch.

There should be a proper description in an issue and corresponding PR as well as a summary in the CHANGELOG.md file. This will be enforced through an automated action. In rare cases for small PRs it may be acceptable to skip this.

**Comment by liamsi** [comment]
Thanks for this @jbowen93! This implies that there needs to be a proper description in an issue/directly in a PR and then a summary in the Changelog too. We sometimes had PRs in this repo with very little context in issues (or sometimes in the PR). Some PRs are just empty or simply described with "description will follow later". This might be OK in very rare exceptional cases but larger PRs without a proper description upfront (and a chance for a brief discussion) are not OK in general.
