### ISSUE TITLE
feat(share/p2p/discovery): Warning for discovery loop if haven't found wanted peers in 5 minutes 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2474]
We need a mechanism to check if wanted amount of peers has not been discovered in 5 minute periods so that users are warned of degraded full node connectivity via a WARN log - something like:

log.Warn("potentially degraded connectivity, unable to discover desired amount of full node peers in 5 minutes")

This would ideally exist in the discovery loop inside discovery.go.

**Comment by nodersteam** [comment]
@renaynay 

Hello! Can we take this issue to work?

**Comment by nodersteam** [comment]
![image](https://github.com/celestiaorg/celestia-node/assets/94483941/3e5ac5e0-29a2-48e5-bc1a-4b40bded96c5)
