### ISSUE TITLE
ipld/bitswap: Prepend block height to CIDs to eliminate Badger inverted index

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#2479]
If we can prepend the block height to CIDs, when requesting chunks over Bitswap, we can eliminate the Badger inverted index for CID => CAR file.

This is a simpler version of what's proposed in https://github.com/celestiaorg/celestia-node/issues/2116, as it doesn't involve adding the coordinates of shares to CIDs - just the block height.

**Comment by ramin** [comment]
resolved by shwap
