### ISSUE TITLE
cmd/celestia: Describe the params in rpc CLI help output

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2493]
## Context

I'm trying to verify a PR but the help docs for an rpc method on the CLI doesn't tell me what are the params for `state Transfer`. E.g.

```
$ celestia rpc state Transfer --help
Send JSON-RPC request

Usage:
  celestia rpc [namespace] [method] [params...] [flags]

Flags:
      --auth string     Authorization token (if not provided, the CELESTIA_NODE_AUTH_TOKEN environment variable will be used)
  -h, --help            help for rpc
      --print-request   Print JSON-RPC request along with the response
      --url string      Request URL (default "http://localhost:26658")
```

## Proposal

It would be nice if the output described the params that are expected for the `state` namespace and the `Transfer` method

**Comment by ramin** [comment]
docs and cli --help output were improved and i think satisfy this as of v0.12
