### ISSUE TITLE
Update gas estimation to correspond with app

### ISSUE THREAD

**Issue by nashqueue** [celestiaorg/celestia-node#2496]
### Implementation ideas

After https://github.com/celestiaorg/celestia-app/pull/2116, celsetia-node should update the gas estimation to be more precise. 

cc @vgonkivs

**Comment by vgonkivs** [comment]
@cmwaters can you please make EstimateGas public? So Celestia-Node will not copy paste it but invoke from app directly.

**Comment by cmwaters** [comment]
Sure. I'm just going to do a bit more modelling of gas calculations and then I should be good
