### ISSUE TITLE
state: More user-friendly error message when calling state-related endpoints with an address that has no balance

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2499]
### Celestia Node version

v0.11.0-rc8

### OS

MacOS

### Install tools

`make go install` from the celestia-node repo

### Steps to reproduce it

```
$ celestia rpc state Transfer $ADDRESS 100000 8000 80000
```

### Expected result

I expected an error message that conveys the address associated with my Celestia light node has a balance of `0` so it can't send `100000` tokens

### Actual result

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "rpc error: code = NotFound desc = account celestia16fcv0z6yvwh3ym5l4stduvp637echmmrvgju62 not found"
  }
}
```

### Relevant log output

```Shell
After transferring tokens to the address associated with my Celestia light node, I was able to bypass this error
```

### Notes

Additional context in https://github.com/celestiaorg/docs/pull/907

**Comment by renaynay** [comment]
@rootulp this is an error coming from SDK - address is "not found" bc technically it does not exist anywhere yet.

We could wrap this error message and make it more legible though.

**Comment by rootulp** [comment]
+1 to making the error message more legible.

**Comment by ramin** [comment]
this was done
