### ISSUE TITLE
bug:  illegal base64 data at input byte during unmarshalling blob.Commitment

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#2500]
Blob Module requests fail sometimes with `illegal base64 data at input byte` error through rpc.

**Comment by renaynay** [comment]
Can you reproduce this @vgonkivs ?

**Comment by vgonkivs** [comment]
Haven't tried it yet, but I'm pretty sure that it will.

**Comment by vgonkivs** [comment]
fixed in #2515 and #2521
