### ISSUE TITLE
blob.GetAll not returning correct base64 data, GetShare and GetSharesByNamespace also don't work

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2503]
### Celestia Node version

v0.11.0-rc8

### OS

mac

### Install tools

docs

### Others

nope

### Steps to reproduce it

Q: if i post plain-text data `'"gm"'` and retrieve it, the response is in base64, correct?
i’m updating the based64.xyz tutorial, and during testing I used `'"gm"'` as a check, the base64 share that i retrieve is: `SW1kdElnPT0=` which converts from base64 to text: `ImdtIg==`, not `gm` (plus some metadata bytes). i’m on arabica-9 v0.11.0-rc8
i previously had `celestia rpc share GetSharesByNamespace "$(celestia rpc header GetByHeight $HEIGHT | jq '.result.dah' -r)" GHTmQvXd5Yk=` but now am using `celestia rpc blob GetAll $HEIGHT 0x42690c204d39600fddd3`

the commands that previously worked, also do not work anymore as expected, detailed in this issue: 
https://github.com/celestiaorg/docs/issues/914

updated tutorial is at https://based64.xyz/

i also went through the [node tutorial](https://docs.celestia.org/developers/node-tutorial/) page, and the examples on retrieval work with CLI when submitting hex.

### Expected result

returns blob in base64 which can be converted to base64 to text. this is how it worked originally and there seems to be a bug on the serialization or deserialization in rpc.go (based on what Hlib and I were looking at yesterday)

### Actual result

returns data in wrong format

### Relevant log output

```Shell
celestia rpc share GetSharesByNamespace "$(celestia rpc header GetByHeight 103692 | jq '.result.dah' -r)" 0x42690c204d39600fddd3
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32700,
    "message": "unmarshaling params for 'share.GetSharesByNamespace' (param: *share.Namespace): illegal base64 data at input byte 20"
  }
}

celestia rpc share GetShare "$(celestia rpc header GetByHeight 101810 | jq '.result.dah' -r)" 101810 0
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 0,
    "message": "fatal error calling 'share.GetShare': panic in rpc method 'share.GetShare': runtime error: index out of range [101810] with length 8"
  }
}
```

### Notes

I know for a fact that I submitted data to the namespace and at the block heights above.

the methods themselves did not change. i am using the correct length of namespace.

![image](https://github.com/celestiaorg/celestia-node/assets/46639943/3703f5e9-12a0-4883-bd1b-434d2f4b41b6)
![image](https://github.com/celestiaorg/celestia-node/assets/46639943/70b57cab-f987-4a4a-a049-9ea3863c8816)
![image](https://github.com/celestiaorg/celestia-node/assets/46639943/9b77715f-df01-4fe5-90d1-13c5bc1a9717)

**Comment by jcstein** [comment]
# only steps you need to repro:
1. run arabica light node on v0.11.0-rc8: `celestia light start --core.ip consensus-full-arabica-9.celestia-arabica.com --p2p.network arabica`
2. `export CELESTIA_NODE_AUTH_TOKEN=$(celestia light auth admin --p2p.network arabica)`
3. `celestia rpc blob Submit 0x42690c204d39600fddd3 '"gm"'`
4. `celestia rpc blob GetAll [blockheightfrom#3] 0x42690c204d39600fddd3`
5. convert the data to hex here: https://base64.guru/converter/decode/text

**Comment by renaynay** [comment]
Duplicate to #2500

**Comment by jcstein** [comment]
ok now context is linked :)

**Comment by jcstein** [comment]
other issue doesn't seem to address the issues with the response from the RPC, though, so reopening

**Comment by jcstein** [comment]
> Input params are incorrect here:
celestia rpc share GetShare "$(celestia rpc header GetByHeight 101810 | jq '.result.dah' -r)" 101810 0
In the second param instead of header.Height(101810) you should pass a row index.
>

what is the correct format?

**Comment by vgonkivs** [comment]
celestia rpc share GetShare "$(celestia rpc header GetByHeight 101810 | jq '.result.dah' -r)"  'rowIndex' 'colIndex'``

**Comment by jcstein** [comment]
and as an example what do i use for `rowIndex` and `colIndex`?

**Comment by jcstein** [comment]
so what namespace is this for?

```bash
celestia rpc share GetShare "$(celestia rpc header GetByHeight 101810 | jq '.result.dah' -r)"  0 0
{
  "jsonrpc": "2.0",
  "result": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBAAACuAAAACbcAgrQAgqgAQqdAQogL2NlbGVzdGlhLmJsb2IudjEuTXNnUGF5Rm9yQmxvYnMSeQovY2VsZXN0aWExNXJkZHB3amY1M3Fsa21xcnkzbmE5Y2FzY3dsYzl4Z3J2czRraDcSHQAAAAAAAAAAAAAAAAAAAAAAAAA+6F39tPkv7BI9GgKLDCIgAW7uZlBgQDnTc8czrN6voDfKphfmVcZLebBsjzEVpoRCAQASaQpRCkYKHy9jb3Ntb3MuY3J5cHRvLnNlY3AyNTZrMS5QdWJLZXkSIwohA9QZjbTNT9DKL9qkJKO/SBiv4uqoulCE8pngYUyJRQ1jEgQKAggBGNN1EhQKDgoEdXRpYRIGMjAwMDAwEICJehpAEdmeKwe6M1bi+Yzj/2wpsfUjA2d7BOxnGsJTpFZzEW0RzhBRa52BD54LsV4xk3zwGE0QormkbQIvO5k9KFD8qxIBAhoESU5EWNgCCswCCp8BCpwBCiAvY2VsZXN0aWEuYmxvYi52MS5Nc2dQYXlGb3JCbG9icxJ4Ci9jZWxlc3RpYTF5aDM2OTh4MzJwYTVtN2NxM2U2azg3bTQ0NWZjOG1wdWU4bWU2dhIdAAAAAAAAAAAAAAAAAAAAAAAAAEJpDCBNOWA=",
  "id": 1
}
```

**Comment by vgonkivs** [comment]
This request is not about the namespace, it fetches the share at a particular position(I actually do not understand why do we need it to be exposed via rpc).
