### ISSUE TITLE
share: slow GetSharesByNamespace

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#2539]
I'm not sure if it's a bug or not but during my cmd tests of the Blob Module, I'm observing that sometimes it takes much more time for the `shareGetter` to return shares. On average, it takes 0.15-0.5 seconds to handle a request and return constructed blob back, but sometimes it takes around 1 minute. After adding extra logs I've figured out that it is stuck on the GetSharesByNamespace step.

NOTE: _these are extra logs that do not present in our code._
```
2023-08-04T15:29:40.781+0300	INFO	blob	blob/service.go:193	fetching shares -> before request
2023-08-04T15:30:40.828+0300	INFO	blob	blob/service.go:201	parsing shares -> right after the receiving a response
```

сс @walldiss

**Comment by musalbas** [comment]
Could it be related to Badger compaction issue? Perhaps worth testing with the new store improvements

**Comment by renaynay** [comment]
Closing as no actionable from the issue - already part of workstreams we're currently working on
