### ISSUE TITLE
feat(cmd): add flag that allows to read blob's data from file 

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#2552]
It would be nice to have a flag in submitCmd that will allow to get blob's(or multiple blobs) data from the file instead of cli

**Comment by sontrinh16** [comment]
hey @vgonkivs i'm working on a logic for this, may i ask is there a standard procudure for testing this type of command locally. Something like on Celestia-app repo there is a note on how to test the command so i was wandering if there is one here ?

**Comment by sontrinh16** [comment]
hi @vgonkivs, can i work on this ? I think i have a functioning version for this feature

**Comment by vgonkivs** [comment]
Hey @sontrinh16. Yes, sure. Thank you!
