### ISSUE TITLE
header: Do not panic on data root mismatch on unmarshal

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2555]
As the fields are public, if a full node or light node is sent an ExtendedHeader with mismatched Row/Col roots that don't compute to the DataRoot, the node will panic.

We should do a severe WARN log and ban the peer instead.

**Comment by Wondertan** [comment]
Supposed to be fixed by https://github.com/celestiaorg/celestia-node/pull/2220

**Comment by renaynay** [comment]
@Wondertan I'm working on a fix right now that implements a custom error - bridge nodes **should** panic as they receive blocks from a "trusted" source. 

Change is almost the same as yours, would you be ok rebasing on it?

**Comment by Wondertan** [comment]
I don't mind rebasing, if you want to move the panic from Validate to CoreListener

**Comment by renaynay** [comment]
Yes pls :)

**Comment by renaynay** [comment]
https://github.com/celestiaorg/celestia-node/pull/2558/files
