### ISSUE TITLE
Account for secondary reserved namespace range

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#2561]
## Context

celestia-app is considering making a breaking change to reserve the last 256 namespaces (see https://github.com/celestiaorg/celestia-app/issues/2253). Relevant PR https://github.com/celestiaorg/celestia-app/pull/2257

## Problem

If https://github.com/celestiaorg/celestia-app/pull/2257 merges, we need to update celestia-node's namespace to account for the change. 

## Proposal

1. Rename [`MaxReservedNamespace`](https://github.com/celestiaorg/celestia-node/blob/87e9500120c27450e264ab4ffd59c87e92186194/share/namespace.go#L17C2-L17C2) to `MaxPrimaryReservedNamespace`
1. Rename [`ReservedPaddingNamespace`](https://github.com/celestiaorg/celestia-node/blob/87e9500120c27450e264ab4ffd59c87e92186194/share/namespace.go#L20C8-L20C8) to `PrimaryReservedPaddingNamespace`
1. Add `MinSecondaryReservedNamespace` constant to [this list](https://github.com/celestiaorg/celestia-node/blob/87e9500120c27450e264ab4ffd59c87e92186194/share/namespace.go#L15-L24)
1. [`ValidateForBlob`](https://github.com/celestiaorg/celestia-node/blob/87e9500120c27450e264ab4ffd59c87e92186194/share/namespace.go#L122-L131) should account for the secondary reserved namespace range.
1. Add unit tests

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/issues/2257#issuecomment-1675981337_

**Comment by Wondertan** [comment]
@renaynay, just needs https://github.com/celestiaorg/celestia-node/pull/2597 to be merged
