### ISSUE TITLE
metrics(share/ipld): reduce amount of tracing spans for GetEDS

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#2568]
### Implementation ideas

GetEDS produces thousands of spans for single eds request. 5 spans per each block requested, so for ods 128 it could be 128*128 = 16384 amount of spans. It results in very high load on jaeger, that consumes a lot of resources. We don't need to track each individual block, so traces could be reduced.

<img width="1726" alt="image" src="https://github.com/celestiaorg/celestia-node/assets/13818348/582b81c5-9024-490c-9dbb-ceeb15da5d4a">

**Comment by Wondertan** [comment]
I think we should stop to enable all the traces at once and enable traces granularly for what we need exactly.

**Comment by ramin** [comment]
shwap deletes this
