### ISSUE TITLE
bug(share/teeGetter): context with proofAdder is leaked

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#2582]
### Implementation ideas

During robusta tests it was observed, that proofAdder sometimes leaked and not freeing up memory after GetEDS operation has exited. Since proofAdder is added to ctx as value, it means that some goroutine still holds reference to context after operation is over. Need to:

-  prevent proofAdder from being leaked
- investigate where the context is leaked

**Comment by distractedm1nd** [comment]
TeeGetter has been removed, but this could maybe still occur inside availability/full. Needs to be reinvestigated

**Comment by Wondertan** [comment]
Hasn't seen this in flame graphs

**Comment by walldiss** [comment]
Not observed anymore
