### ISSUE TITLE
cmd/celestia: Return proper error for RPC CLI when call is unauthorised

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2583]
### Current behaviour

Server-side: 
```
2023-08-18T13:44:40.778+0200	WARN	auth	auth/handler.go:39	JWT Verification failed (originating from [::1]:57655): jwt: signature is invalid
```

client-side: 
```
2023/08/18 13:44:40 Error parsing JSON-RPC response: unexpected end of JSON input
```

### Expected behaviour

client-side: 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "not enough permissions to access <method>; wanted <perm>, have <perm>"
  }
}
```

**Comment by maharsh312** [comment]
i'll like to work on this, can you assign it to me?

**Comment by Wondertan** [comment]
@maharsh312, sure thing!

**Comment by maharsh312** [comment]
@Wondertan do you guys have slack channel for discussions?

**Comment by Wondertan** [comment]
@maharsh31, we prefer GH for discussions

**Comment by rise2semi** [comment]
@renaynay @Wondertan 
I've tried to reproduce the scenario with a permission error (used `celestia rpc node Info`)
RPC responds with the following message:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": 1,
    "message": "missing permission to invoke 'Info' (need 'admin')"
  }
}
```

Should this issue be marked as fixed?
In case additional work is expected I can work on that.

**Comment by distractedm1nd** [comment]
@rise2semi You are right, thank you for checking!
