### ISSUE TITLE
fix(eds/store): Synchronize WriteEDS calls

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#2608]
Bridges sometimes call writeEDS concurrently, which can lead to data corruption as seen in #2335. This can be fixed by making sure the file writing is only happening by one goroutine at a time.

**Comment by derrandz** [comment]
I wonder if using locks on the store is sufficient solution or too simplistic, any suggestions or direction if I want to take up this issue?

**Comment by Wondertan** [comment]
Stripped locking would be efficient enough

**Comment by derrandz** [comment]
Do we have a test that reproduces the issue to work against? also your suggestion to use stripped locking implies that we have multiple store instance, is that the case? my understanding is that a bridge node has single store instance shared between multiple parties including exchange and listener, whose calls seem to be causing the issue. Your clarification would be much appreciated.

**Comment by walldiss** [comment]
Locking will make 2 parallel put synchronised. We actually don't need to sync them, but rather only leave only one process running. So we save valuable store throughput capacity (biggest bottleneck for syncing rn). 

https://github.com/celestiaorg/celestia-node/pull/2613

**Comment by musalbas** [comment]
In what scenarios are we writing EDS of the same block multiple times?

**Comment by Wondertan** [comment]
We do right because of a diff bug. Even when we fix it, we should still synchronise the EDSStore puts so that data corruption is impossible.
