### ISSUE TITLE
[Feature Request]: store openrpc.json in releases

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2611]
### Implementation ideas

This is so that it is historically accessible, and so that storing past versions does not cause any risk of manual user error.

v0.11.0-rc8 would be available at:
https://raw.githubusercontent.com/celestiaorg/celestia-node/v0.11.0-rc8/openrpc.json

v0.11.0-rc9 would be available at:
https://raw.githubusercontent.com/celestiaorg/celestia-node/v0.11.0-rc9/openrpc.json

etc.

**Comment by ramin** [comment]
@jcstein can we do this now? we will have the rpc stuff in a branch right?

**Comment by jcstein** [comment]
also, to catch discrepancies in versions, etc. for example, if I check out to v0.12.1 of celestia-node and then run `make openrpc-gen`, the version reflected is v0.11.0 instead of v0.12.1

**Comment by jcstein** [comment]
bumping this again. also, the API version hasn't been updated in a long time and the result still shows:

```
--> Generating OpenRPC spec
{
    "openrpc": "1.2.6",
    "info": {
        "title": "Celestia Node API",
        "description": "The Celestia Node API is the collection of RPC methods that can be used to interact with the services provided by Celestia Data Availability Nodes.",
        "version": "v0.11.0"
```
