### ISSUE TITLE
[Feature Request]: In-memory Test Swamp Tool

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#262]
### Summary

Need in fast execution of tests during PR stages

### Impact on users

Having a robust process of testing our implementation during every PR will be beneficial to track the quality and catch bugs as early as possible in scenarios where we are deploying the whole network setup (light-full-bridge). Now, unit tests covers the features in isolation and we need to expand testing envs and cases. 

### Cost of not doing

As we will start to have RC and release stages in CD/CD, the cost of not doing this tool will be costly in finding the root cause of found bugs during e2e testing phases

### Evidence

During devnet, we have found out that most of the bugs could be caught using a more simple testing approach by directly creating components/test scenarios in code base and not opting full into dockerising the components for testing, leaving the latter for more e2e testing approaches. 

### Steps that we need to achieve in order to start development of test scenarios using the tool:

1. Have a code-base cleanup #250 
2. Discuss the architecture design of the tool @Wondertan and @Bidon15 
3. Implementation of the architecture @Bidon15 

### What will be tested with this tool
Already:
- syncing
- dasing

Overall:
- header service
- share service

What is needed: 
- state service 
- networking setups

### What is close to what we want:
- DALC [repo](https://github.com/celestiaorg/dalc)

### Urgency

High

**Comment by liamsi** [comment]
Will this test-swamp also enable developers to quickly run tests locally?

**Comment by Bidon15** [comment]
> Will this test-swamp also enable developers to quickly run tests locally?

Yes. It should be by design to give the same UX as what is already happening with unit tests

**Comment by Bidon15** [comment]
For test swamp to operate we need these points: 
- Initialise the mocknet FullMeshLinked to link all full/bridge/light nodes
- Have `WithHost` and `WithCoreClient` options for node
  - `WithHost` is needed to link+connect nodes between each other
  - `WithCoreClient` is needed to feed bridge(currently it's full) node with an existing coreclient (mockedCoreClient)
 - Place the swamp in the `node/tests` directory
   -  `swamp` dir for the tool itself
   -  `domain_name/*_test.go` 

Ideally, swamp will take care of creating + linking + connecting all nodes and leaving the user to only focus on the testing scenario

Proposals so far:
- we need to migrate some of the existing full/light tests to the `node/tests` dir
- so far, having multiple embedded core client communicating between each other is a limitation, so we will start with testing 1 full/bridge node and 1+ light nodes
