### ISSUE TITLE
[Feature Request]: implement stubs for BadEncodingFraudProofs

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-node#263]
### Summary

Tracking issue: #4

Implement stubs to produce and verify BadEncodingFraudProofs.

### Impact on users

BadEncodingFraudProofs are necessary to have secure partial nodes.

### Cost of not doing

No partial nodes ☹️

### Implementation ideas

As the first step towards having BadEncodingFraudProofs, add stubs to the node for functions to produce and verify BadEncodingFraudProofs.

#### Producing BEFPs

**Full node** starts performing `FullAvailability` check.

https://github.com/celestiaorg/celestia-node/blob/40c4c62b7fb0ba8ef26c644c99a741295efd13d8/node/services/service.go#L137

During `FullAvailability`, repairing the square is attempted.

https://github.com/celestiaorg/celestia-node/blob/40c4c62b7fb0ba8ef26c644c99a741295efd13d8/ipld/read.go#L60-L62

The `error` is returned immediately and not processed. `RepairExtendedDataSquare` needs to be changed to check that the error is not `ErrUnrepairableDataSquare` (which indicates a need for more samples, orthogonally), and if not, instead create a BEFP using

1. The returned `ErrByzantineRow` or `ErrByzantineCol`, and,
2. A Merkle proof for shares in the above error that are missing from the error struct.

The second point will require `retrieveShare` to return a Merkle proof along with the share value.

https://github.com/celestiaorg/celestia-node/blob/40c4c62b7fb0ba8ef26c644c99a741295efd13d8/ipld/read.go#L49

A produced BEFP must then be disseminated across the network with some new p2p message (a separate issue).

#### Verifying BEFPs

When receiving a BEFP from the network (a separate issue), it is verified.

### Urgency

Medium

**Comment by renaynay** [comment]
Closing in favour of #528
