### ISSUE TITLE
GetSharesByNamespace JSON RPC returns the the old representation of NamespacedShares

### ISSUE THREAD

**Issue by oblique** [celestiaorg/celestia-node#2631]
### Celestia Node version

4b960224e735c7a7e2036f730b6ccc06f8688a2b

### OS

Arch Linux

### Steps to reproduce it

Do `share.GetSharesByNamespace` request.

### Expected result

I was expecting to get the new protobuf representation ([`share.p2p.shrex.nd.NamespaceRowResponse`](https://github.com/celestiaorg/celestia-node/blob/8deffba77b0e68f6a2229bc8266359eda704c584/share/p2p/shrexnd/pb/share.proto#L22-L25)):

```json
[
    {
      "shares": [],
      "proof": {
        "start": 1,
        "end": 2,
        "nodes": [
          "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEinncqCRtmn9rQpzZu1bRShpoTh01mE75gkp9C68byu",
          "/////////////////////////////////////////////////////////////////////////////w81Htmj5E2p0vlhWgUHbEu+jHu0S74GbTWrHUPWC0NB"
        ],
        "leafHash": "AAAAAAAAAAAAAAAAAAAAAAAAAAwECTkh44s4pzQAAAAAAAAAAAAAAAAAAAAAAAAADAQJOSHjizinNErclwFCmkujstcQOiIunyB5edz+oREPWyE1GeDzvN9+",
        "isMaxNamespaceIgnored": true
      }
    }
]
```

### Actual result

Instead I got the old representation ([`share.NamespacedShares`](https://github.com/celestiaorg/celestia-node/blob/8deffba77b0e68f6a2229bc8266359eda704c584/share/getter.go#L52-L56)):

```json
[
    {
      "Shares": [],
      "Proof": {
        "start": 1,
        "end": 2,
        "nodes": [
          "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEinncqCRtmn9rQpzZu1bRShpoTh01mE75gkp9C68byu",
          "/////////////////////////////////////////////////////////////////////////////w81Htmj5E2p0vlhWgUHbEu+jHu0S74GbTWrHUPWC0NB"
        ],
        "leaf_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAwECTkh44s4pzQAAAAAAAAAAAAAAAAAAAAAAAAADAQJOSHjizinNErclwFCmkujstcQOiIunyB5edz+oREPWyE1GeDzvN9+",
        "is_max_namespace_id_ignored": true
      }
    }
]
```

### Notes

I think the issue starts from [here](https://github.com/celestiaorg/celestia-node/blob/8deffba77b0e68f6a2229bc8266359eda704c584/nodebuilder/share/share.go#L60-L64).

**Comment by oblique** [comment]
Relevant issues: #2427, #2423.

Also in the new representation can you rename the field in snake_case format?

**Comment by distractedm1nd** [comment]
Good catch, we will still return `NamespacedShares` but we will make the json fields match and be all in snake_case

**Comment by oblique** [comment]
Tested the latest release and I still get the old representation. I think [this](https://github.com/celestiaorg/nmt/blob/ac56b3b59c7d6a7cd4d9923ac774fca098fe6f88/proof.go#L52-L83) should be removed.

**Comment by distractedm1nd** [comment]
@oblique That makes sense - it is probably removing those fields on unmarshalling because they do not have the same name. Don't know why the original proof struct is not tagged with the json fields

**Comment by distractedm1nd** [comment]
@oblique The protobuf definitions from nmt have now changed so that the fields are snake case - so your old actual result should be the new expected result. Or am I missing something?

**Comment by oblique** [comment]
I'm using `ghcr.io/celestiaorg/celestia-node:v0.11.0-rc11` and when I request `blob.GetProof` I get this result:

```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "end": 2,
      "is_max_namespace_id_ignored": true,
      "leaf_hash": null,
      "nodes": [
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABLdBzzpUnHG99n3rFul1zuDC3/mibQH8Ics9I1EP3muK",
        "/////////////////////////////////////////////////////////////////////////////yVANEGwvveNvq0ylhBwcRNmpTd/hLmgSlPtjrMfJSMj"
      ],
      "start": 1
    }
  ],
  "id": 4
}
```

The `is_max_namespace_id_ignored` is from the previous representation. If masrhialing was done by the new protobuf definition it should be `is_max_namespace_ignored`. I believe this is because the custom [`MarshalJSON`](https://github.com/celestiaorg/nmt/blob/ac56b3b59c7d6a7cd4d9923ac774fca098fe6f88/proof.go#L52-L83) was not removed.

**Comment by distractedm1nd** [comment]
Yes, it should, didn't even catch that - thanks

**Comment by distractedm1nd** [comment]
related #2728
