### ISSUE TITLE
[test]: test DASing with different max block sizes and amount of light nodes

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#266]

**Comment by adlerjohn** [comment]
It would be nice if we could also test even larger block sizes than the current maximum to see where things start breaking down.

**Comment by renaynay** [comment]
@adlerjohn Can you provide some specs for the tests you'd like to see run? Like

`test 1`: block size of ______
`test 2`: block size of ______, with _____ light nodes running in the network

etc.

**Comment by Wondertan** [comment]
Simple testing by sending payForMessage with 32 square width succeeds:
![image](https://user-images.githubusercontent.com/22449364/145210869-8b2cadbb-a8e9-4e55-9e3f-fa11ce336fdf.png)

Tested using a simple utility made by @evan-forbes in https://github.com/celestiaorg/celestia-app/blob/evan/mock-block-cmd/cmd/mock-blocks/main.go#L21.

@Bidon15, this might be highly relevant for you to test getSharesByNamespace in the real network environment. As a side goal, I would recommend forking the branch above and extending the CLI to allow more customization with CLI, so you can specify what square size you want. Also, would be cool if CLI can automatically detect RPC addresses so you won't need to specify it every time.

**Comment by Wondertan** [comment]
https://github.com/celestiaorg/celestia-node/issues/276

**Comment by adlerjohn** [comment]
A matrix of tests:

1. ODS 64x64x256 bytes (i.e. 1MiB blocks)
2. ODS 256x256x256 bytes (i.e. 16 MiB blocks)

1. 10 nodes
2. 100 nodes
3. 1000 nodes

**Comment by renaynay** [comment]
@Bidon15 can you track these desired testcases somewhere so that we don't forget about them? We don't have to do them now, but maybe a nice way to show desired testcases, what we've completed so far, the results of those completed tests, and what is still left TODO + small description on any blockers to running the tests.

**Comment by Wondertan** [comment]
https://github.com/celestiaorg/celestia-app/blob/evan/mock-block-cmd/cmd/mock-blocks/main.go#L66 - the code states that it is maxed size, while it was only 32x32

**Comment by renaynay** [comment]
closed in favour of #7
