### ISSUE TITLE
edsstore put file handling refinement

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/celestia-node#2673]
### Celestia Node version

v0.11.0-rc12

### OS

darwin/arm64

### Steps to reproduce it

Follow up from #2613, semi-related.

Would need to run this against a chaos monkey / fault injection framework to absolutely reliably  reproduce.

### Expected result

`store.put` should not ignore `f.Close` errors.

### Actual result

Errors that occur after file has been closed but before the filesystem syncs would be ignored due to the `defer`. In combination with the fact that we don't force a filesystem sync with `fsync`, this can cause a data loss and/or blockstore corruption.

**Comment by walldiss** [comment]
Errors in close will be logged since merge of https://github.com/celestiaorg/celestia-node/pull/2612. If we happen to see any problems, I'll post an update

**Comment by renaynay** [comment]
Can this be closed @walldiss ?
