### ISSUE TITLE
Improve CLI documentation for blob submit

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-node#2707]
The `celestia rpc blob submit` method has the following docs:

```
Flags:
      --fee int          specifies fee for blob submission (default -1)
      --gas.limit uint   specifies max gas for the blob submission
```

1. The denomination of the fee isn't documented.
2. The `-1` magic number isn't documented. If it's `-1` does it do something automatically? If yes, why not just do that when `--fee` isn't specified?
3. The documentation for gas limit says "max gas" but really it's just "gas" since all gas is consumed.

**Comment by vgonkivs** [comment]
Fixed in scope of the global rpc rework. https://github.com/celestiaorg/celestia-node/pull/2812
