### ISSUE TITLE
chore(rpc): deprecate subtmitPayForBlob

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#2725]
We should deprecate our `state.SubtmitPayForBlob` method in favour of `blob.Submit`

**Comment by distractedm1nd** [comment]
![image](https://github.com/celestiaorg/celestia-node/assets/16523232/79f43205-bd54-4de8-984b-9519a29b728d)

**Comment by renaynay** [comment]
so good lol

**Comment by distractedm1nd** [comment]
Closed by #2809
