### ISSUE TITLE
[Feature Request]: allow subscribing to new blocks

### ISSUE THREAD

**Issue by SuperFluffy** [celestiaorg/celestia-node#2737]
### Implementation ideas

A nice feature would be to subscribe to new blocks under a target namespace, maybe something like `blob.Subscribe` that takes 1 or more namespaces. It would be great to receive the current height and a map of `namespace -> [blob]` (the RPC should return an empty map and/or list if no blocks were written).

At the moment we can use `header.Subscribe` and then extract the most recent `height`. We can then follow this up with `blob.GetAll` using `height` and a single `[MyNamespace]` as parameters.

This is fine and not too inconvient, but a direct subscription to blocks that avoids the extra RPC would be a good feature for a data availability layer.

**Comment by Wondertan** [comment]
Thanks for the issue! We had something like this in mind for a while but never received any feature requests from any of teams. We should def do blob.Subsribe
