### ISSUE TITLE
share/availability: Remove `ProbabilityOfAvailability` endpoint

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2769]
Useless, it's constant for now and if you're interacting with a node and asking if if SharesAvailable, you should already know whether it's `light` or `full`

cc @musalbas

**Comment by Wondertan** [comment]
Literally, the only value this endpoint brings is the computation of a static formula with constant parameters. 

As long we don't allow changing how much LN sample in runtime, there is no reason to have this endpoint.

**Comment by musalbas** [comment]
Will there be another way to check how many samples are completed for latest block then?

**Comment by distractedm1nd** [comment]
By looking in the config. I do not understand why we should provide an API endpoint that returns a static value calculated with a constant from the config. Especially for someone elses node

**Comment by musalbas** [comment]
What is the API endpoint to check how many samples are completed for the latest block? This cannot be found in the config, it is dynamic.

**Comment by Wondertan** [comment]
This is different from what the current endpoint does. To achieve what you describe, we would need to change the ShareAvailabe call to return how much it sampled successfully or store that info so that the `ProbabilityOfAvailability` can return this info back

**Comment by musalbas** [comment]
By removing this endpoint then, there is no way to query how many samples have been completed for latest block

**Comment by renaynay** [comment]
The point here is that we do not do the behaviour that you're discussing (dynamic sample #)

**Comment by musalbas** [comment]
What's dynamic sampling? I just think there should be a way to query how many samples have been completed for the latest block as it could be useful for UXes or monitoring tools.

**Comment by Wondertan** [comment]
Then, we should change this issue to support what you want, and I propose to make it part of SharesAvailable call while still removing the current one

**Comment by renaynay** [comment]
I agree with @Wondertan  - this endpoint is useless and poorly designed anyway.

**Comment by renaynay** [comment]
https://github.com/celestiaorg/celestia-node/pull/2797
