### ISSUE TITLE
[Bug]: When celestia-node is run with `full start --core.remote <url>` it exits after 1 failed request to `<url>`

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/celestia-node#279]
### Celestia Node version

Semantic version: v0.1.0-1-g8e42e6a Commit: 8e42e6a41e237d4f109680afb4545cff47a55013

### OS

ubuntu

### Install tools

docker

### Others

full -r /celestia-full start --core.remote tcp://192.167.10.2:26657 --headers.trusted-hash A9272DAD1BEBEF104EBDBF071E39789E21C0650AF5B76A7062213B772B6B925E

### Steps to reproduce it

From a fresh ubuntu box run:
```
apt update
apt install docker.io -y
apt install docker-compose -y
git clone https://github.com/celestiaorg/devops-test.git
cd devops-test/devnet
git checkout -b jbowen93/node-repro
chmod 0600 celestia-node/full0/nodekey0
chmod 0600 celestia-node/full1/nodekey1
docker-compose -f docker/docker-compose-repro.yml up
# Let run for ~10 seconds before ctrl-c to exit
docker-compose -f docker/docker-compose-repro.yml logs full-node0 full-node1
```

### Expected result

Celestia node doesn't kill itself on single message failure to core.remote server and instead retries with appropriate incremental delay

### Actual result

Celestia node exits after the first message to the core.remote server fails

### Relevant log output

```shell
full-node0    | 2021-12-08T18:43:45.158Z	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s
full-node0    |
full-node0    | Error: dial tcp 192.167.10.2:26657: connect: connection refused
full-node1    | 2021-12-08T18:43:46.419Z	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s
full-node1    |
full-node1    | Error: dial tcp 192.167.10.2:26657: connect: connection refused
```

```
full-node0 exited with code 1
full-node1 exited with code 1
```
```


### Notes

Presumably it's a mishandling of the response being connection refused

**Comment by Wondertan** [comment]
Also, is this really a bug? I feel like this is more a feature request for connection retries, rather than a bug, but that is fine.

**Comment by Wondertan** [comment]
@renaynay, Would you mind looking into implementation ideas, so we can mark this as a Good First Issue to attract outside contributors? This should be trivial to implement.

**Comment by renaynay** [comment]
Yeah can write up the issue.

**Comment by renaynay** [comment]
We can try dial the remote node 3 times?

**Comment by renaynay** [comment]
Use [this method](https://github.com/tendermint/tendermint/blob/master/rpc/client/http/http.go#L128) and pass in a standard http.Client that can perform retries.

**Comment by renaynay** [comment]
https://github.com/hashicorp/go-retryablehttp
