### ISSUE TITLE
rpc: Implement an RPC endpoint for users to submit transactions to Celestia Node

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#28]
Implement an RPC server in package `rpc` that will handle inbound requests from users to submit transactions. This feature should be available for both `light` and `full` nodes. 

- [ ] Implement simple server that listens on a default port
- [ ] Add a config parameter to change the port
- [ ] Handler for requests on endpoint `/submit_tx` -- should trigger an `AccountQuery` in the node to get the state for given account in order to submit a tx
  - [ ] optional, implement `/submit_tx_sync` which would be blocking, vs `/submit_tx_async`

**Comment by renaynay** [comment]
Question: should we enable this RPC server by default?

**Comment by liamsi** [comment]
In tendermint nodes run with the RPC server but by default it only listen on the local / loopback interface. I think for devnet it does not matter to much if we turn it on by default or not. I think later it should be optional.

**Comment by evan-forbes** [comment]
can't we just enable/forward to the grpc server for the app instead of implementing one for node?

**Comment by renaynay** [comment]
I think this is the plan as of right now, cc @Wondertan

**Comment by Wondertan** [comment]
Missed this somehow. Yes, exactly, let's  do this:
> can't we just enable/forward to the grpc server for the app instead of implementing one for node?

**Comment by renaynay** [comment]
Related to #265
