### ISSUE TITLE
bug: openrpc.json has output line in file, breaking node-rpc-docs.celestia.org

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#2815]
I cloned the old version of RPC docs to evaluate which one to use (either using [a component like is in the docs now](https://docs.celestia.org/api/v0.11.0-rc13/) or improving site @distractedm1nd made) and noticed that [the openrpc.json spec that is referenced on the open-rpc docs](https://raw.githubusercontent.com/celestiaorg/celestia-node/openrpc-spec/openrpc.json) has extra output in the json file:

```json
--> Generating OpenRPC spec
{
    "openrpc": "1.2.6",
```

**Comment by ramin** [comment]
@jcstein this was removed in the branch `openrpc-spec` with last set of commits: 

https://github.com/celestiaorg/celestia-node/commit/9e43c637c6d3fd4d9b5bcdb051a1b3110cac3b30#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L153

@vgonkivs @distractedm1nd what is the plan with this branch?

**Comment by jcstein** [comment]
hey @ramin - it looks like it's still there, no? https://github.com/celestiaorg/celestia-node/blob/openrpc-spec/openrpc.json
this pr resolves it https://github.com/celestiaorg/celestia-node/pull/2816

i don't think we need this anymore though as until they are stored with releases on main https://github.com/celestiaorg/celestia-node/issues/2611 , i will be manually generating them

**Comment by ramin** [comment]
@jcstein merged to the feature branch. Yes we removed but didn't commit a fixed openrpc.json, sorry!

**Comment by jcstein** [comment]
all good! thank you!

**Comment by vgonkivs** [comment]
Should we close this one https://github.com/celestiaorg/celestia-node/issues/2611 ?

**Comment by jcstein** [comment]
i don't think so. i don't see on the release or in main?
