### ISSUE TITLE
modshare/cmd: use height as an argument intead of full ExtendedHeader

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2848]
Currently to work with share cmds something like the command below is required.
```
celestia share get-eds “$(celestia header get-by-height 500 --node.store ~/.celestia-light-mocha-4 | jq .result)” --node.store ~/.celestia-light-mocha-4
```

Instead, we should be just passing either the hash or height of the header as an argument. The cmd will then internally do 2 rpc calls

**Comment by bao1029p** [comment]
hi @Wondertan, is this issue still open for work ? thank you

**Comment by Wondertan** [comment]
It is! Feel free to take it over @bao1029p

**Comment by bao1029p** [comment]
thank you
