### ISSUE TITLE
node: API to inject custom modules on New

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#285]
## What 
Right now, the only customization available for the Node is through `node.Config`. This is not enough and `node` package users(including ourselves) should be able to inject customized modules, like setting custom Host(required by https://github.com/celestiaorg/celestia-node/issues/262) or like setting custom private key https://github.com/celestiaorg/celestia-node/issues/284. 

## How
To accomplish this we can rely on DI magic. The API from the node perspective should look like
```go
node.New(cfg, repo, node.With(host))
```

So as you can see there is a new option `node.With()` that accepts variadic `interface{}`, so users can really swap in the module of their interest in the Node. Surely, if something goes wrong we should error.

**Comment by renaynay** [comment]
Not relevant with current design of node
