### ISSUE TITLE
cmd: command accessing RPC should detect running node

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2859]
## Problem
We have to specify `node.store` flag every time we want to do an RPC request, but it should be possible to detect running instance automatically.

I am currently playing a lot with CLI, and it's a pretty good experience, however copying `node.store` flag all over again is annoying. In all Unix daemon apps, you don't have to specify the running instance all over again when you use the default setup.

## Implementation 
* Take the default network as NetworkType
* Detect running node type by looking at the directory.
	* If there is a lock, it means a node is running, so we can use it.
* Combine network type and detected node type and use that as `node.store`

**Comment by vgonkivs** [comment]
Q: what if multiple nodes are running in parallel on different ports?

**Comment by Wondertan** [comment]
This case is unlikely, and I still don't think we should allow running multiple node types at the same in general. I would only allow that across different networks. For that, we should always prefer the default network.

**Comment by vgonkivs** [comment]
Then we should not allow several nodes with the same node type too.

**Comment by vgonkivs** [comment]
Tbh I'm not sure that it will be helpful or easier to use from the user's perspective. All information anyway lives inside node's config. So to automatically detect the running node we will have to pass node type and network (2 flags instead of 1 node store) unless we will not find another approach.

What we can really do is to make a persistent rpc connection via cli so the will pass node store only once. Adding quit/close cmd will close this connection.

**Comment by Wondertan** [comment]
Yes
> Then we should not allow several nodes with the same node type too.

**Comment by Wondertan** [comment]
> Tbh I'm not sure that it will be helpful or easier to use from the user's perspective. All information anyway lives inside node's config. So to automatically detect the running node we will have to pass node type and network (2 flags instead of 1 node store) unless we will not find another approach.

Passing optional options is totally fine IMO

**Comment by vgonkivs** [comment]
cc @jcstein for visibility

**Comment by jcstein** [comment]
lost track of this ping, thanks for the tag. the proposed solution sounds good to me

**Comment by mastergaurang94** [comment]
Can I take a crack at this? Have light go codebase experience.

**Comment by mastergaurang94** [comment]
> Yes
> 
> > Then we should not allow several nodes with the same node type too.

Is this part of this PR too?

**Comment by Wondertan** [comment]
Hello @mastergaurang94, feel free to take this over. This is a very high ux impact

**Comment by mastergaurang94** [comment]
Yup, agreed, will give it a go.
