### ISSUE TITLE
blob: TestBlobService_Get is flaky

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2860]
```
--- FAIL: TestBlobService_Get (0.02s)
    service_test.go:221: 
        	Error Trace:	/home/runner/work/celestia-node/celestia-node/blob/service_test.go:221
        	            				/home/runner/work/celestia-node/celestia-node/blob/service_test.go:294
        	Error:      	Received unexpected error:
        	            	empty shares received
        	Test:       	TestBlobService_Get
    --- FAIL: TestBlobService_Get/not_included (0.00s)
        testing.go:1490: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
 ```

**Comment by ramin** [comment]
@vgonkivs temporarily added https://github.com/celestiaorg/celestia-node/blob/main/blob/service_test.go#L1 to skip the test on mac os to help with CI passing, just in case it suddenly looks fixed

**Comment by vgonkivs** [comment]
Had a private discussion with @walldiss regarding this case and figured out that GetSharesByNamespace can behave differently:
1. Row1 = [`Namespace1`, `Namespace3`]
`Namespace1` < `Namespace2`
`Namespace2` < `Namespace3`
Requesting Namespace2 will return empty shares + non-inclusion proof.

2. Row1 = [Namespace1]
    Row2 = [Namespace3]
`Namespace1` < `Namespace2`
`Namespace2` < `Namespace3`
Requesting Namespace2 will return empty shares + empty proof.

Before that, we have never considered non-inclusion proofs for the Blob Module. cc @Wondertan 

@nashqueue do you need non-inclusion proofs as a result of `GetProof` if the blob does not exist? If yes, how we can handle case 2. where no shares and no proofs?

**Comment by huutrong1994** [comment]
🖐Hello! Welcome to #CelestiaCommunity

We are happy to announce  ($TIA) is now available on DEX #PancakeSwap 💪

👉  Our ONLY Contract:  
 CA:      0xf2caebbb49a7733a7c5cff571af849a6b52d346c

🥞 BUY ON PANCAKESWAP:

 https://pancakeswap.finance/swap?outputCurrency=0xf2caebbb49a7733a7c5cff571af849a6b52d346c

▫️Name:   Celestia 
▫️Symbol : TIA 
▫️Decimals : 18

📆Launch on  #BINANCE at Oct 31, 16:00 (UTC)
