### ISSUE TITLE
OOM on Light and Bridge nodes

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2905]
I found my mainnet LN getting OOMed a day ago on 8GB DO instance. @renaynay, found here BN ooming on BN with 16GB instance. There is definitely a leak somewhere, and it's likely to exist in the  FN as well.

At this point, there is not much info on why it happens, as well as why we haven't seen this on other networks like Arabica, Mocha, and Robusta

**Comment by Wondertan** [comment]
Right now, I am collecting profiles for further investigation

**Comment by Wondertan** [comment]
Running it with pprof for a day. No suspicious memory grow noticed, as well nothing leaky in profiles

**Comment by Wondertan** [comment]
Running for another 24 hours with continuous profiling. RAM usage is stable at 1.22 GB with a single spike to 1.91 GB. 

Clearly, the leak does not happen under normal conditions, and some edge case has to be triggered in order to see it. It's unclear what exactly one has to do to trigger it, and I don't see any better ideas than continue profiling and observing.

**Comment by Wondertan** [comment]
New update. My node oomed again during badger compaction, which bursts ram usage. The node uses around 3GB of RAM right before the compaction, and most of the profiles lead to badger allocations. We have yet to investigate if this is a badgerv4  bug or if we incorrectly use it. 

Talking to @Jorropo, he said they observe similar behavior with badger.

**Comment by boobcactus** [comment]
Just wanted to add that I am experiencing this issue on Arabica and have begun collecting pprof info. My server has 16GB of memory and the celestia light process will slowly consume until it's OOM

**Comment by Wondertan** [comment]
I am running the binary again with gomemlimit=2mib and gogc=25 to make runtime more conservative about ram usage

**Comment by Jorropo** [comment]
Such a low GOMEMLIMIT is equal to:
```go
for {
 runtime.Gc()
 time.Sleep(time.Second)
}
```

**Comment by Wondertan** [comment]
![image](https://github.com/celestiaorg/celestia-node/assets/22449364/d9dea53d-054c-4b93-87f5-a7f31c50a430)

This so far seems to be the leakiest of them all. It looks like badger txs are not cleaned up after Commit. Particularly, the trace comes from `peerstoreds`'s [flush](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/peerstore/pstoreds/addr_book.go#L50). 

So seems like there might be a bug in the DS-backed store, or it's [the bug](https://github.com/dgraph-io/badger/commit/1741e474446b4eb053b1a959ea8d31d9d5cf6948) in Badger that was fixed in main, but nit in the release we use.

**Comment by Wondertan** [comment]
* I tried with the latest master of Badger to test if [the bug](https://github.com/dgraph-io/badger/commit/1741e474446b4eb053b1a959ea8d31d9d5cf6948) has anything to do with this, but it kept leaking
* Out of curiosity, I tried to switch to [Pebble](https://github.com/cockroachdb/pebble), yielding results worth exploring.
	* LN kept syncing with no more than 500mib in use
	* It's not clear if, CPU-wise, the Pebble is more efficient than the Badger
	* Pebble looks like a much better maintained and more approachable code. It's easier to read, and it's very well documented.
	* Pebble provides more knobs to tune up things going further.

**Comment by boobcactus** [comment]
Did you notice any instability after switching to pebble? I'd be interested in building rc6.1 with pebble swapped in if that's possible by an end user (like with a go.mod dependency swap)|

(I need to keep my LN running 24/7 for Dymension and it keeps going down, so I'm excited for a solution)

**Comment by Wondertan** [comment]
> Did you notice any instability after switching to pebble

I think it's too early to make any conclusions on stability. I need to run it for at least a week to be sure we don't have any side-effects after switching.

**Comment by Wondertan** [comment]
__Update on the badger:__
The code leaks in places where we write a single value to the Badger datastore directly, with `Put`. In places where we use `Batch` with multiple written it works well. 

As an experiment, I tried using `Batch` inside of `Put` in [`go-ds-badger4`](https://github.com/celestiaorg/go-ds-badger4/commit/d428d9690c756ce02b667541d85b328dc2cd676a) adapter, but it didn't yield any result. Profiles show that badger still leaks transactions inside of used batches.
![image](https://github.com/celestiaorg/celestia-node/assets/22449364/3d921ae2-0f01-4bef-be51-647a5ec1a394)

At this point, the only clue we have is a single entry written vs multiple at the same time and this is likely to be a bug inside of the Badger.

**Comment by Wondertan** [comment]
__On pebble__:

Simply migrating to pebble made our node consume constantly around 300mibs for LN even during compactions. This is a good result, but we should not rush with migrating as its very disruptive. Also, considering that LNs won't have a high write-load we may also consider a different KV store engine that is not LSM-tree based and much simpler, likely B+ tree.

For now, I think we should focus on figuring out a simple patch for Badger and considering KV store migration in a separate issue.

**Comment by Wondertan** [comment]
__New update on badger:__

We were able to break the following by writing an additional entry every time we did a single `Put`. Even when we write two entries it still leaks.
> At this point, the only clue we have is a single entry written vs multiple at the same time and this is likely to be a bug inside of the Badger.

However, there is good news. We were able to accelerate the memory growth by rewriting value for the same key over and over again. This also aligns with leaking code paths, where we update the state of something with a constant key. So there is enough proof at this point that the bug is in Badger.

The next step is to write a unit test for Badger that shows that and opens an issue on their side.

**Comment by Wondertan** [comment]
The bug is in `DetectConflicts` feature of Badger. By disabling it, I was able to get a stable RAM usage over an hour already

**Comment by Wondertan** [comment]
__New final update:__

The bug is not in `DetectConflicts` as I thought. Disabling `DetectsConflicts` just removes one of the leaks caused by the bug and it still had to be accompanied by some other case because everything was fine when I worked with Badger directly. A pure Badger [test for overwriting the same key](https://github.com/celestiaorg/celestia-node/commit/864ffa2185d81e41690edbfddb2580f7b83ccc54) didn't show any leaks.

But right after `DetectConflicts` finding, I kept playing with the Badger to the point where I reduced RAM usage during sync __up to 10 times__(more on that later). This allowed me to detect another more minor leak in Badger that I hadn't realized but had seen before.

After a day of pure debugging, I found the true culprit of all the problems: an edge case in Badger. Check the patch for it [here](https://github.com/dgraph-io/badger/pull/2031). Basically, when we flush an empty Batch, the transaction inside of the leak is not marked as read. Flushing of an empty Batch happens in DHT's provider manager. When the manager [loads the provider set via `ds.Query`
](https://github.com/libp2p/go-libp2p-kad-dht/blob/b63ad6096833d36b365f1361edab871f6cdc283c/providers/providers_manager.go#L349-L354C3), internally [the `autobatch`](https://github.com/ipfs/go-datastore/blob/1caa2449ed7c222eee335f9b51e9c6818ff3595f/autobatch/autobatch.go#L30-L32) wrapper [does the `Flush`](https://github.com/ipfs/go-datastore/blob/1caa2449ed7c222eee335f9b51e9c6818ff3595f/autobatch/autobatch.go#L148-L155). As this query happens on startup, the batch is empty and thus the issue.(cc @Jorropo, this should explain why IPFS observes the leak with Badger as well)

> ___Badger internals of the bug___: 
When we flush a datastore `Batch` with no data, it would not notify the internal synchronization primitive(`Watermark`) that the read side of the transaction has ended. The bug surprisingly does not leak the transaction or batch directly, but does not free up resources inside of the `Watermark` and does not progress the `Watermark` internal monotonic counter. The leak inside of the `Watermark` is the minor leak I mentioned in the previous paragraph, and the stalled counter causes the `DetectConflicts` feature to leak, which is the original leak.

The mystery is solved, and now we need to land the patch and apply all the optimizations I've collected along the way.

P.S. Debug branches:
* https://github.com/celestiaorg/celestia-node/tree/badger-reproducible-bug
* https://github.com/celestiaorg/celestia-node/tree/badger-bump - fixed with optimization and history of all the debug attempts
* https://github.com/celestiaorg/go-ds-badger4/tree/debug - debug branch on datastore adapter
* https://github.com/Wondertan/badger/tree/debug - debug branch on the Badger itself

**Comment by distractedm1nd** [comment]
Yes the watermark has to do w GC and we explored seeing watermark in pyroscope before. We fixed the leak but then we changed the badger parameters again recently so it's no longer fixed I assume

**Comment by Wondertan** [comment]
> We fixed the leak but then we changed the badger parameters again recently so it's no longer fixed I assume

The leak has always been there(see above) various badger params only make it less or more severe.
