### ISSUE TITLE
Set GOMEMLIMIT

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2910]
We see OOMes from time to time, like in #2905. As we are targeting resource-restricted environments, we should be more cautious about OOMs, and this is where the new GOMEMLIMIT runtime param can help us. 

The main problem that can sometimes happen is related to spikes in RAM usage. Every time runtime requests memory from OS, it takes 2x more than it currently has. So, if a program running with 4GIB needs more memory, it will request 4GIB more, even if it needs only 100MiB. On the machine with only 8GIB, this will cause OOM to kill the process, even when it could continue running technically.

The Golang team was aware of this issue and introduced the GOMEMLIMIT runtime param, which provides a soft limit and prevents 2x allocations if they exceed the limit, as well as start GCing more aggressively. By default, it's effectively disabled, so we should enable it by either:
* Setting the env var in the docker or ask users to do so if the run pure binary. Users would need to define a limit themselves
* Set in runtime with function in runtime pkg. We would be responsible for setting the limit value by looking at amount of RAM on the machine.

I prefer the second option with an ability to control this by power user if requested.

Ref: https://weaviate.io/blog/gomemlimit-a-game-changer-for-high-memory-applications

**Comment by renaynay** [comment]
TODO: take a look at how other node software approaches GOMEMLIMIT

**Comment by renaynay** [comment]
Closing as this issue is outdated and we haven't had severe spikes on mem use. We also have shwap now, which has proven to resolve a lot of the resource consumption spikes we were seeing prior. We can reopen this issue if we observe spikes in mem use.
