### ISSUE TITLE
[Feature Request]: Prometheus metrics for bridge/light node health and liveliness

### ISSUE THREAD

**Issue by ilhanu** [celestiaorg/celestia-node#2921]
### Implementation ideas

We have recently forked and customized our own Prometheus exporter for the Celestia node. We are operating a bridge-node connected to the validator we are running. There have been plenty of ways of exporting metrics from the Celestia node, but we are proposing an incorporated exporter coming directly from the node itself. This addition doesn't need to be expansive, and we don't anticipate it requiring a lot of maintenance.

Currently, the port 8890 provides only libp2p output, which is not entirely relevant for us, as it contains a lot of other technical figures that do not align with our primary monitoring needs.

Our main interest lies in specific metrics crucial for monitoring the health and liveliness of the Celestia node, such as `local block height`, `network block height`, and overall `node health (up)`.

We would like to put this proposal on the agenda for consideration. For now, we are managing the monitoring independently, but I believe having these metrics as a source directly from the node software would be a significant enhancement. Such a feature would not only benefit our operations but could also be invaluable for the broader community of Celestia node operators.

**Comment by renaynay** [comment]
Hi @ilhanu, thanks for submitting this issue. 

We already have metrics for reporting the local block height (`head_total`). There are other ways to check node health (whether it is up or not), such as looking at either `head_total` and ensuring that it is progressing, but we could also implement a generic node health metric as well. We can also introduce a new metric for the syncer to report the network head.

**Comment by renaynay** [comment]
FWIW, we are also adding some metrics that are specific to bridge nodes here: #2863

**Comment by ilhanu** [comment]
Hi @renaynay, Can you please point me to the metrics `head_total` in the code, couldn't find it in the api docs of the celestia-node. 

And one thing that was not clear for me is will these new metrics still require otel-collector or will it be outputted through a prometheus port, like the p2p metrics ?

**Comment by derrandz** [comment]
@ilhanu most metrics are pumped through the otel-collector, which in turn is scrapable by prometheus. The p2p metrics are a special case as they are native libp2p network performance metrics, and celestia clients expose them as is, for diagnostics and network performance monitoring.

As far as actual DA metrics (_if you will_), you can configure prometheus to scrape the otel-collector. Check https://github.com/celestiaorg/celestia-node/blob/main/docker/telemetry/prometheus/prometheus.yml and https://github.com/celestiaorg/celestia-node/blob/main/docker/telemetry/ for more info on how to spin up your local telemetry stack.

As far as requesting a feature is concerned, what is needed in this telemetry stack is a Celestia standardized grafana dashboards for the metrics it provides, will make node runners life easier.

**Comment by ilhanu** [comment]
@derrandz thank you for the explanation. we will switch to the otel-collector.

For the grafana dashboard we will try to publish one. There are a couple of examples out there for Celestia. We will combine the best of them in a overview with relevant metrics for node operators.

feel free to close the issue.
