### ISSUE TITLE
metrics: DRY code pattern

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#2928]
We have the following code pattern in several metrics files: 
```
func (m *metrics) observe(ctx context.Context, observeFn func(context.Context)) {
	if m == nil {
		return
	}

	if ctx.Err() != nil {
		ctx = context.Background()
	}

	observeFn(ctx)
}
```

It would be nice if it could be DRY'd as a utility.

Ref: https://github.com/celestiaorg/celestia-node/pull/2863#discussion_r1372842413

**Comment by cyneptic** [comment]
i'd like to tackle this issue if thats alright.

I'm assuming we're talking about the context validation here and not the check to see if struct is empty or not correct?

**Comment by Wondertan** [comment]
Feel free to give it a shot

**Comment by anubhavitis** [comment]
@Wondertan 
I want to work on this. As per my understanding, there are several decorators that does context validation before running the passed func, and you want this part of the code to by dry'd to util func?

Or you just want to focus on context validation, and keep the decorator intact?

**Comment by cyneptic** [comment]
just a heads up, i've already fixed this in a pull request, awaiting review.
