### ISSUE TITLE
modp2p: change user UserAgent name

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2932]
Currently, its `celestia-<network-name>`, which in mainnet it looks like `celestia-celestia`.We might just trim `celestia-` prefix.

Related #2908

**Comment by ATREAY** [comment]
Hey @Wondertan, can I work on this issue if you are not currently working on it?

**Comment by Wondertan** [comment]
Hey @ATREAY, yes, go for it! 

The file where this is defined is at nodebuilder/p2p/host.go. 
Would be great to fix #2908 as well

**Comment by Wondertan** [comment]
The network version is encoded in the network string. p2p.Nerwork

**Comment by ATREAY** [comment]
Hey @Wondertan, I've made the necessary changes. Could you please take a look whenever you have a moment and let me know if any changes are required?
