### ISSUE TITLE
test(swarm): run swamp tests with `t.Parallel` to speed them up

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2961]
We should also consider doing the same for unit tests.

**Comment by ramin** [comment]
i've found some of the flakiness of the swamp/integration tests was caused been alleviated by using build tags to allow running them separately/isolated, i fear that introducing the parallel would be a rabbit hole we don't have time/resource for at moment. We've made them run in "parallel" via different CI jobs in https://github.com/celestiaorg/celestia-node/pull/3114 and i'd suggest that should be enough on this for now.

**Comment by Wondertan** [comment]
We should do this for at least unit tests imo

**Comment by ramin** [comment]
@Wondertan agree, i'll make a fresh issue so we can keep history ok skipping it for swamp
