### ISSUE TITLE
share: `GetShares` method for `Getter` interface

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#2983]
We only have the `GetShare` method, which gets us a single share/sample. It worked well before, but with shwap sampling protocol, we need a method that gets multiple shares within one call to allow batching requests. 

```go
GetShares(ctx context.Context, hdr *header.ExtendedHeader, shrIdxs ...int) ([]share.Share, error) 
```

The method can also satisfy singular requests, so we would also deprecate `GetShare`

**Comment by Dadiselef20** [comment]
> Solo tenemos el `GetShare`método, que nos proporciona una única acción/muestra. Funcionó bien antes, pero con el protocolo de muestreo IPLDv2, necesitamos un método que obtenga múltiples recursos compartidos en una sola llamada para permitir solicitudes por lotes.
> 
> ```go
> GetShares(ctx context.Context, hdr *header.ExtendedHeader, shrIdxs ...int) ([]share.Share, error) 
> ```
> 
> El método también puede satisfacer solicitudes singulares, por lo que también desaprobaríamos`GetShare`

https://github.com/celestiaorg/celestia-node/issues/2983#issue-2022476441

**Comment by Dadiselef20** [comment]
https://github.com/celestiaorg/celestia-node/issues/2983#issue-2022476441

**Comment by Dadiselef20** [comment]
https://github.com/celestiaorg/celestia-node/issues/2983#issue-202247644

**Comment by vgonkivs** [comment]
We had something similar but with range. I think we can combine somehow these two issues:
https://github.com/celestiaorg/celestia-node/issues/2304

**Comment by Wondertan** [comment]
I dont see how we can combine range requests and  single share requests in a single method ergonomically. Please show if you have an idea

**Comment by vgonkivs** [comment]
instead of having `shrIdxs ...int` it could be some kind of a filter struct that determines the behavior.

**Comment by vgonkivs** [comment]
```
type filter struct {
idx []uint
start uint
end uint
}

func(f *filter) Next() uint {}
```
