### ISSUE TITLE
use a different network than the default public ipfs network

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#3]
## Summary

Ideally, we want to connect only to nodes that run some lazyledger node, too.

## Problem Definition

IPFS nodes connect to a large set of nodes by default. That's cool but we want our nodes to only connect to a set of nodes that 1) load the LL ipld plugin and 2) run some other portion of the lazyledger software (light client, (full) node, archival node etc).

## Proposal

- Provide an alternative set of bootstrap nodes. Ideally, we'd automatically deploy a node before each release and its address to the default config (this is good for testing purposes).
- Add a way to only connect to a subnet. Using a private network (swarm key) could be the first very simple approach. Ideally, though we would modify to which nodes the ll-core nodes connect to by using some form of different network ID / protocol version (?) than the public ipfs network uses.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Wondertan** [comment]
Using the public IPFS network basically means sharing global DHT. This could be a case even without using a full-blown IPFS node.

The definition of done for the issue:
- [ ] At least one "seed" node deployed serving bootstrap/network entry point needs
- [ ] so we can hardcode it or define it in a hardcoded config. 
- [ ] We should also prepend/append custom protocol IDs to protocols we reuse from IPFS, e.g. Bitswap This is required for content not being shared between the networks, though there is no strong oppositions to that.

**Comment by Wondertan** [comment]
Wrong button 😅

**Comment by Wondertan** [comment]
@liamsi, I feel like this can be closed. WDYT?

**Comment by Wondertan** [comment]
Closing as we are using a completely different network.
