### ISSUE TITLE
[Feature Request]: Allow clients to configure Gas Price in SubmitOptions

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/celestia-node#3053]
### Implementation ideas

Currently, clients are able to configure `Fee` and `Gas` as part of `SubmitOptions`. As `Gas` depends on blob size, it requires the client to calculate it for each blob and adjust `Fee` accordingly. The client only cares about the Gas Price so that the transaction can be prioritised.

Hence this is a feature request that the client should be able to configure a Gas Price _once_ that can be used to calculate and adjust fee for all subsequent submitted blobs.

**Comment by musalbas** [comment]
I think it would be cleaner to also add it as a parameter for transactions being submitted, rather than as global variable. Or rather, the global variable could just be to set the default.

**Comment by tuxcanfly** [comment]
Partially addressed by https://github.com/rollkit/go-da/issues/30 as we're handling this celestia-da for now.

**Comment by adlerjohn** [comment]
+1 to it should be a per-tx parameter.
