### ISSUE TITLE
Celestia Bridge crashes with to many open files

### ISSUE THREAD

**Issue by staking4all** [celestiaorg/celestia-node#3061]
### Celestia Node version

Semantic version: v0.12.1 Commit: b7b6350f8921d4454b8a38c8485d74f908fb6a61 Build Date: Sun Dec 17 05:14:17 PM CET 2023 System version: amd64/linux Golang version: go1.21.2

### OS

DISTRIB_ID=Ubuntu DISTRIB_RELEASE=22.04 DISTRIB_CODENAME=jammy DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

### Install tools

Running local binary

### Steps to reproduce it

Run bridge node for validator. Then run into error after running since mainnet. Has only occued once, but has done so on mainnet node

Error is
131 225 62 201 255 255 255 255 255 255 255 255] right:[] inf:false size:0}] thisSize:0 dropPrefixes:[]} error: While opening directory: /home/celestia/.celestia-bridge/inverted_index/. error: open /home/celestia/.celestia-bridge/inverted_index/: too many open files

keeps repeating itself, higher cpu usage. Restart fixes

### Expected result

no error and just run

### Actual result

error

### Relevant log output

```Shell
131 225 62 201 255 255 255 255 255 255 255 255] right:[] inf:false size:0}] thisSize:0 dropPrefixes:[]} error: While opening directory: /home/celestia/.celestia-bridge/inverted_index/. error: open /home/celestia/.celestia-bridge/inverted_index/: too many open files
```

### Notes

Error on mainnet node for validator Staking4All

**Comment by mindstyle85** [comment]
[bridge-mainnet.txt](https://github.com/celestiaorg/celestia-node/files/13842324/bridge-mainnet.txt)

**Comment by ramin** [comment]
@mindstyle85 @rooiie did you get around this, assume via increasing the max open files with `ulimit`?
