### ISSUE TITLE
Bridge under heavy load since 12/27/2023 8:00AM

### ISSUE THREAD

**Issue by JB273** [celestiaorg/celestia-node#3062]
We see disturbing high load on our bridge node since 8:00 AM this morning:
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/7e57b377-136a-485f-becd-eabf7f388fb2)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/f3c8056b-6d23-4361-97ac-98bba407018c)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/780bc4ba-20d9-4c77-9585-543bc3323ccd)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/726389f4-abc9-4af4-9e5d-7452005131fc)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/01a89084-c050-45e6-96f5-e721cb2ffb38)

**Comment by ramin** [comment]
@JB273 checking in on this, is the load still heavy? What are you seeing

**Comment by JB273** [comment]
@ramin @renaynay It looks OK now on mainnet, will check testnet, but the testnet one never had an issue...
So I think we can close this issue for now with this update, wdyt?

![image](https://github.com/celestiaorg/celestia-node/assets/54506968/ddc58635-3a94-44b2-ae4c-90bc3e4305d5)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/489f6190-6dad-459d-8df9-6d99c6036693)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/30538980-8c8c-414f-b65a-1b8d0c47101b)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/3b32aa6f-b8f0-4132-95a5-4387b8b201d3)
![image](https://github.com/celestiaorg/celestia-node/assets/54506968/b808e2bf-40af-4bc7-8240-98bcaea7f871)

**Comment by ramin** [comment]
I think we are safe to close. I KNOW we had an impromptu "inscriptions load test" happen around that time 😆, which might be the explanation....
