### ISSUE TITLE
v0.12.4 consumes 8GB RAM on startup after building with or without jemalloc on production grade server

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3107]
### Celestia Node version

v0.12.4

### OS

ubuntu, production grade server

### Steps to reproduce it

Run light node

### Expected result

Syncs using under [500 MB RAM as per documentation](https://github.com/celestiaorg/docs/blob/8516257429d8618aa28d33298ee624b38329e2ae/nodes/light-node.md?plain=1#L30)

### Actual result

Uses 8GB RAM on startup, with and without jemalloc

### Notes

Originally reported in celestia-da https://github.com/rollkit/celestia-da/issues/35#issuecomment-1894255938

**Comment by jcstein** [comment]
cc @tuxcanfly and @mycodecrafting for visibility on the issue

**Comment by mycodecrafting** [comment]
some added info.

OS:  Ubuntu 20.04.6 LTS
Arch type:  x86_64

Build and install following guide here:  https://docs.celestia.org/nodes/celestia-node

Go version:  go1.21.1 linux/amd64

celestia built version
```
Semantic version: v0.12.4
Commit: 8e5a71746bc9bd9300ad3e4853797e64fdd1d018
Build Date: Tue 16 Jan 2024 08:26:39 PM UTC
System version: amd64/linux
Golang version: go1.21.1
```

**Comment by tuxcanfly** [comment]
Attaching heap snapshots from @mycodecrafting collected at 1m intervals.

[heap-snapshots.tar.gz](https://github.com/celestiaorg/celestia-node/files/13966322/heap-snapshots.tar.gz)

**Comment by jcstein** [comment]
from @mycodecrafting: Ubuntu server and mem usage on celestia-node has grown to 18.6G overnight

**Comment by Wondertan** [comment]
Does this run over an clean node or synced node?
