### ISSUE TITLE
fix(node): Log node p2p information to stderr as well so docker runners can see it

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#3109]
When the node starts up, we print p2p information of the node [here](https://github.com/celestiaorg/celestia-node/blob/main/nodebuilder/node.go#L124-L128). 

We should also log out to stderr so docker container users can see it.

**Comment by MuhtasimTanmoy** [comment]
Would like to work on it.

**Comment by AbhinavMir** [comment]
Hi @renaynay ! Wondering if you had a chance to look at my PR!

Thx.

**Comment by vgonkivs** [comment]
Closed until there will be complains
