### ISSUE TITLE
metrics(blob): Add trace paths through blob module to trace Read paths

### ISSUE THREAD

**Issue by ramin** [celestiaorg/celestia-node#3112]
There have been some loose reports of "reads being slow". Though this is vague, a first step is to add traces to the blob module read codepath. 

Then we can use a testing tool (such as waypoint) to perform many reads and see what traces are emitted

success:

- blob module read paths are instruments with traces
- potentially add some timing metrics too

**Comment by Wondertan** [comment]
@vgonkivs and @ramin, can we say it's closed or not?
