### ISSUE TITLE
Facing issue while trying to setup  Celestia node using docker

### ISSUE THREAD

**Issue by Swornatoya** [celestiaorg/celestia-node#3134]
Steps followed to setup the node:

1. export NETWORK=celestia
2. export NODE_TYPE=light
3. export RPC_URL=celestia.rpc.stakin-nodes.com
4. sudo docker run -e NODE_TYPE=$NODE_TYPE -e P2P_NETWORK=$NETWORK -v /**/node-celestia/data:/home/celestia ghcr.io/celestiaorg/celestia-node:v0.12.4 celestia $NODE_TYPE start --core.ip $RPC_URL --p2p.network $NETWORK

Initially the node started and ended up with the error as:

> 2024-01-22T13:36:35.671Z INFO badger v4@v4.0.0-20231125230536-2b9e13346f75/db.go:625
> Level 0 [ ]: NumTables: 00. Size: 0 B of 0 B. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 16 MiB
> Level 1 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level 2 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level 3 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level 4 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level 5 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level 6 [B]: NumTables: 01. Size: 185 KiB of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
> Level Done
> 
> Error: node: failed to start within timeout(20s): context deadline exceeded

When I try starting the node again with the same command, I am getting the below error:

> 2024-01-22T15:02:13.851Z INFO node nodebuilder/init.go:31 Initializing Full Node Store over '/home/celestia/.celestia-full'
> 2024-01-22T15:02:13.852Z INFO node nodebuilder/init.go:63 Saved config {"path": "/home/celestia/.celestia-full/config.toml"}
> 2024-01-22T15:02:13.852Z INFO node nodebuilder/init.go:65 Accessing keyring...
> 2024-01-22T15:02:13.855Z WARN node nodebuilder/init.go:194 Detected plaintext keyring backend. For elevated security properties, consider using the file keyring backend.
> 2024-01-22T15:02:13.857Z INFO node nodebuilder/init.go:72 Node Store initialized
> 
> Starting Celestia Node with command:
> celestia full start --core.ip celestia-rpc.brightlystake.com --p2p.network celestia
> 
> 2024-01-22T15:02:13.927Z INFO node nodebuilder/module.go:25 Accessing keyring...
> 2024-01-22T15:02:13.932Z INFO module/state state/keyring.go:40 constructed keyring signer {"backend": "test", "path": "/home/celestia/.celestia-full/keys", "key name": "my_celes_key", "chain-id": "celestia"}
> Error: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".ConstructModule.Listen.func2 (/src/nodebuilder/p2p/addrs.go:13): failed to build host.Host: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".routedHost (/src/nodebuilder/p2p/host.go:27): failed to build p2p.HostBase: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".host (/src/nodebuilder/p2p/host.go:32): failed to build peer.ID: could not build arguments for function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".id (/src/nodebuilder/p2p/identity.go:45): failed to build crypto.PrivKey: received non-nil error from function "github.com/celestiaorg/celestia-node/nodebuilder/p2p".Key (/src/nodebuilder/p2p/identity.go:17): keystore: permissions of key 'p2p-key' are too relaxed: required: 0600, got: 0777

**Comment by ramin** [comment]
@Swornatoya i see a `keystore: permissions of key 'p2p-key' are too relaxed: required: 0600, got: 0777` there in those error logs, did you get around this? Feel free to re-open if not

**Comment by Swornatoya** [comment]
@ramin : Could you please let me know what changes I need to resolve this
