### ISSUE TITLE
[Feature Request][core]: load balance core endpoints

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/celestia-node#3151]
### Implementation ideas

Currently we accept a single `core.rpc.endpoint/core.grpc.endpoint`. It would be ideal to allow a list of core endpoints to be configured such that the node can load balance between them to minimise the risk of transaction failure.

**Comment by distractedm1nd** [comment]
I will do this on top of #3153 rn

**Comment by distractedm1nd** [comment]
But architecturally, it does not make sense at all for node to be doing the load-balancing. Traditionally the load balancing is taken care of up the stack. But I will implement quickly anyways to show what it would look like

**Comment by Wondertan** [comment]
>  it does not make sense at all for node to be doing the load-balancing.
Absolutely.

**Comment by ramin** [comment]
closing as load balancing not a concern of node itself
