### ISSUE TITLE
Why two distinct commands to install binary?

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#3169]
## Context

Step 4 of https://docs.celestia.org/nodes/celestia-node#install-celestia-node shows that the install command differs for Mac and Ubuntu. 

Platform | Command | Notes
--- | --- | ---
Mac | `make go-install` | Uses [`go install`](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) to put binary in $GOPATH/bin (if GOPATH is set) or $HOME/go/bin (if GOPATH is not set)
Ubuntu | `make install` | Uses [`install`](https://en.wikipedia.org/wiki/Install_(Unix)) to put binary in `/usr/local/bin`

## Question

I'm wondering why? A prerequisite to this page is the [development environment](https://docs.celestia.org/nodes/environment) steps which instruct users to Install Go and configure PATH to include:
1. `/usr/local/go/bin`
2. `$HOME/go/bin`

So it seems to me like we only need to support the Go install command. Concretely, on a Linux machine, I can do:

```
root@rootulp-mocha:~/celestia-node# make go-install
--> Installing Celestia

root@rootulp-mocha:~/celestia-node# which celestia
/root/go/bin/celestia

root@rootulp-mocha:~/celestia-node# celestia version
Semantic version: v0.12.4
Commit: 8e5a71746bc9bd9300ad3e4853797e64fdd1d018
Build Date: Wed Feb  7 15:02:52 UTC 2024
System version: amd64/linux
Golang version: go1.21.6
```

## Proposal

1. Remove the existing `make install` command.
2. Alias the existing `make install` command to do the same as `make go-install`.

**Comment by Wondertan** [comment]
It exists to support two ways of installing the binary. The native go way and native linux way which doesn't rely on `GOBIN`. It might be not documented well enough, but we should keep two ways.

Personally, I never use go-install and only install.

Another option I see is to unify them into one `install` directive  and check for `GOBIN` presence which will define the path. Remember that `go install` is basically `go build; mv`

**Comment by rootulp** [comment]
Personally, I always try to use `make install` and hit an error:

```
$ make install
--> Installing Celestia
install: ./build/celestia -> /usr/local/bin//celestia
install: -t: No such file or directory
make: *** [install] Error 71
```

Then I recall that I'm supposed to use `make go-install`. It's minor but I wonder if other developers encounter the same friction. I like your idea of unifying them into one `make install` command. The unified `make install` could check for `GOBIN` (like you said) and/or the platform that the user is on and then delegate to the current implementations based on that info. Defer to ya'll

**Comment by jcstein** [comment]
> It exists to support two ways of installing the binary. The native go way and native linux way which doesn't rely on GOBIN. It might be not documented well enough, but we should keep two ways.

i think [it is clearly documented in Celestia docs](https://github.com/celestiaorg/docs/blob/7c1985ceab2732bc4531ad294955ced43584c1cc/nodes/celestia-node.md?plain=1#L74-L86), if you all think this needs to be more clear let me know. also, thinking maybe it could be better documented in celestia-node itself?

**Comment by Wondertan** [comment]
@jcstein, i meant to document better n celestia-node side, docs are good imo
