### ISSUE TITLE
bug: Proofs are serialized as strings - undocumented API break in 0.13.0

### ISSUE THREAD

**Issue by zvolin** [celestiaorg/celestia-node#3173]
### Celestia Node version

0.13.0

### OS

archlinux

### Steps to reproduce it

In #3146 change, the Proof serialization changed from a list of proof objects to the list of stringified objects. This is a breaking change for the RPC clients. Is this new behavior expected and should clients like [rust celestia-rpc](https://github.com/eigerco/lumina/tree/main/rpc) align to it?

My 2 cents is that previous API is cleaner, the string serialization seems rather unnecessary

### Expected result

.

### Actual result

.

**Comment by zvolin** [comment]
You can see the difference in
https://node-rpc-docs.celestia.org/?version=v0.12.4#blob.GetProof
and 
https://node-rpc-docs.celestia.org/?version=v0.13.0#blob.GetProof

**Comment by zvolin** [comment]
I've just noticed that this also is inconsistent with other rpc methods, like `GetSharesByNamespace` which will still return the old proof representation (json object)

**Comment by ramin** [comment]
@zvolin yes i don't think this was intentional, let me chase and discuss with team and i think we'll have to change

**Comment by ramin** [comment]
@renaynay here is the culprit https://github.com/celestiaorg/celestia-node/commit/625cdf3b1f31afe5371cca8c355d59a572ae6ea6#diff-e0265c8a8ef591c5dac3ccd849803c7c79932ed3b87bff256fdf9f291611ace4R38

i believe we just need to remove this custom Marshall/Unmarshal and we'll be back to original behavior

**Comment by renaynay** [comment]
@zvolin does #3204 revert proof marshalling to how it was done previously?

**Comment by zvolin** [comment]
yup, all our tests passes on that

**Comment by renaynay** [comment]
Perfect
