### ISSUE TITLE
[Feature Request]: `blob_get_all` could return empty `Vec` on "blob not found"

### ISSUE THREAD

**Issue by bkolad** [celestiaorg/celestia-node#3192]
### Implementation ideas

The `blob_get_all` RPC method yields a `Result<Vec<Blob>, Error>`. When no blobs are published under a specified namespace and height, I am getting the forllowing error: 

`error is: ErrorObject { code: ServerError(1), message: "getting blobs for namespace(00000000000000000000000000000000000000736f762d746573742d70): blob: not found\nblob: not found", data: None }`.

Missing blobs feels more like a standard scenario rather than an error.  Currently there is no clean way to distinguish between a missing blob or some other HTTP error, as we can't pattern match on `ErrorObject`. I think it would be more appropriate to return an empty `Vec` in this case.

version: `celestia-node:v0.12.0`

**Comment by jcstein** [comment]
thanks for the issue @bkolad!

**Comment by renaynay** [comment]
cc @tuxcanfly 

had similar concerns

**Comment by ramin** [comment]
cc @vgonkivs

**Comment by Wondertan** [comment]
This makes sense for the `GetAll`. The other methods should still return the error
