### ISSUE TITLE
bug: no flag found on v0.13.0 for `--rpc.skip-auth` or `--rpc.disable-auth`

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3193]
### Celestia Node version

v0.13.0

### OS

macOS

### Install tools

docs

### Steps to reproduce it

try to use either `--rpc.skip-auth` or `--rpc.disable-auth`

### Expected result

it should disable auth

### Actual result

<img width="1082" alt="Screenshot 2024-02-20 at 9 38 35 AM" src="https://github.com/celestiaorg/celestia-node/assets/46639943/7794478e-5823-4868-b5c5-2e628f0e57a6">
<img width="1111" alt="Screenshot 2024-02-20 at 9 37 40 AM" src="https://github.com/celestiaorg/celestia-node/assets/46639943/4fc25ccf-7a43-4bd2-8c66-c1538f68a48a">

### Relevant log output

```Shell
Error: unknown flag: --rpc.skip-auth
Usage:
  celestia das sampling-stats [flags]

# and

Error: unknown flag: --rpc.disable-auth
Usage:
  celestia das sampling-stats [flags]
```

### Notes

How does a user skip auth if the node store must be specified to tell which chain it is specific to? Does celestia-node know which network is running and will refer to that data store for the network?

I wasn't sure which flag to use, because [the issue summary says "New flag: `--rpc.skip-auth`"](https://github.com/celestiaorg/celestia-node/pull/3117#issue-2092064717) and [the release notes say "feat!(rpc): rpc.disable-auth flag by @ distractedm1nd in https://github.com/celestiaorg/celestia-node/pull/3117"](https://github.com/celestiaorg/celestia-node/releases/tag/v0.13.0)

**Comment by ramin** [comment]
@jcstein I see how this is confusing and had to stop and think myseld. 

as currently implemented, `--rpc.skip-auth` is a flag provided ONLY when starting the node, ie:

`celestia light start --rpc.skip-auth` 

Then the [verifyAuth middleware](https://github.com/celestiaorg/celestia-node/blob/ec978ec8e378ee6e75ae54dde61e61f52beb7c43/api/rpc/server.go#L55) for RPC will skip validating the provided auth token in the request header. This was introduced as a request to support programmatic access without managing auth tokens. The cli (as would any sdk client) remains unaware if a server was started with auth skipped. So, in this case, you could provide anything as token, ie:

- start a server with `--rpc.skip-auth`
- run a cli rpc command like `celestia p2p info --token LOLWHUT` 

and it'd be accepted
