### ISSUE TITLE
Investigate the implications of the client choosing whether to sample from row or column

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#3198]
In the [fraud proofs paper](https://arxiv.org/abs/1809.09044), the client picks the (x, y) co-ordinates, but the node decides whether to return a response from the row or column root.

In the [current implementation](https://github.com/lazyledger/lazyledger-core/pull/270/files#diff-5c955aa55be1fcf69650e175217cd038dc552b1b3ee428e458679b0005810b2cR37), the client also decides whether the response should be from a row or column root.

We should consider the security implications to this if, any.

**Comment by Wondertan** [comment]
We made make it secure, but its inefficient. Really, the client shouldn't care how their shares are proved. As long as they are proven, dasing works. This will be changed to the way its described in the paper via #2971, so closing this investigation issue.
