### ISSUE TITLE
I want to get in touch with Rene from your team

### ISSUE THREAD

**Issue by a941249849** [celestiaorg/celestia-node#3217]
I want to get in touch with rene, but I didn't find an effective way on his profile page, so I want to try this way. Please forgive me for being reckless.

**Comment by mindstyle85** [comment]
@renaynay

**Comment by renaynay** [comment]
@a941249849 What is this regarding?

**Comment by a941249849** [comment]
@renaynay Hello Rene.

I would like to ask you about code and some personal matters. Could you please tell me what time is convenient and what email address can I contact you by? Or any way that is convenient for you

**Comment by renaynay** [comment]
If it's regarding code, I'd prefer to discuss here, thank you.

**Comment by a941249849** [comment]
@renaynay It is about some personal matters of mine. Of course, this matter also includes GitHub matters, so if possible I would like to send you an email to explain.

I saw your profile and I'm sorry to bother you but I had to do it because it's very important to me
My email is: a941249849@gmail.com
If you are concerned about your privacy, can you send me an email? please

**Comment by renaynay** [comment]
You can send an email here if it's urgent: civapo5625@gexige.com

**Comment by ramin** [comment]
gonna close this
