### ISSUE TITLE
[Feature Request]: Ability to Change Node's Listen Port

### ISSUE THREAD

**Issue by gaia** [celestiaorg/celestia-node#3230]
### Implementation ideas

It doesn't seem possible to change the P2P port for the node. Updating config.toml's `ListenAddresses` does affect the port which it listens on.

As seen in https://github.com/celestiaorg/celestia-node/blob/f2b664f3abe5e76ed51e19305aa3489980a93692/nodebuilder/p2p/config.go#L43, the port is hardcoded.

Will this change at some point?

**Comment by Wondertan** [comment]
That's the default config hardcoded and this feature is implemented. You should be able to change the port by changing the config after your node is initialized. If that's not the case, it means there is a bug. 

Please provide the logs of your nodes after changing the config. The logs should contain the addresses your node listens to. If they don't change, we make this issue a bug.

**Comment by gaia** [comment]
> That's the default config hardcoded and this feature is implemented. You should be able to change the port by changing the config after your node is initialized. If that's not the case, it means there is a bug.
> 
> Please provide the logs of your nodes after changing the config. The logs should contain the addresses your node listens to. If they don't change, we make this issue a bug.

I updated the config to 2131 and restarted the node. it's logs & netstat state it's listening on 2121.

**Comment by ramin** [comment]
hi @gaia i just spent a minute trying to investigate and reproduce this from current main and could not recreate. It appears changing all entries in the config for listen port behaves correctly (from inspecting logs etc) and viewing connections via netstat.

@gaia I'd make sure that under the config.toml you update all entries in P2P ListenAddresses
