### ISSUE TITLE
[Feature Request]: Support broadcast mode selection

### ISSUE THREAD

**Issue by ALPAC-4** [celestiaorg/celestia-node#3241]
### Implementation ideas

I'm utilizing Celestia's light node on the Mocha testnet to execute the SubmitPayForBlob method. However, when I use this method with the light node RPC, I often encounter delays in transaction processing, resulting in the error message `timed out waiting for tx to be included in a block.` Nevertheless, the transaction eventually gets included in a block approximately a minute later. This error occur when using [block mode](https://github.com/celestiaorg/celestia-node/blob/32bc7a973b2f0b730c8ec1c2f7d6be5e5484e85b/state/core_access.go#L234).

To retrieve blob data, celestia require the height at which the transaction was included. However, receiving an error message makes it challenging to obtain this height. Therefore, I propose allowing users to choose the broadcast mode. By incorporating a sync mode, users can obtain the transaction hash and subsequently poll the transaction using the hash to retrieve the height once the transaction is included in a block.

**Comment by renaynay** [comment]
Thanks @ALPAC-4, we have a duplicate issue here for this: https://github.com/celestiaorg/celestia-node/issues/2430

Will close for now and bump priority on the original.
