### ISSUE TITLE
gcc: fatal error: cannot read spec file ‘./specs’: Is a directory

### ISSUE THREAD

**Issue by 0mustafasevinc0** [celestiaorg/celestia-node#3272]
### Celestia Node version

v0.13.1

### OS

Linux Mint 20.1

### Steps to reproduce it

$ ver="1.21.1"
$ cd $HOME
$ wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
$ sudo rm -rf /usr/local/go
$ sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
$ rm "go$ver.linux-amd64.tar.gz"
$ echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
$ source $HOME/.bash_profile
$ cd $HOME
$ rm -rf celestia-node
$ git clone https://github.com/celestiaorg/celestia-node.git
$ git checkout tags/v0.13.1
$ make build

### Expected result

well done

### Actual result

go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.2
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.46.1
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.46.1
go: downloading golang.org/x/time v0.5.0
github.com/celestiaorg/celestia-node/cmd/celestia
/home/walue/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.0.linux-amd64/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
gcc: fatal error: cannot read spec file ‘./specs’: Is a directory
compilation terminated.

make: *** [Makefile:38: build] Error 1

**Comment by ramin** [comment]
@0mustafasevinc0 i spent some time trying to recreate this on a fresh box (though not linux mint) and didn't run into similar issues. My guess is

- there is some config in you go toolchain and how you set that up that is incorrect
- some config in your profile that is potentially setting some GCC flag override

Can you try with latest and verify your go installation is correct and see if things work. Also, ensure you are on go 1.22 going forward. Let me know if you still have issues
