### ISSUE TITLE
refactor: Consolidate SHA-256 Hash Function Usage

### ISSUE THREAD

**Issue by walldiss** [celestiaorg/celestia-node#3275]
### Implementation ideas

The Celetia node codebase currently defines the SHA-256 hashing constructor using `sha256.New()` in multiple locations. To eliminate redundancy and ensure consistency, we need to centralize the definition of this hashing constractor within the `share` package.

**Comment by kien6034** [comment]
Hi, can anyone assign me to this issue. I've already had a PR open for it
