### ISSUE TITLE
Add a flag to `share get-by-namespace` to ignore padding

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#3282]
## Context

Originally surfaced by Rohan at Sovereign Labs. Currently `celestia share get-by-namespace` returns all the shares in a namespace including [namespace padding shares](https://celestiaorg.github.io/celestia-app/specs/shares.html#namespace-padding-share). 

## Problem

It's extremely unlikely that clients actually want to download namespace padding shares. They exist so that subsequent blobs in the data square are placed at the correct index. Namspace padding shares aren't helpful for users interested in the namespace that is being queried.

## Proposal

Options:
1. [not breaking] add an option to the share get-by-namespace like `ignorePadding: bool`. If the flag isn't provided, default to false to preserve the existing API behavior. In a subsequent major version, default the flag to true because most users aren't interested in namespace padding shares.
2. [breaking] remove namespace padding shares from the response of get shares by namespace

**Comment by Wondertan** [comment]
Makes sense. I think we should go even deeper and optimize this on the p2p protocol level so that we never carry around bogus data. We would need some logic to detect and auto-append necessary padding so we can verify inclusion in-place and stateless(is this possible @rootulp ?)
cc @walldiss

**Comment by rootulp** [comment]
@preston-evans98 shared that Sovereign labs needs to generate completeness proofs so they wouldn't actually use this enhancement. We probably shouldn't prioritize this issue unless we get feedback from other teams that it's important for them.

@Wondertan I don't understand the proposed optimization so I can't comment if that's feasible.

**Comment by Wondertan** [comment]
I confirmed with @rootulp that it's possible to make this optimization. Shares in get-by-namespace contains blobs where each blob's first share has information on padding shares that can be trimmed and later on generated on the client side. 

Alternatvely or on top, we may use a compression algorithm

**Comment by rootulp** [comment]
> where each blob's first share has information on padding shares

I think this is misleading. Each blob's first share only contains information about how long that blob spans. In the [specs](https://celestiaorg.github.io/celestia-app/specs/shares.html) we call this the sequence length. A blob's share doesn't contain any information about the N namespace padding shares that may exist after the blob in the data square.

**Comment by rootulp** [comment]
Closing as won't do for now. We can re-open if other users request this feature.
