### ISSUE TITLE
feegrant/state: Light node's celestia account can't pass fees to the granter

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#3284]
### Celestia Node version

v0.13.1

### OS

linux/mac

### Steps to reproduce it

Go through this tutorial https://github.com/celestiaorg/docs/pull/1500

### Expected result

Fees are charged from the granter account

### Actual result

The light node's account is still paying for fees itself

**Comment by jcstein** [comment]
`ERROR` in logs of successful feegrant transaction and revoke. [see comments](https://github.com/celestiaorg/docs/pull/1500/#issuecomment-2065551407)

**Comment by ramin** [comment]
@vgonkivs is this still relevent given the work completed for #3256 ?

**Comment by vgonkivs** [comment]
All changes were done in https://github.com/celestiaorg/celestia-node/issues/3256

This one can be closed.
