### ISSUE TITLE
service/header: Should `CoreListener` be tracked inside of header `Service` struct?

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#330]
```
// TODO @renaynay: how will we register core listener on the header Service? It's a part of header service but
// 	we can't pass it directly to constructor b/c only Bridge nodes provide CoreListener, otherwise it'll always be nil
// 	maybe we can make it an interface? Still hacky.

```

saving this comment here ^ 

---------------------------------------------------------------------------
I think the main issue is that all other header sub-services are passed to the header service and contained there while this sub-service is its own special case and is just delegated to the DI app to manage its lifecycle, and isn't tracked anywhere else.

_Originally posted by @renaynay in https://github.com/celestiaorg/celestia-node/pull/327#discussion_r780228291_

**Comment by Wondertan** [comment]
No, unless we need to access it in runtime and control anyhow.
