### ISSUE TITLE
[Feature Request]: improve example api values as they are not realistic

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3317]
# summary

gas of “42” is not realistic, etc

### Implementation ideas

moving over https://github.com/celestiaorg/node-rpc-docs/issues/32 as the changes need to happen here, and will then be imported into the node-rpc-docs

**Comment by ramin** [comment]
after a bit of work on docgen, realizing there's no way to override single input values in an RPC calls without forking docgen and doing quite a bit of work, then discussing with @jcstein and @distractedm1nd it was determined that a) the improvements they are making to docs are good enough b) medium term, the reflection based automatic docgen was a nice start, but we need something better for docs that allows more specific input. Also, the work by the interfaces wg regarding a canonical API may well supersede JSON-RPC as the de facto developer interface for building. So, with @jcstein's blessing we will close this
