### ISSUE TITLE
`make install` should not use `go install`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#332]
Even though it is simple to use `go install`, it requires the person building the Node from scratch to set the GOBIN for this to work reliably, thus to build the Node locally, one has to be aware of Go's semantics. 

I propose to avoid this by making `make install` not to rely on `go install`, but to `cp` the results from `make build` to `/usr/local/bin` which may require the user's `sudo` permissions. Furthermore, we should use built-in GNU `install` instead of `cp`.

**Comment by Wondertan** [comment]
Another solution might be to check if GOBIN is set and if not - set it to `/usr/local/bin` for the user.

**Comment by totallymystic** [comment]
Is this the reason why I'm getting this error
`--> Installing Celestia
build github.com/celestiaorg/celestia-node/cmd/celestia: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
make: *** [Makefile:20: install] Error 1
`

**Comment by marbar3778** [comment]
This is a documentation issue imo. Users can download or build on their own.

**Comment by Wondertan** [comment]
@totallymystic, no, this issue is unrelated. Pls make another one if still relevant.
