### ISSUE TITLE
service/share: Remove `Availability` from `ShareService` params as it's unnecessary

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#335]
TODO: 
- [ ] remove availability from params of `NewShareService`
- [ ] remove any kind of Availability from bridge node components. Light node needs LightAvail, and full node needs FullAvail

**Comment by renaynay** [comment]
@Wondertan I am rethinking whether this issue makes sense after we implement the public API. The only reason I'm asking is because current `ShareModule` proposed is: 

```go
type SharesModule interface {
	GetShare
	Get
	GetByNamespace
	IsAvailable
	Submit
}
```

`IsAvailable()` would require `share.Service` to keep `Availability`. 

So I guess the question is, are we going to merge `daser` into `ShareModule`? In that case, it would make sense to keep `IsAvailable` as part of `ShareModule` and to keep `Availability` inside `share.Service`, but if we have a `SamplingModule`, then maybe it would make sense to keep `IsAvailable` in the sampling module instead? And then `ShareModule` would only have `Get/Submit` methods for shares.

WDYT?

**Comment by Wondertan** [comment]
`DASer/Sampler` or else relies on `ShareService/Module.IsAvailable`.

Checkout [the comment](https://github.com/celestiaorg/celestia-node/pull/506#discussion_r821646082). By it, I also meant to move DASer into `share` pkg, so it turns into `share.Sync`, which is arguable, and I am already kinda used to daser. Public API is currently outlined with DASModule in mind, which will only provide DASState to the outside right now.

**Comment by renaynay** [comment]
I like the separation of the `daser` from everything else tbh. It's super simple and if people want to find it, it's easy to find/understand for the most part how it works. It's also the "coolest" part of our codebase (arguably) 😄  

For public API of `daser`, I will leave some comments on the open PR.

**Comment by Bidon15** [comment]
Irrelevant due to current implementation of the RPC
