### ISSUE TITLE
`blob.NewBlob` will reject > 2 MB blobs even if the square size is increased

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#3356]
## Context
celestia-node enforces a max blob size of 1.97 (1974272 bytes) [here](https://github.com/celestiaorg/celestia-node/blob/e9026800ed67859deb0a4f31e832a4586bee1d45/blob/blob.go#L93-L95).

## Problem
If governance votes to allow 8MB blocks via bumping:
- `consensus.block.MaxBytes` to 8MiB
- `blob.GovMaxSquareSize` to 128

then celestia-node will reject blobs that could theoretically fit inside a block.

## Question

Is the max blob size check  [here](https://github.com/celestiaorg/celestia-node/blob/e9026800ed67859deb0a4f31e832a4586bee1d45/blob/blob.go#L93-L95) necessary? 
- If no, can we remove it and rely on error handling from consensus nodes?
- If yes, can it be made aware of the governance params and infer a max blob size based on them? 

Tangent: I think it's quite complex to determine what is the max possible blob size that is submittable on Celestia b/c it depends on a number of parameters that can be changed up or down. We may consider adding an explicit constraint on the max blob size (i.e. 1 MiB) to make checks like this stateless.

**Comment by jcstein** [comment]
Isn't this max blob size bigger than `consensus.block.MaxBytes | 1.88MiB` set in [celestia-app mainnet parameters](https://arc.net/l/quote/tkrodtcj)?

**Comment by rootulp** [comment]
1974272 bytes == 1.88 MiB but the params in the specs should be updated to use the exact byte value to make that clearer.

**Comment by renaynay** [comment]
@rootulp if governance votes to increase or decrease the Max blob size, would that const (`DefaultMaxBytes`) get updated in the app version? If so, node just needs to import the upgrade and it will automatically adjust to the new value (which is why we point to the app const to begin with). 

Please confirm if this is the case. If not, then we can decide how to proceed.

**Comment by rootulp** [comment]
> @rootulp if governance votes to increase or decrease the Max blob size, would that const (DefaultMaxBytes) get updated in the app version?

No it would not. `DefaultMaxBytes` is the initial value (i.e. the default) for the param. Governance can modify it _without_ a code change to `DefaultMaxBytes` in celestia-app.

**Comment by renaynay** [comment]
Okay good to know @rootulp

**Comment by renaynay** [comment]
Hey @rootulp -- is this still relevant? Aren't we hard capping the max blob size anyway ?

**Comment by jcstein** [comment]
I think it is, at least based on [CIP-28](https://cips.celestia.org/cip-28.html#specification): "Transaction size is limited to 2MiB by setting the versioned parameter MaxTxSize to 2097152"

**Comment by rootulp** [comment]
I think we should remove the blob size check in celestia-node all together because it doesn't necessary. The check was added in [this PR](https://github.com/celestiaorg/celestia-node/pull/2388/files#diff-e0265c8a8ef591c5dac3ccd849803c7c79932ed3b87bff256fdf9f291611ace4R120-R122) but `DefaultMaxBytes` is not appropriate to use because that constant applies to something else:

```go
// DefaultMaxBytes is the default value for the governance modifiable
// maximum number of bytes allowed in a valid block.
DefaultMaxBytes = DefaultGovMaxSquareSize * DefaultGovMaxSquareSize * share.ContinuationSparseShareContentSize
```

There is currently no defined max blob size limit. It is inferred based on other parameters.
