### ISSUE TITLE
Blobstream API should be moved to node

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#3361]
> Proofs for Blobstream (DataRootInclusionProof and ProveShare endpoints on core) are not accessible through node API, so currently all integrations with Blobstream require one to have two endpoints, and two APIs.

related: https://github.com/celestiaorg/celestia-core/issues/1306

**Comment by rach-id** [comment]
Referencing this PR here: https://github.com/celestiaorg/blobstream-node-api/pull/1
