### ISSUE TITLE
[Feature Request]: Document about how to compute `SharePointer` after submitting data to celestia?

### ISSUE THREAD

**Issue by zhiqiangxu** [celestiaorg/celestia-node#3363]
### Implementation ideas

[Here](https://github.com/CryptoKass/blobstreamx-example/blob/main/main.go) is the example to use blobstream, which is pretty nice.

But as can be seen, the `SharePointer` is [hardcoded](https://github.com/CryptoKass/blobstreamx-example/blob/b432a67b2f900543522cb52ec2c1b75516b914e6/main.go#L36).

How should one compute `SharePointer` after submitting a tx(containing blobs in my case) on celestia?

**Comment by ramin** [comment]
@rach-id

**Comment by rach-id** [comment]
Hello 👋 
To prove the PFB transaction shares: https://docs.celestia.org/developers/blobstream-proof-queries#transaction-inclusion-proof-using-the-transaction-hash
To prove the PFB blob shares: https://docs.celestia.org/developers/blobstream-proof-queries#blob-inclusion-proof-using-the-corresponding-pfb-transaction-hash
To prove a specific range: https://docs.celestia.org/developers/blobstream-proof-queries#specific-share-range-inclusion-proof

Currently, querying the proofs is done using an RPC endpoint and not a Celestia node. However, we will be working on supporting that in node in the upcoming months.

**Comment by zhiqiangxu** [comment]
Hey @rach-id @ramin 

Thanks a lot for the detailed answer, now I see how to query for proofs by a PFB transaction hash:)

What about the finality of celestia, after submitting a tx to celestia, how long can one consider it finalized?

**Comment by rach-id** [comment]
After the transaction is included in a block, it's considered final. There are no reorgs in Celestia.
