### ISSUE TITLE
Error in the path when restoring the light node wallet

### ISSUE THREAD

**Issue by itrocket-team** [celestiaorg/celestia-node#3365]
### Celestia Node version

v0.13.4

### OS

ubuntu 22.04

### Steps to reproduce it

~~~
cd ~/celestia-node
./cel-key add my_celes_key --keyring-backend test --node.type light --recover
~~~

### Expected result

The key should be restored in `~/.celestia-light-mocha-4/`, but the keys are being written to a different directory, `~/.celestia-light`, so the node does not detect them. Adding the `home` flag with the exact path specified also does not solve the problem

### Actual result

~~~
cellight@reliable3:~/.celestia-light$ tree
.
└── keys
    └── keyring-test
        ├── 034d5601c0f06bb3ccecc5fab63ac2f60519196a.address
        └── my_celes_key.info
        ~~~

**Comment by renaynay** [comment]
@itrocket-team Can you please try again and add the `--p2p.network mocha` flag please and see if this resolves the issue?

**Comment by itrocket-team** [comment]
Oh, yes. Using the `--p2p.network mocha` flag, everything works fine. Its my mistake, sorry
