### ISSUE TITLE
cannot require "github.com/celestiaorg/celestia-node v0.13.4" in go project

### ISSUE THREAD

**Issue by phpxin** [celestiaorg/celestia-node#3375]
### Celestia Node version

v0.13.4

### OS

osx

### Install tools

go mod

### Steps to reproduce it

* add "github.com/celestiaorg/celestia-node v0.13.4" to go.mod 

* use "go mod tidy"
* the error below will show
```bash
go: code.****.io/****/commands imports
	github.com/celestiaorg/celestia-node/api/rpc/client imports
	github.com/celestiaorg/celestia-node/nodebuilder/blob imports
	github.com/celestiaorg/celestia-node/blob imports
	github.com/tendermint/tendermint/proto/tendermint/types: reading github.com/tendermint/tendermint/go.mod at revision v0.34.29: unknown revision v0.34.29
```

### Expected result

no error with "go mod tidy"

### Actual result

go: code.****.io/****/commands imports
	github.com/celestiaorg/celestia-node/api/rpc/client imports
	github.com/celestiaorg/celestia-node/nodebuilder/blob imports
	github.com/celestiaorg/celestia-node/blob imports
	github.com/tendermint/tendermint/proto/tendermint/types: reading github.com/tendermint/tendermint/go.mod at revision v0.34.29: unknown revision v0.34.29

### Relevant log output

```Shell
go: code.****.io/****/commands imports
	github.com/celestiaorg/celestia-node/api/rpc/client imports
	github.com/celestiaorg/celestia-node/nodebuilder/blob imports
	github.com/celestiaorg/celestia-node/blob imports
	github.com/tendermint/tendermint/proto/tendermint/types: reading github.com/tendermint/tendermint/go.mod at revision v0.34.29: unknown revision v0.34.29
```

### Notes

When I review "https://pkg.go.dev/github.com/tendermint/tendermint?tab=versions", I fount there are no version "v0.34.29"

**Comment by ramin** [comment]
hi @phpxin 

i know it's less than ideal, but you need set up some replaces in your go.mod to import client directly easily, see https://github.com/celestiaorg/celestia-node/blob/main/go.mod#L343

Or for an example of using client directly https://github.com/ramin/celestia-rpc-base

**Comment by ramin** [comment]
@phpxin let me know if you have further issues i can help you get set up
