### ISSUE TITLE
bug: `"result": "RPC client error: sendRequest failed: http status 401 Unauthorized unmarshaling response: EOF"` on querying account-address

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3384]
### Celestia Node version

v0.13.5

### OS

macOS

### Install tools

docs

### Steps to reproduce it

1. run a light node with state access using `celestia light start --p2p.network arabica --core.ip validator-1.celestia-arabica-11.com`
2. try to query the account address with `celestia state account-address --node.store $HOME/.celestia-light-arabica-11`
3. receive result:
```json
{
  "result": "RPC client error: sendRequest failed: http status 401 Unauthorized unmarshaling response: EOF"
}
```

### Expected result

account address

### Actual result

`http status 401 Unauthorized unmarshaling response: EOF`

**Comment by distractedm1nd** [comment]
I'm assuming this is fixed by [this pr](https://github.com/filecoin-project/go-jsonrpc/pull/108) and #3385 can fix it once released. 

Expected Result should probably not be "account address", 401 signifies you did not have permission to access that endpoint -- meaning the expected result should be an error and not a result, with a cleaner ouput.

The 401 could either be internally from node/jsonrpc (by not setting the auth token), or from your networking setup between the client and node. Could you provide more details from the setup?

**Comment by jcstein** [comment]
my setup is just me running `celestia light start --p2p.network arabica --core.ip validator-1.celestia-arabica-11.com` in one terminal, and in another, trying to get the account address `celestia state account-address --node.store $HOME/.celestia-light-arabica-11`

**Comment by jcstein** [comment]
[here is a loom](https://www.loom.com/share/f9ef9754b38240b8ae2294428edcc64a?sid=e3368a3c-1672-4ddb-9701-66802be1d0c1)

**Comment by jcstein** [comment]
hold on a second...i think the auth token needs to be `admin` not `write`, but i guess there is still a bug in here as i should receive a more useful and readable error

```bash
export CELESTIA_NODE_AUTH_TOKEN=$(celestia light auth admin --p2p.network arabica)
celestia state account-address --token $CELESTIA_NODE_AUTH_TOKEN
```

**Comment by Wondertan** [comment]
> hold on a second...i think the auth token needs to be admin not write, but i guess there is still a bug in here as i should receive a more useful and readable error

Hmn, the logic added by @mastergaurang94 that removes the need to specify the store should have automatically gotten the admin token. Do i understand correctly that you don't have this issue when you specify admin token, but when not it fails?

**Comment by jcstein** [comment]
@Wondertan https://github.com/celestiaorg/celestia-node/pull/3246 is not included in v0.13.5 release

if running:
1. `celestia light start --p2p.network arabica --core.ip validator-1.celestia-arabica-11.com`
2. the node and then requesting account address with no auth token or node store, it errors because it needs either auth or node store, as expected.

```bash
celestia state account-address
Error: cant get the access to the auth token: token/node-store flag was not specified
Usage:
  celestia state account-address [flags]

Flags:
  -h, --help   help for account-address

Global Flags:
      --node.store string   The path to root/home directory of your Celestia Node Store
      --token string        Authorization token
      --url string          Request URL (default "http://localhost:26658")
```

**Comment by Wondertan** [comment]
Ah, I see, thanks for correction

**Comment by jcstein** [comment]
and now that i've changed the auth token to admin, i cannot reproduce an error where:

```bash
celestia state account-address --node.store $HOME/.celestia-light-arabica-11
```

results in an error. i don't know how this is related, though tbh 😅 

i can also use this successfully and see no error from using `write` instead of `admin`

```bash
export CELESTIA_NODE_AUTH_TOKEN=$(celestia light auth write --p2p.network arabica)
celestia state account-address --token $CELESTIA_NODE_AUTH_TOKEN
{
  "result": "celestia1lvns26q9d43a5fcl3xjmfy3auk6fekf2x5pp93"
}
```

**Comment by renaynay** [comment]
@jcstein Is the issue resolved here? If so, feel free to close the issue

**Comment by jcstein** [comment]
yep let's close this
