### ISSUE TITLE
[Bug]: TestRetrieveBlockData exceeds goroutine limit with -race flag

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#340]
### Celestia Node version

af0277b15ec17214965ef15083a2cd2f31b9f93f

### OS

macOS 12.0.1

### Steps to reproduce it

go test -v -race -run TestRetrieveBlockData ./ipld -count 1 

### Expected result

TestRetrieveBlockData is passing

### Actual result

TestRetrieveBlockData is failing

### Relevant log output

```shell
race: limit on 8128 simultaneously alive goroutines is exceeded, dying
```

### Notes

Same is reproducible in github action execution

**Comment by Wondertan** [comment]
It is not a race condition. Unfortunately, the race detector has a limit to the number of goroutines possible in the test and this test spawn goroutines deliberately.

**Comment by Wondertan** [comment]
The proper fix is: https://github.com/celestiaorg/celestia-node/issues/247

**Comment by Wondertan** [comment]
The test is now skipped with #388 and should be unskipped once the solution above is implemented.

**Comment by renaynay** [comment]
Closing as #247 has been merged
