### ISSUE TITLE
Mocha full storage Node peering issue v0.13.5

### ISSUE THREAD

**Issue by itrocket-team** [celestiaorg/celestia-node#3401]
### Celestia Node version

v0.13.5

### OS

Ubuntu 22.04.4 LTS

### Install tools

Binaries

### Steps to reproduce it

My Celestia full Storage Node has a peering problem after upgrading to v0.13.5
`celestia full config-update --p2p.network mocha` didn't help

### Expected result

I have tried restarting a couple of times, and it didn't help. Ports 2121  UDP and 2121 TCP are open

### Actual result

- As a result of having 0 peers, the full Storage Node is stuck  
- And I have the same issue on our bridge node, installed on separate server, but the Bridge node is not stuck...  
>Bridge node logs:
```
May 13 12:18:01 Reliable2 celestia[23720]: 2024-05-13T12:18:01.768Z        WARN        share/discovery        discovery/discovery.go:219        Potentially degraded connectivity, unable to discover the desired amount of full peers in 5m0s. Number of peers discovered: 0. Required: 5.
May 13 12:18:03 Reliable2 celestia[23720]: 2024-05-13T12:18:03.042Z        INFO        header/store        store/store.go:375        new head        {"height": 1818128, "hash": "00D591E4E2DEF2E81BE77C60283BDC39BF29F5F3D38DC1136FCC516B145058CE"}
```

### Relevant log output

```Shell
May 13 11:41:30 celestia[1688566]: 2024-05-13T11:41:30.243Z        INFO        pidstore        pidstore/pidstore.go:84        Persisted peers successfully        {"amount": 0}
May 13 11:41:30 celestia[1688566]: 2024-05-13T11:41:30.243Z        WARN        share/discovery        discovery/discovery.go:219        Potentially degraded connectivity, unable to discover the desired amount of full peers in 5m0s. Number of peers discovered: 0. Required: 5.
```

**Comment by itrocket-team** [comment]
About an hour later, both the full storage and bridge nodes were able to connect to the peers without any intervention from me, and now all indicators are normal. This information might be useful, if not, you can close the issue

**Comment by ramin** [comment]
thanks for the report @itrocket-team, this was useful info. let us know if you experience other issues
