### ISSUE TITLE
share.GetSharesByNamespace: non-deterministic response

### ISSUE THREAD

**Issue by christopherbrumm** [celestiaorg/celestia-node#3448]
### Celestia Node version

v0.13.4 - Commit: 13ac02fe9a659b8741c2f62fac256c4ef249b718

### OS

Ubuntu 22.04.4 LTS

### Install tools

- go1.22.0
- GNU Make 4.3

### Others

`celestia full start --core.ip public-celestia-grpc.numia.xyz --rpc.port 35001`

### Steps to reproduce it

1. Set up two different full nodes
2. Request the `share.GetSharesByNamespace` endpoint for a certain namespace for a range of heights (e.g. `1,000,000 - 1,500,000`).
3. Compare the results.

### Expected result

Deterministic responses.

### Actual result

We’ve experienced non-deterministic responses to the `share.GetSharesByNamespace` query. For certain heights (e.g., height 1400810, namespace `AAAAAAAAAAAAAAAAAAAAAAAAAAAADBuw7+PjGs8=`), different nodes respond with different values (`null` or `[]`), although they have the exact same  full-node setup.

### Relevant log output

```Shell
Will be submitted in the following days alongside with a script that can be used to reproduce the submitted issue.
```

**Comment by walldiss** [comment]
Hey! Thank you for reporting the issue. It is very concerning and I'll try to reproduce. I have few question, that will help to identify whats is the root cause: 
- How do you call share.GetSharesByNamespace? Do you use JSON-RPC or maybe CLI?
- Can inconsistency be achieved by doing request to the same node?
  - If yes, do you run your nodes with same setup mentioned above?
- Does `null` result contain any error with it?

**Comment by christopherbrumm** [comment]
> * How do you call share.GetSharesByNamespace? Do you use JSON-RPC or maybe CLI?
With JSON-RPC:
`await axios.post(this.config.rpc, {
        id: 1,
        jsonrpc: '2.0',
        method: 'share.GetSharesByNamespace',
        params: [
          header,
          namespace
        ]
      }, {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.CELESTIA_NODE_AUTH_TOKEN}`
        }
      });`

> * Can inconsistency be achieved by doing request to the same node?
No. After trying again, all nodes respond with `[]`.

> * Does `null` result contain any error with it?
No, it doesn't contain an error, although I haven't checked the nodes' logs. Respond:
`{
          "namespace_id": "AAAAAAAAAAAAAAAAAAAAAAAAAAAADBuw7+PjGs8=",
          "data": [
            {
              "shares": null,
              "proof": {
                "start": 8,
                "end": 9,
                "nodes": [
                  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMofYJmDgqpoqbuDJgJzdZYSt/fjQcSKDbTIuaYiV8dt",
                  "AAAAAAAAAAAAAAAAAAAAAAAAALz67w0250KL770AAAAAAAAAAAAAAAAAAAAAAAAAvPrvDTbnQovvvanKT7x2q7/r+Lyzokg/7SgCfqdKFS+fI1tPNhD7hl+M",
                  "AAAAAAAAAAAAAAAAAAAAAAAAALz67w0250KL770AAAAAAAAAAAAAAAAAAAAAAAAAvPrvDTbnQovvvYDUPMuM5s3OXnaK1JT4cGsSUzpMXvLcVEsVXXji8P4j",
                  "AAAAAAAAAAAAAAAAAAAAAAAAALz67w0250KL770AAAAAAAAAAAAAAAAAAAAAAAAAvPrvDTbnQovvvYbD+UC9eCyctpgo/lxldHjugN1ODy9vS9U+z3DKcEuw",
                  "/////////////////////////////////////////////////////////////////////////////6ReOHX5c579orXfnXK086AG/wmkCfL5rMpQ2Ee8c9Gh"
                ],
                "leaf_hash": "AAAAAAAAAAAAAAAAAAAAAAAAALz67w0250KL770AAAAAAAAAAAAAAAAAAAAAAAAAvPrvDTbnQovvveyPe6A6gO7bouW2bsDMt1UvOz2U5DgDFH5g2TMowWu7",
                "is_max_namespace_ignored": true
              }
            }
          ]
        }`
        
I am also trying to reproduce the error on a new node, but without success so far.

**Comment by Wondertan** [comment]
According to the response you shared, in the case where we return a non-inclusion proof, we return `nil` instead of `[]`

**Comment by Wondertan** [comment]
Seems like a quick fix in ShrexGetter. Can you take a look in it, @walldiss?

**Comment by walldiss** [comment]
Hey! @Wondertan is correct, the implementation of getters is a bit inconsistent for non-inclusion proofs. Right now, you might get [] when data is found in the local store and null if it's not there and we try to fetch it from the network. Here’s how the responses currently look for the Shares:

- ShrexGetter: null
- StoreGetter: []
- IPLDGetter: []

I'm planning to streamline this by using null across the board to avoid unnecessary allocation. If this inconsistency is causing you any trouble, you might want to check len(Shares) in your response handler to see when the data isn't included. Let me know if you need any help!

**Comment by christopherbrumm** [comment]
Thanks a lot @walldiss!

Will wait until PR #3454 is merged before continuing with archiving the blobs.
