### ISSUE TITLE
[Feature Request]: Choose key/account to post blob using celestia-node

### ISSUE THREAD

**Issue by a26nine** [celestiaorg/celestia-node#3496]
### Implementation ideas

It would be beneficial to have an option to choose a key/account to post a blob on-chain using celestia-node, just as celestia-appd allows it using the `--from` flag.

**Comment by renaynay** [comment]
@vgonkivs is currently working on this as a part of #3295

**Comment by renaynay** [comment]
Closing as duplicate of #3295
