### ISSUE TITLE
[Bug]: node/p2p: light client can das without proper connection to a trusted peer

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#352]
### Celestia Node version

42928034b442c70499e2bf4a02292ce2e74acfbe

### OS

ubuntu

### Install tools

- make install
- run full and light in 1 machine
- full and light have the same ip/port for generating a multiaddress

### Steps to reproduce it

1. Run the Celestia Full Node (Bridge Node post-devnet terms)
2. Initialize the Celestia Light Client with defaults(port 2121) in the same machine as the full
   - add the same multiaddr from CFN (CBN) as a trusted peer
3. Add the CFN(CBN) multiaddr as the mutual peer for the CLC
4. Start the CLC

### Expected result

CLC is not dasing due to no sync being done from the absent connection to the trusted peer

### Actual result

CLC is dasing due to mutual peer being a CFN(CBN)

### Relevant log output

```shell
https://gist.github.com/maxzonder/23c50a00f45a20f2c1eacae421385a89
```

### Notes

Needs retesting with 2 instances (1 for CFN-CBN and 1 for CLC) on master
Will do @Bidon15

**Comment by Wondertan** [comment]
DASing works with any peer and does not require a trusted peer. Don't see this being an issue. An issue is more that we are too tied on the trusted peer for header exchange and instead should be able to work with any peers(besides header for subjective initialization)

**Comment by Wondertan** [comment]
@Bidon15, I am closing this as this is valid behavior. Pls reopen if you see an issue here.
