### ISSUE TITLE
nodebuilder: Config changes not seen by node.Start

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#3523]
@tac0turtle reported that changes to the config were not picked up by the node when started.

He changed the RPC and gRPC ports in the config and started the node, but the node still looked at the default ports. No port flags were passed via CLI

CLI flags should override config on start, but in their absence, config should be read.

This isn't confirmed to be an issue yet, so let's confirm it's reproducible first.

**Comment by ramin** [comment]
@renaynay @tac0turtle i can't recreate this error with a totally fresh light node with new config off main. Is it possible you have an older config from node store initialized long ago? Does your config.toml have the [Core] entry

I did notice the config is confusing. If you edit the settings under [core], eg:

```
[Core]
  IP = ""
  RPCPort = "1234"
  GRPCPort = "1234"
```

These changes will take effect, but there is an additional (maybe confusing) entry for the RPC server you could mistakenly edit?

**Comment by ramin** [comment]
@tac0turtle ah yeah that is quite specific and i CAN recreate in that case. will work on a fix. thank you
