### ISSUE TITLE
[Feature Request]: WebRTC libp2p transport

### ISSUE THREAD

**Issue by lzrscg** [celestiaorg/celestia-node#3538]
### Implementation ideas

Lumina can perform DAS in the browser using webtransport. However, [this is not supported by Safari](https://caniuse.com/?search=webtransport)—which means it won't work for a large number of users. The solution to this could be to add websockets as a transport method, which works in Go, Rust, and JS (Browser).

I brought up this topic in Lumina's repo, and thought it might be good coordinate this feature request with the celestia-node team as well.

Here is the original issue: https://github.com/eigerco/lumina/issues/314

**Comment by Wondertan** [comment]
https://github.com/eigerco/lumina/issues/314#issuecomment-2197337211
