### ISSUE TITLE
[Feature Request]: read only mod that doesn't require RPC

### ISSUE THREAD

**Issue by joroshiba** [celestiaorg/celestia-node#3544]
### Implementation ideas

In our use of celestia nodes, we have some nodes which are never used for submission. We just want to participate in DAS network and read data. I believe this is common with rollkit (every node that's not a header producer just reads data). On startup celestia light nodes require an RPC connection, and if for whatever reason that rpc doesn't work it crash loops because it can't read gas price data.

If you are using a node where you never write data this is unnecessary. The light node will crash (and potentially crash loop of configured to auto restart). A read only mode would I believe not require an RPC connection at all?

**Comment by Wondertan** [comment]
I believe it was possible; if not, there might be a new bug. Could you share the logs you see in the crash loop? The rpc flag should be optional.

**Comment by ramin** [comment]
@joroshiba this is unexpected, a light node can start with no RPC connection, can you share exactly what your running and i can try and recreate and figure out what might be going on

**Comment by joroshiba** [comment]
Sorry about delay here, did not realize RPC was optional (maybe it wasn't always?). Closing issue, just not setting the RPC solves our issue.
