### ISSUE TITLE
blob: can't get blobs in arabica

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#3572]
It's not possible to successfully retrieve the dah at a height [1373869](https://arabica.celenium.io/tx/6818c93b3e7668690c19eeba12525a02336de8bfa3111228fce127b5b4961ba6?tab=messages) on arabica-11.

**Steps to reproduce:**
1) Launch celestia light node on arabica-11: 
`celestia light run  --core.ip=consensus.celestia-arabica-11.com --p2p.network=arabica`
2) Wait until the node syncs to the needed height;
3) request blob: 
`celestia blob get 1373869 0x8f8736b6ff9dc08065a6 0x9ede456e70b3c95ec779bd5b434d787911b1911b29629e88c80b5cc52736021b`

**Expected behavior:**
Blob's info is printed;

**Actual behavior:**
The request is stuck until a timeout is reached(in case of CLI request forever)

Tested on the latest main.

NOTE: It happens only for this particular height.

**Comment by Wondertan** [comment]
The other surprising thing/bug is that it works only when we disable shrex, while it should have worked with CascadeGetter swtiching to IPLDGetter after ShrexGetter  has failed.

**Comment by vgonkivs** [comment]
https://github.com/celestiaorg/celestia-node/issues/2501

**Comment by Wondertan** [comment]
Seems like the bug is that we never actually set the timeout on this operation

**Comment by vgonkivs** [comment]
Yeah, so setting `minTimeout` fixes this.

**Comment by Wondertan** [comment]
Ok, we should still this or other issue around for ShrexGetter not working as expected

**Comment by srene** [comment]
so is there any option i can set in the light client to retrieve the blob, or do i have to wait for a new release that fixes the bug? thanks

**Comment by Wondertan** [comment]
@srene, do you face this particular issue? Generally, blobs are retrievable.

**Comment by srene** [comment]
this particular case was reported by me. we are not able to get a specific blob for a rollapp in dymension testnet, and is causing some issues to get full-nodes syncing.

**Comment by Wondertan** [comment]
Ah, I see. We can provide a quick fix branch for this issue.

**Comment by vgonkivs** [comment]
Hello, @srene. Do you need a test branch with the quick fix so you can test it?

**Comment by srene** [comment]
yes, that will help. thanks

**Comment by vgonkivs** [comment]
Hello, @srene. I made a [fix](https://github.com/celestiaorg/celestia-node/pull/3591) and it is a part of v0.15.0 release.

**Comment by vgonkivs** [comment]
Not relevant anymore
