### ISSUE TITLE
permission problem when make build celestia with non root user

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#3603]
### Celestia Node version

v0.13.7 to 0.14.1

### OS

ubuntu 22.04

### Steps to reproduce it

checkout and do make build with a non root user

### Expected result

binary builds normally

### Actual result

```
go: downloading [go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc](http://go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc) v0.47.0
[github.com/celestiaorg/celestia-node/cmd/celestia](http://github.com/celestiaorg/celestia-node/cmd/celestia): go build [github.com/celestiaorg/celestia-node/cmd/celestia](http://github.com/celestiaorg/celestia-node/cmd/celestia): copying /tmp/go-build3878569183/b001/exe/a.out: open build/celestia: permission denied
make: *** [Makefile:39: build] Error 1
```

**Comment by ramin** [comment]
@mindstyle85 i'm not able to recreate this on a totally new box, fresh users, no history. Non root user can checkout and build fine, was this a fresh box on your side? Let me know if you have more information to properly recreate or can verify this happens on a fresh install and i can look again
