### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by najibDev** [celestiaorg/celestia-node#363]
### Celestia Node version

Semantic version: v0.1.1

### OS

Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1022-aws x86_64)

### Install tools

no install tools
I ran the node following this web page: 
https://mzonder.notion.site/Celestia-Full-Node-Light-Client-Install-devnet-2-on-the-same-server-with-Application-valida-cdd5c1ff3c1943f5b85220e55bcae609

### Steps to reproduce it

journalctl -u celestia-full.service -o cat -f

### Expected result

Example: Celestia node is running in default mod
![Untitled](https://user-images.githubusercontent.com/7003804/149833508-59bd7dc9-fc18-470a-beb2-5507f0116d02.png)
e

### Actual result

I have the error below: 
![image](https://user-images.githubusercontent.com/7003804/149833955-db225771-5b4d-4487-9c37-1b38ec6a375f.png)

### Relevant log output

```shell
2022-01-17T20:36:54.541ZWARNheader-serviceheader/store.go:199header/store: no valid headers were given
2022-01-17T20:36:54.541ZINFOblock-serviceblock/event.go:103stored block{"block height": 305077, "block hash": "E9538F005E9ABEA2DBA46F5584C565B14CE1D
C587D03AEF65302551C08C89287"}
2022-01-17T20:37:10.030ZINFOblock-serviceblock/event.go:27received new block{"block height": 305078, "block hash": "7E7C4DAA2CC39DCD66DDA93198A5A
3CE1CFF7D8567312606081BC97B4659F221"}
2022-01-17T20:37:10.041ZERRORheader-serviceheader/store.go:192invalid header{"current head": "965C8423D3928C8DD68833084B628DF9844DCEC4514F08E85D7FC160409
FD738", "height": 214833, "attempted new header": "7E7C4DAA2CC39DCD66DDA93198A5A3CE1CFF7D8567312606081BC97B4659F221", "height": 305078, "err": "headers must be adjacent in height"}
```

### Notes

I am sorry if it's not clear.
It's the first issue opening for me.

By the way, I am french and my english is a little bit...

Thanks.

**Comment by renaynay** [comment]
Thank you so much for opening an issue @najibDev

This issue occurs when the header store attempts to append a new header that is too distant in height from the header store's latest known header -- a known issue with our current devnet sync logic.

We are working on hardening sync logic such that if a node receives a header much greater in height than its latest known header, it will perform a sync up to that new header height.

**Comment by yura2434** [comment]
did you find a solution to the problem?

**Comment by Wondertan** [comment]
The new upcoming release fixes the roots of the problem.

**Comment by waelsy123** [comment]
@Wondertan does that mean that we will need to reset all local blocks and sync again after the new release?

**Comment by mindstyle85** [comment]
> 

im not sure about resetting, especially with that error above, but you can easily try it already, you can checkout v0.2.0

**Comment by Wondertan** [comment]
This issue shouldn't happen anymore with 0.2.0.
