### ISSUE TITLE
Audit the need for WANT_HAVEs and cut them off in case its not

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#3632]

**Comment by renaynay** [comment]
More information in #3630

**Comment by Wondertan** [comment]
That's unrelated to #3630

**Comment by Wondertan** [comment]
Bitswap sends WANT_BLOCK for each sample to one peer and WANT_HAVE to other peers in the session as a back-up in case WANT_BLOCK is unsuccefull. The original worry behind this issue was that WANT_HAVE adds a roundtrip, which is not the case, so we can close this issue.
