### ISSUE TITLE
Node Halting

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#365]
## What
In case of an unrecoverable event where the honest majority becomes malicious, any celestia-node should halt and stop accepting new headers. Such an event can be detected with 
* Fraud Proofs
* Double signing

## TODO
 - [ ] Exactly define what is halting
 	- Do we need something else besides not receiving any new headers?
 - [ ] Define simple one func/method halting API that stops what decided to be stopped.

**Comment by renaynay** [comment]
We decided the architecture for this issue is that all services that must be stopped/halted if bad encoding fraud was detected will rely on `FraudService` and shut down if `FraudService` sends the stop signal.

**Comment by renaynay** [comment]
Tracked in #528
