### ISSUE TITLE
ci: run coverage script and display coverage via badge

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#368]
- [ ] Configure and run coverage in CI and reject PR if it substantially lowers coverage. 
- [ ] show badge with coverage

**Comment by tzdybal** [comment]
This can be done easily with codecov-action. I also highly encourage to use go-acc for better cross-package coverage (see [optimint workflo](https://github.com/celestiaorg/optimint/blob/main/.github/workflows/test.yml#L24-L31)).
