### ISSUE TITLE
Unable to introduce appconsts github.com/celestiaorg/celestia-app/pkg/appconsts lib 

### ISSUE THREAD

**Issue by Delaube923** [celestiaorg/celestia-node#3695]
github.com/celestiaorg/celestia-app/pkg/appconsts  requires github.com/gogo/protobuf@v1.3.3:
but unable to find github.com/gogo/protobuf@v1.3.3

**Comment by Wondertan** [comment]
Make sure you have proper replaces your in go.mod. Check them out in our go.mod
> 	replace github.com/gogo/protobuf => github.com/regen-network/protobuf v1.3.3-alpha.regen.1
