### ISSUE TITLE
v0.16.0 release doesn't have prebuilt binaries

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#3711]
## Context

https://github.com/celestiaorg/celestia-node/releases/tag/v0.16.0 doesn't have prebuilt binaries. 

## Problem

Looks like integration tests keep failing on https://github.com/celestiaorg/celestia-node/actions/runs/10685447212 so version_bump and goreleaser never get triggered

## Proposal

1. [short term] keep retrying CI until it succeeds
2. [medium term] maybe make version bump not depend on integration tests b/c they're flaky
3. [long term] fix the flaky integration tests

An alternative short term solution is to manually attach the prebuilt binaries. We've had to do that a lot on celestia-app b/c goreleaser config issues so we have a [guide](https://github.com/celestiaorg/celestia-app/blob/main/docs/maintainers/prebuilt-binaries.md).

**Comment by renaynay** [comment]
Should be fixed now @rootulp

**Comment by rootulp** [comment]
https://github.com/celestiaorg/celestia-node/releases/tag/v0.16.0

![Screenshot 2024-09-10 at 2 01 22 PM](https://github.com/user-attachments/assets/1ebf0703-2bb5-46ad-89f5-a22e6eb53375)

**Comment by renaynay** [comment]
Oh whoops sorry I thought our CI ran properly 😬

**Comment by Halimao** [comment]
How is this issue going now? Still have trouble in downloading prebuilt binaries with `bash -c "$(curl -sL https://docs.celestia.org/celestia-node.sh)"`

```shell
--2024-10-03 02:49:34--  https://github.com/celestiaorg/celestia-node/releases/download/v0.16.0/celestia-node_Linux_x86_64.tar.gz
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-10-03 02:49:34 ERROR 404: Not Found.
```

**Comment by jcstein** [comment]
v0.17.1 doesn't either

**Comment by jcstein** [comment]
Reported from devrel telegram chat:

"and the doc says testnet is celestia-node v0.18.2-mocha, but that version docker image not exists, I use latest instead. the testnet seems works well."

**Comment by hyacinthus** [comment]
Yes, I need the docker image :)

**Comment by renaynay** [comment]
Our CI (goreleaser) has been fixed on recent releases, and `v0.16.0` is now outdated on both `arabica` and `mocha` and will become outdated tomorrow on `mainnet` as well.

**Comment by rootulp** [comment]
FYI a release from yesterday doesn't have prebuilt binaries: https://github.com/celestiaorg/celestia-node/releases/tag/v0.20.2-arabica.

![Screenshot 2024-11-19 at 10 17 38 AM](https://github.com/user-attachments/assets/5467c458-8ed3-499f-bab6-65b1aa6c8b8f)

GoReleaser gets confused when fetching the latest tag for a particular commit if one commit has multiple tags (i.e. v2.0.0-mocha, v2.0.0-arabica). To temporarily workaround, celestia-app plans on creating releases on distinct commits. But it looks like celestia-node had a different problem for the v0.20.2-arabica b/c GoReleaser job was skipped: https://github.com/celestiaorg/celestia-node/actions/runs/11894453531/job/33141724905

**Comment by cristaloleg** [comment]
That's interesting, thanks for the info! I will take a look tomorrow.

**Comment by jcstein** [comment]
is this related to #3938 ?
