### ISSUE TITLE
blob: Service.GetProof mistakenly swallows up error from Service.retrieve

### ISSUE THREAD

**Issue by odeke-em** [celestiaorg/celestia-node#3726]
If we examine this code https://github.com/celestiaorg/celestia-node/blob/1a1286f454c1dd670af856153a8fc8674cd91192/blob/service.go#L237-L238 we can see something peculiar there that err is set but down below, there is a `return proof, nil` of which due to the use of named returns in Go, even if there was a variable name clash. Please return that value and test that code more: if it was intended, please document it instead.

/cc @liamsi @rootulp @musalbas

**Comment by Wondertan** [comment]
cc @vgonkivs, we should fix it

**Comment by vgonkivs** [comment]
I'm pretty sure that I saw the fix in some of our PRs previously. But for some reason, It hasn't been merged(or it was overwritten during resolving conflicts). Thanks for catching it @odeke-em.
