### ISSUE TITLE
Excessive logging from bitswap

### ISSUE THREAD

**Issue by S1nus** [celestiaorg/celestia-node#3758]
### Celestia Node version

v0.16.0

### OS

Mac amd64

### Steps to reproduce it

`celestia light start`

### Expected result

Normal log output

### Actual result

excessive log messages like this
`bitswap/session    session/session.go:477    No peers - broadcasting    {"session": 2071, "want-count": 1}`

When killed with ctrl + C, we get excessive logs like `bitswap/client/msgq    messagequeue/messagequeue.go:545    Could not send message to peer 12D3KooWMwEGFhgxB95prxSCq3SSgigQMTBn95rpP6W8GK1ECy9W: context canceled` for a long time before it times out and finally stops

### Relevant log output

```Shell
`bitswap/session    session/session.go:477    No peers - broadcasting    {"session": 2071, "want-count": 1}`
```

### Is the node "stuck"? Has it stopped syncing?

no, it doesn't seem stuck

**Comment by Wondertan** [comment]
was fixed by https://github.com/celestiaorg/celestia-node/pull/3713
