### ISSUE TITLE
docs: CLI menu doesn't clarify that aliases can be used

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3829]
Proposed solution:
add a note in the CLI menu that says aliases for Mocha and Arabica work

**Comment by renaynay** [comment]
@jcstein should be resolved by this https://github.com/celestiaorg/celestia-node/commit/3997d7268e14f3e24ea268d3504cec276dcb8a66

Can you confirm @jcstein ? Please close this if it works for you. I just listed them along with the other valid options.

**Comment by jcstein** [comment]
Yes your PR fixes it, I just made this before knowing you had one :)
Thanks @renaynay !
