### ISSUE TITLE
docs: response examples should match API

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3840]
# Problem

[From Slack thread](https://celestia-team.slack.com/archives/C0639CBCAF7/p1728632038656139?thread_ts=1728548434.440719&cid=C0639CBCAF7)

I generated specs using `celestia docgen` on v0.16.0 and v0.17.1 and added them to docs, but it is reported that the response examples are incorrect on docs still, although the API changed. API spec updates from v0.16.0 and v0.17.1 do not contain correct responses, for at least tx responses:

Source: https://github.com/celestiaorg/celestia-node/releases/tag/v0.16.0

> API Response Changes: The return type for SubmitPayForBlob remains unchanged, but most fields in the response will now be omitted. Only the Code, TxHash, and Height fields will be populated, with all other fields set to empty values.

# Solution

Modify the docs within celestia-node so that when docs are generated in the CI (building the openrpc.json specs) or manually in CLI, they contain the correct responses

**Comment by jcstein** [comment]
Note that these were manually generated because CI did not build the specs for either of the mentioned releases.

**Comment by zvolin** [comment]
I think the reason for that could be because the type hasn't changed on celestia-node side, just now celestia-app responds with the other type that only partially maps to the TxResponse. Docs probably just fill dummy values for the type they see
