### ISSUE TITLE
cel-key node.type flag broken?

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#3851]
### Celestia Node version

0.18.2

### OS

ubuntu

### Steps to reproduce it

n/a

### Expected result

n/a

### Actual result

```
cel-key add mocha --keyring-backend test --node.type bridge --p2p.network mocha
Error: no or invalid node type provided
```

**Comment by redwest88** [comment]
Can confirm I'm encountering the same issue with the following command:
```
cel-key add wallet --node.type bridge --p2p.network mocha --recover
Error: no or invalid node type provided
```
### System Information:
```
- Celestia Node version: v0.18.2-arabica
- OS: Ubuntu 22.04.5 LTS (Jammy)
- Golang Version: go1.23.1
```

**Comment by redwest88** [comment]
It worked for me with the command:
```
cel-key add wallet --node.type Bridge --p2p.network mocha --recover
```
The only change I made was adjusting `--node.type bridge` to `--node.type Bridge`

**Comment by dapriddle-eth** [comment]
Same error using --node.type light
Had to use --node.type **L**ight

**Comment by renaynay** [comment]
https://github.com/celestiaorg/celestia-node/pull/3827 fixes this and will be released soon.
