### ISSUE TITLE
[Feature Request]: No need for both GRPC and Tendermint URLs

### ISSUE THREAD

**Issue by ranlavanet** [celestiaorg/celestia-node#3901]
### Implementation ideas

Light node requires both grpc and tendermint URLs to be provided which is not necessary in cosmos. 

`github.com/cosmos/cosmos-sdk/client` can be used by providing just the tendermint RPC endpoint.
Making it easier for the users to set up their client.

```golang
RunE: func(cmd *cobra.Command, args []string) error {
    clientCtx, err := client.GetClientTxContext(cmd)
    // any module query client
    <anymodule>.NewQueryClient(clientCtx)
    // as well as any tendermint rpc calls, for example status. 
    status, err := clientCtx.Client.Status(ctx)
```

Also, If you prefer to keeping the optionality to set up two endpoints, please allow the users to set up different URLs for both grpc and tendermint 

I.E 
Tendermint URL:
`https://celestia.tendermint.rpc:443`
gRPC URL: 
`celestia.grpc.rpc:443`

currently the binary allows only port configuration while using the same IP address.

**Comment by Wondertan** [comment]
Unfortunately, that's not possible, as we still need the ability to fetch Block data, Commits, and Validator sets, and that's not accessible from GRPC. 

We are working on moving necessary endpoints to GRPC to make it work with a single endpoint only, also avoiding the overhead JSON brings over the wire for big blocks

**Comment by ranlavanet** [comment]
Tendermint can make "GRPC" calls internally using abci_query.

**Comment by Wondertan** [comment]
These are only limited to App's state. It can't serve the data I listed above.

**Comment by Wondertan** [comment]
You can follow developments of the new endpoint here: https://github.com/celestiaorg/celestia-core/pull/1513

**Comment by Wondertan** [comment]
@omerlavanet, It is possible to do almost* everything with TM's JSON RPC only. Our goal, on the other hand, is to make everything work over GRPC as JSON brings noticeable overhead.

**Comment by Wondertan** [comment]
This change will land in a not-so-distant future release, effectively resolving the unification you requested.
