### ISSUE TITLE
swamp: race in NewSwamp and Core

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#392]
![image](https://user-images.githubusercontent.com/22449364/150992689-74f52b01-b556-42eb-ac76-d8891412791f.png)

**Comment by Wondertan** [comment]
Found in https://github.com/celestiaorg/celestia-node/pull/334

**Comment by Bidon15** [comment]
So this should be fixed after I finish with https://github.com/celestiaorg/celestia-node/issues/371

Some sample runs of the draft(will be closed) https://github.com/celestiaorg/celestia-node/pull/393

https://github.com/celestiaorg/celestia-node/runs/4938174725?check_suite_focus=true
