### ISSUE TITLE
bug: version output is malformatted

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-node#3938]
### Celestia Node version

v0.20.1

### OS

mac

### Install tools

docs

```
# clone node
make build
make install
celestia version
```

### Steps to reproduce it

above

### Expected result

`version: v0.20.1-mocha`

### Actual result

```
$ celestia version

Semantic version: v0.18.0-refs-tags-v0-20-1-mocha.0
Commit: 353141fb5a0a33c10a8678ac6e92a90b02f74dbd
Build Date: Thu Nov 14 14:10:37 +07 2024
System version: arm64/darwin
Golang version: go1.23.2
```

**Comment by jcstein** [comment]
This is still present on v0.20.2

```
/_____/  /_____/  /_____/  /_____/  /_____/
Started celestia DA node
node version:         v0.18.0-refs-tags-v0-20-2-arabica.0
node type:         bridge
network:         mocha-4
/_____/  /_____/  /_____/  /_____/  /_____/
```

**Comment by walldiss** [comment]
Thank you for reminding of this issue. We have broken CI that produces second tag for release and it is mailformed one. I’ve deleted incorrect tags for all recent releases, so it should not be a problem for existing ones. @oleg is on the hunt to track down the root cause

**Comment by jcstein** [comment]
you're welcome and thank you for the context and support 🙌

**Comment by jcstein** [comment]
got it. this is the only release with that commit though, so not sure this should be closed yet?
