### ISSUE TITLE
Failed to resolve addr (da-full-1 on 127.0.0.53:53: server misbehaving)

### ISSUE THREAD

**Issue by 0x-Fury** [celestiaorg/celestia-node#3960]
### Celestia Node version

v0.20.2

### OS

Ubuntu 22.04.5

### Install tools

go `1.23.3`

### Others

```
/usr/bin/celestia bridge start \
    --core.ip XXX \
    --core.rpc.port XXX \
    --core.grpc.port XXX \
    --p2p.network celestia \
    --metrics \
    --metrics.tls=true \
    --metrics.endpoint otel.celestia.observer \
    --p2p.metrics \
    --archival
 ``` 

### Steps to reproduce it

Synced up a fresh DA bridge node on `v0.20.2` commit: `b24d47fe29d2b244d501194956412cb7bb60f30f`

Synced to chain head with no issues but we're seeing this `WARN`:

```
Nov 23 16:27:31 celestia-brg02 celestia[84231]: 2024-11-23T16:27:31.323+0100        WARN        swarm2        swarm/swarm_dial.go:454        Failed to resolve addr /dns/da-full-1/tcp/2121: lookup da-full-1 on 127.0.0.53:53: server misbehaving
```

### Expected result

Expect `WARN` to disappear or if its fine to disregard

### Actual result

The `WARN` does not disappear

**Comment by smuu** [comment]
Hey @0x-Fury,
We cannot reproduce this issue.

We migrated some infrastructure components in the last few days, and we suppose this caused this temporary issue.
Please let me know if you can still observe that issue, and I will reopen it.

**Comment by 0x-Fury** [comment]
Hi @smuu 

Yes we're still seeing this `WARN`. We've since upgraded to latest `v0.20.4` commit: `51b79431533576a5cddf1235bdf3751e4c014212`.

Let us know if you'd like anymore info.
