### ISSUE TITLE
Light node throws unexpected INFO line

### ISSUE THREAD

**Issue by fontm2** [celestiaorg/celestia-node#402]
My validator node and full node are working as expected, but my light node gave me back a line i would expect from a validator or full node in case some resources are exhausted. I am using a quad-core 8GB RAM 200GB SSD VPS. Another node is running too on the same machine and quite constant CPU consumption is at 45% and ram at 49% without and peaks. SSD should not be an issue with the current block height. It was suggested in discord to raise an issue here, so i hope this is helpful for future development. All the best celestia team!
![Screenshot from 2022-01-28 16-49-10](https://user-images.githubusercontent.com/6941103/151578461-fc2f16c3-49ab-4aac-853e-29fb9393e003.png)

**Comment by Wondertan** [comment]
Hello, thank you for reporting this. This is a known issue and will be fixed as we update DASing related component. A simple restart will fix this.

Also, are you able to find the DASing error in your logs?

@renaynay, this issue can only happen when a DAS failed. When such an event happens, the DASer does not retry and shuts down without continuing further DASing, so we need a (1)retrying mexanism and (2)stop failing completely.

**Comment by renaynay** [comment]
Thank you for reporting this bug @fontm2

**Comment by renaynay** [comment]
@Wondertan 

Looks like DASer only returns for a canceled context - if failures, it logs err and continues trying from the sub.

https://github.com/celestiaorg/celestia-node/blob/main/das/daser.go#L68-L93

Can you point me to the place you're referring to?
