### ISSUE TITLE
service/header/sync: Race detected in `TestSyncSimpleRequestingHead`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#405]
[Ref](https://github.com/celestiaorg/celestia-node/runs/5006778963?check_suite_focus=true#step:5:216).

![Screenshot 2022-01-31 at 15 31 04](https://user-images.githubusercontent.com/41963722/151812164-0f4945c4-bfa5-47fc-b5c4-5b172e821ea4.png)

cc @Wondertan

**Comment by Wondertan** [comment]
This is going to be fixed by a younger bro PR. I mentioned this at the big bro PR, btw

**Comment by renaynay** [comment]
Okay well now you can write "resolves #405" in little bro PR 😄

**Comment by liamsi** [comment]
<img src="https://media2.giphy.com/media/3oz8xAUUmxS2uJSKe4/giphy.gif"/>

**Comment by renaynay** [comment]
Fixed by #397
