### ISSUE TITLE
[Feature Request]: Define node behavior on BEFPs

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-node#413]
### Summary

Tracking issue: #4

Define the behavior on producing and receving a BEFP.

### Impact on users

Allows BEFPs, and therefore secure partial nodes.

### Cost of not doing

No secure partial nodes.

#### Bridge Nodes

**Producing**: do not produce BEFPs.

**Receiving**: do not process received BEFPs. _May_ forward received BEFPs, but not strictly necessary.

#### Full Nodes

**Producing**: produce BEFP when receiving a newly-seen block on the _canonical chain_ (i.e. either during initial sync, or new blocks with a Commit). Then halt (i.e. continue running and distributing BEFPs and old blocks, but don't accept new blocks) until manual intervention.

**Receiving**: do not process received BEFPs. Should forward received BEFPs, but not strictly necessary.

#### Light Nodes

**Producing**: do not produce BEFPs.

**Receiving**: receiving BEFPs against blocks on the _canonical chain_ (i.e. either during initial sync, or new blocks with a Commit). If received, halt (i.e. continue running and distributing BEFPs, but don't accept new blocks) until manual intervention.

### Urgency

Medium

**Comment by adlerjohn** [comment]
For lack of a better place to put docs, in that case an ADR is probably what we need. It can consolidate this issue and also #263

**Comment by Bidon15** [comment]
Closing due to work being tracked in https://github.com/celestiaorg/celestia-node/issues/528
