### ISSUE TITLE
Clarify the public APIs intended to be used by external developers

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#425]
Celestia-node currently contains both a binary and library. There should be documentation that clarifies this dichotomy. 

Of highest relevance are the main entry-points for developers that want to use it to build on top of it.
There are quite a few public methods and types but it is unclear which are relevant for devs trying to build on top of 
node.
A good way to know which methods are immediately relevant is to look at how @evan-forbes  and @tzdybal  are trying to use it in combination with Optimint.

@evan-forbes  plugin PR (#414) is another good example as it is made for others to extend celestia-node programmatically. An ADR is a great start but the end-result must be a developer friendly documentation.

-------------
Celstia-node will be used in these major use-cases:

1.  run as a full-node accompanied with a tendermint node 
2. run as a standalone full-node 
3. run as a DASing light node
4. run as a DASing light-node that tracks and computes Celestia-state (only the reserved Txs)
5. run together with a rollup block aggregator/sequencer in one of the above modes

While 1. and 3. are pretty obvious and 2. is currently being worked on, we did not yet really think about 4. and 5. too much. If the code is properly documented, we could even encourage community contributions for 4. and 5. Currently, that would be really hard as there is too much siloed knowledge that basically would require too much hand-holding.

**Comment by Wondertan** [comment]
Before documenting public API we should define it first and we don't have it defined.

One of the goals of RPC work is to design the public API which can be accessed by both RPC and programmatically. Right now, the only really public API we have is node.New which allows devs to instantiate a node and access the internal components of it.

**Comment by renaynay** [comment]
Public API will be documented in #506

**Comment by Wondertan** [comment]
@liamsi, is #562 fixing what you mean?
P.S To have Public API documented, we need to have it defined first, and we don't have that yet, while the ADR is going to fix this.
