### ISSUE TITLE
das: Implement DASer public API

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#427]
## Context
Currently, our `daser` only exposes Start/Stop.
 
In order to get more detailed information from the `daser`, `DASState` must be implemented.

Ideas for API methods for the `daser`:

* status of the daser(is it active/not active) 
* error handling (atm of writing, we are only logging error messages) 
*  height/hash info
* square width info

Some of the above can be modelled after [`SyncState`](#397).

## TODO

- [ ] Implement `DASState`
- [ ] Implement above suggested methods on `daser`

**Comment by liamsi** [comment]
Is this resolved with #397?

**Comment by Bidon15** [comment]
> Is this resolved with #397?

The reference is what is the example and expectation to be done for DASer 

This is going to be resolved with #473 and upcoming changes (usually I can cover some of the basics during test devs)

**Comment by renaynay** [comment]
Well it won't really be covered by #473 but a subsequent PR that will implement DASState where we can access realtime info on DASer

**Comment by renaynay** [comment]
I'm not sure errors with sampling should be stored in DASState -- but rather CacheAvailability
