### ISSUE TITLE
service/header: Subscriber.RmValidator

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#429]
Currently, we can only add new validators to Subscriber, but we should also provide a method to unregister them, so users like Syncer will unregister them on Stop.

**Comment by renaynay** [comment]
Right now, we only support adding a validator for whatever `topicID` is registered on the `p2p.Subscriber`, and during Stop, we unregister that validator (and you can only add one validator per topic). Is there still a reason to make the unregistering of topic validator more explicit @Wondertan ?

**Comment by vgonkivs** [comment]
We don't need an additional `unregister topic validator` as all logic is done inside `subscriber.Stop()`.
