### ISSUE TITLE
node: internal IPC/RPC/Internal API for `Node`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#45]
Implement some kind of interface for the `Node` so that any other application using the `Node` object and/or local CLI could remotely interact with the running daemon by using the same standardised interface. 

Components: 
- [ ] Implement an interface for interacting with `Node`
  - [ ] What kind of functionality do we want to provide via this interface?
- [ ] Implement transport(s) (whether it's HTTP/IPC/Websocket, etc.) for communication with this interface
- [ ] Implement authorisation for this interface

**Comment by Wondertan** [comment]
> Implement an interface for interacting with Node

This is an interface through which all other applications will interact with the node. To give a `geth` based analogy, this should be in some way similar to [this](https://geth.ethereum.org/docs/rpc/server)/

**Comment by renaynay** [comment]
Closing as no longer relevant.
