### ISSUE TITLE
perf: High memory usage coming from badger/y.Watermark

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#481]
![image](https://user-images.githubusercontent.com/22449364/155850231-fc8d21c6-1e6f-4d8b-80d7-ea41ca937855.png)
![image](https://user-images.githubusercontent.com/22449364/155850243-3578a0bb-9da1-4e7f-a2a1-c44100c4f525.png)

Currently, it is not clear why this happens, and seems like a leak. Also, I am not yet sure what this Watermark component does for the bodger.

**Comment by distractedm1nd** [comment]
yes resolved
