### ISSUE TITLE
das: Parallelise `catchUp` method

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#483]
Supplement https://github.com/celestiaorg/celestia-node/pull/473 by additionally parallelising the DASing of past headers. 

TODOs mentioned [here](https://github.com/celestiaorg/celestia-node/pull/473#discussion_r828138649).

**Comment by renaynay** [comment]
<img width="795" alt="Screenshot 2022-03-21 at 15 08 58" src="https://user-images.githubusercontent.com/41963722/159278716-9e18c92a-c645-42e0-b438-1cad483b0cf8.png">

**Comment by renaynay** [comment]
Now that [DASState](#848) is almost implemented, we should consider the storing of errors for parallel `catchUp` workers whenever this issue is tackled.

**Comment by Bidon15** [comment]
We should revisit https://github.com/celestiaorg/celestia-node/issues/504 and close it if after implementation of parallelisation, the issue is not reproducible again
