### ISSUE TITLE
service/header: exchangeProtocolID should include network name from `params`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#493]
Currently, we have a static protocol ID for the HeaderEx protocol, meaning that peers from different networks(devnet, testnet, mainnet) can speak to each other and exchange invalid headers by the same heights. Instead, the protocol ID of HeaderEx(service/header/p2p_exchange.go:19) should contain the network the node is on(we do not allow a node to be on multiple networks at the same time).

**Comment by toanngosy** [comment]
Hi @Wondertan, I would like to work on this. Could you assign this to me?
