### ISSUE TITLE
[BUG]: Bitswap spams wantlist errors

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#498]
Multiple people on devnet reported this log being spammed consistently. I also have those 
![image](https://user-images.githubusercontent.com/22449364/156935879-cda0c9bc-21e8-4506-9f4d-93c7f705175d.png)

Currently, IDK what can cause this and this needs to be investigated.

**Comment by Bidon15** [comment]
Closing as not reproduced on latest version
