### ISSUE TITLE
ipld: Implement API for application sovereignty: query data per namespace

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#5]
## Summary

Application Clients (e.g. from ORUs) need a way to simply download all data specific to their namespace (application sovereignty). 

## Proposal

Add a simple library that traverses the NMT and returns all data of the requested namespace ID.

It might be valuable to consider adding an RPC endpoint for this too. E.g. for block explorers who want to serve Txs of certain applications (or ORU chains), too.

**Comment by renaynay** [comment]
Reimplement the API to retrieve shares by namespace referenced here: 
https://github.com/celestiaorg/celestia-core/pull/422

ADR for reference: [ADR-003](https://github.com/celestiaorg/celestia-core/blob/master/docs/adr/adr-003-application-data-retrieval.md)

**Comment by evan-forbes** [comment]
personal reminder to refactor and add back in these extra tests https://github.com/renaynay/celestia-core/pull/2, after we complete the main implementation.

**Comment by renaynay** [comment]
Resolved by #170.
