### ISSUE TITLE
node: embed `Core` node process into `Full` node 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#50]
We need a way to be able to embed a Core node process into the `Full` node so we don't have to start a `Core` node separately and pass in its RPC endpoint to the celestia node on initialisation. Ideally, via either the `Node` or the `rpc` component, we can control the lifecycle for the `Core` node (Start/Stop). 

This would not only help with testing, but is the desired end-goal for devnet (is to **default** run a "trusted" `Core` node alongside a `Full` node). This will of course be optional as we also have the goal to implement `Full` <> `Full` communication instead of only relying on a trusted `Core` node, but for now, our source of NewBlocks is from `Core` nodes and we must have some way of spinning them both up simultaneously with as little configuration on the user-side as possible.

**Comment by Wondertan** [comment]
The `Core` can be either embedded in the same proc or be a child sub-proc of a `node`.
