### ISSUE TITLE
ipld: add documentation for fetching shares

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#512]
After merging #442 and implementing #508, #509 the logic `ipld/read.go` will become too complicated. We should document each step in  `RetreiveData` to avoid misunderstanding and confusing in future.

**Comment by vgonkivs** [comment]
Related to #423

**Comment by Bidon15** [comment]
Grooming 16/11/2022:

Closing as irrelevant as we have completely redone the implementation 
Ref: https://github.com/celestiaorg/celestia-node/pull/623
