### ISSUE TITLE
[EPIC] Implement bad encoding fraud proofs

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#528]
This is an epic issue breaking down the requirements listed in the [Bad encoding fraud proof ADR](https://github.com/celestiaorg/celestia-node/pull/492). 

In order to fully implement the generation, validation, broadcasting and handling of BEFPs, the following components/features need to be implemented:

- [x] #529
- [x] #530
- [x] #531
- [x] #532
- [x] #533
- [x] #535
- [x] #536

**Comment by vgonkivs** [comment]
done 🍾
