### ISSUE TITLE
ci: lint often fails due to timeout being exceeded

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#53]
CI often fails due to `lint timeout exceeded`, like here: https://github.com/celestiaorg/celestia-node/pull/52/checks?check_run_id=3554301525#step:3:73

We already merged a pr (#49) to increase the timeout by 1 minute, but that didn't fix it.

**Comment by tzdybal** [comment]
In optimint I set limit to 5min, and it works most of the time ;)

**Comment by renaynay** [comment]
Will close this once I see lint stops failing due to timeout. PR #54 attempts to resolve this.

**Comment by renaynay** [comment]
Closing as this issue seems resolved on master
