### ISSUE TITLE
fraud: Implement FraudSub and integrate it into corresponding services

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#531]
Implement FraudSub based on the design described in [BEFP ADR](#492) and integrate with corresponded services:

- [x] Implement FraudSub service;
- [x] Integration of FraudSub  with Header verification(for light nodes);
- [x] Integration of FraudSub wit DASer(for full nodes);

**Comment by renaynay** [comment]
<img width="828" alt="Screenshot 2022-03-28 at 08 52 42" src="https://user-images.githubusercontent.com/41963722/160384437-f5805990-9a32-4529-bcfb-aaf6a0ff1103.png">

cc @vgonkivs
