### ISSUE TITLE
Confusing naming for bridge nodes and full nodes

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#548]
The [naming of full nodes and bridge nodes](https://github.com/celestiaorg/celestia-node/blob/main/docs/adr/adr-003-march2022-testnet.md#legend) are confusing. From [the ADR](https://github.com/celestiaorg/celestia-node/blob/main/docs/adr/adr-003-march2022-testnet.md#legend):

* A bridge node *is* a full node, which downloads blocks via celestia-core RPC.
* But a full node is also apparently another kind of node, that actually downloads data from the libp2p network.

This is confusing because firstly, "bridge node" doesn't sound like a full node but just some node _in between_ two different types of nodes.

Secondly, it's not clear what the relationship between "bridge node (that downloads data via RPC)" and "full node (that downloads data via libp2p)" is. Can a bridge node _also_ download data via libp2p, and does that mean therefore that a full node is a subset of a bridge node? If so, perhaps "bridge node" can be renamed to "full bridge node" or similar in the documentation, to make it clear that a bridge node is a superset of full node.

**Comment by Wondertan** [comment]
Bridge node doesn't download data over p2p network, it only provides data to it.

**Comment by musalbas** [comment]
Why not? If the full block isn't available, then it should ideally contribute to reconstructing the data by downloading the shares.

**Comment by mindstyle85** [comment]
My quick thoughts, as theres more issues with naming than just bridge/full node:

- essentially a validator is just running celestia-app and registering, however

- you want people to also run the bridge node along with it as it is a part of the stack

- currently the naming for running the full package is weird (bridge validator node, which consists of celestia app and bridge node)

We need to unify these names so its more clear what is what. Ideally the app and the bridge should run as a package (1 binary, if thats even possible).

Another way is to just name the package as Celestia node or Celestia validator, which includes celestia-app and the bridge, the difference between node and validator only being if you register as a validator or not.

**Comment by Wondertan** [comment]
@musalbas

> Why not? If the full block isn't available, then it should ideally contribute to reconstructing the data by downloading the shares.

We have Full Node for this purpose. Bridge Nodes seed on the DA network via a trusted connection to a Core Node, so we don't think of them as an independent entity, but a utility application/attachment to a Core Node that just bridge it to the DA network.

My original idea, was to name this Node as Validator Node, because from the DA network perspective Bridge Node is a fill validator node. WDYT about this naming?

I am ok to rename it to something that makes the most sense.

**Comment by musalbas** [comment]
So if you want to run a node on the same machine that is connected to both the Tendermint network and the libp2p network to help reconstruct blocks, you have to run both a bridge node and a full node? Isn't that kind of inefficient?

More importantly though, if a bridge node can't reconstruct blocks, I think the data reconstruction story isn't fully completed: when the full nodes reconstruct the blocks, they cannot be "fed in" back to the validator network running in celestia-core.

**Comment by musalbas** [comment]
Actually, I just remembered that if a data withholding attack was done by the validators then the validator set is malicious, as this would have required them to sign blocks they know they don't have the data for, so helping them to resume the chain wouldn't be necessary anyway. However, if people are running celestia-core nodes for other reasons like eg running a wallet or block explorer, then their node would stop unless they somehow manually import blocks back to celestia-core (a liveness attack). 1/3 of validators can already cause a liveness attack as part of the Tendermint threat model. However, we should further consider any issues caused by celestia-node having the data, but celestia-core not.

**Comment by qubelabsio** [comment]
> Another way is to just name the package as Celestia node or Celestia validator, which includes celestia-app and the bridge, the difference between node and validator only being if you register as a validator or not.

From what I've seen in the communities, most are indeed being confused the most by the Validator and Bridge names. Ideally, it would be best to have something like Validator Node / Full Node / Light Node which are already the most commonly used terms in other networks.

In the future, it would be also good to have some sort of Telemetry UI where members will be able to see statistics about the network and different types of nodes participating. Not sure if and when that would be possible but with some additional work, I believe it could give a good overall UX and a better understanding of the network to the community.

**Comment by Wondertan** [comment]
@musalbas, bridge node cannot do that as well. The connection between DA and Core networks is unidirectional and the is no way you can pipe the data from DA to the Core Network via Tendermint. So I don't think there is value in reconstruction from p2p for Bridge node if Core fails until the former is fixed. 
>  when the full nodes reconstruct the blocks, they cannot be "fed in" back to the validator network running in celestia-core

P.S. that I am now putting in every related discussion: IOTWAL(If Only Tendermint Was A Library)

**Comment by musalbas** [comment]
>The connection between DA and Core networks is unidirectional and the is no way you can pipe the data from DA to the Core Network via Tendermint.

Of course, because celestia-node is new software. But I don't see why a connection couldn't be implemented in practice.

**Comment by Wondertan** [comment]
True
> But I don't see why a connection couldn't be implemented in practice.

The limitation is on the tendermint/abci side, no matter how old celestial-node is.
> because celestia-node is new software

**Comment by renaynay** [comment]
@musalbas I think a lot of confusion comes from the ADR itself. I am going to update that now.

**Comment by renaynay** [comment]
@musalbas pls consult https://github.com/celestiaorg/celestia-node/pull/577 for a clearer explanation on the role bridge nodes serve in the DA network. 

An alternative name for bridge node can be `relay` node as the sole purpose of a bridge node is to relay celestia-core blocks to the DA network in a digestible format (as an `ExtendedHeader` that contains the `DataAvailabilityHeader`)

**Comment by Bidon15** [comment]
Grooming 20/09: @musalbas can you close this issue or we can do it on our own?
