### ISSUE TITLE
params: Node can be set for a private/other network type

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#550]
ATM, when the node is initialised,  it is automatically trying to connect to bootstrap peers that are serving for `devnet` network. 
We need more flexibility in setting up such parameter as `swamp` tests contains their own network and this is causing warnings on execution with messages like `can not connect to bootstrap peers` which are intended for another use-case. 

This behaviour is also effecting our ephemeral-cluster. 
Some refs can be found in `params/networks.go`

**Comment by Wondertan** [comment]
I thinking about ENV var that allows setting desired network preference

**Comment by liamsi** [comment]
What was the reason to not make this part of the config instead?

**Comment by Wondertan** [comment]
Configs, according to my experience, are something that users often play around with a lot, trying different things, etc. The network switch in the config is something I expected users to touch and break subsequently breaking the synchronization. But I might be overcautious.

**Comment by liamsi** [comment]
> . The network switch in the config is something I expected users to touch and break subsequently breaking the synchronization.

I think proper documentation makes this a non-issue. Can also happen with env vars.
