### ISSUE TITLE
das: Improve error handling of failed `catchUp` routine

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#554]
Right now, the `catchUp` routine logs an error and returns completely out of the `catchUpManager`, preventing the DASer from continuing to DAS past headers. In order to be able to DAS past headers again, the user would need to restart the node. For now, we log this as an instruction, but we need to have some sort of logic that will handle this error for the user. 

Solutions could include some retry logic and potentially the graceful shutdown of DASer and subsequently node. 

cc @Wondertan

**Comment by Bidon15** [comment]
Revisit on the next grooming session after #483 is done
Now we can get stuck in rebase issues if done in parallel

**Comment by Bidon15** [comment]
Grooming 16/11/2022:

Closing as we have completely redone the implementation of DASer
