### ISSUE TITLE
core: Remove embedded celestia-core node functionality from codebase

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#565]
As this functionality is largely unused and not of high priority, we will remove it entirely for the time being.

TODO: 
- [x] remove embedded functionality
- [ ] make `coreconfig.Remote` -> `coreconfig.Enabled`
- [ ] change state service construction in `baseComponents` to rely on whether core is enabled rather than remote
- [ ] make state service required on node

**Comment by Wondertan** [comment]
Closed by https://github.com/celestiaorg/celestia-node/pull/567

**Comment by renaynay** [comment]
Not quite - still needs https://github.com/celestiaorg/celestia-node/pull/573 to be fully resolved

**Comment by Wondertan** [comment]
Why is unoptional StateService required for removing embedded node?

**Comment by renaynay** [comment]
Not required but it was a blocker for it. Should have made separate issues.

**Comment by Bidon15** [comment]
Grooming 16/11/2022:

This is too old and we have removed all of it
