### ISSUE TITLE
share: test complex recovery scenarious 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#600]
We need to test the base case where:
* there are two full nodes on the network connected to each other;
* neither of them individually are connected to enough light nodes to reconstruct the block;
* but, together, they do have enough light nodes to reconstruct the block.

**Comment by liamsi** [comment]
Here is one proposal how the setup could look like: 
![image](https://user-images.githubusercontent.com/7441766/162189370-81460ea9-793e-4b77-8e1e-bc9accf78ec1.png)
This is meant to consistently and deterministically yield an integration tests that fulfils the test-case assumptions.

**Comment by liamsi** [comment]
Alternatively, you could achieve sth similar via the number of light nodes but probabilistically. If we do tests on a real network, we should be doing that I think.
