### ISSUE TITLE
[EPIC] E2E large block reconstruction test tracking issue

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#602]
- downloading blocks: 1mb, 2mb, 4mb (original data), maybe larger to see when things break
- DASing large blocks 
- downloading per namespace 
- etc

All these should be done on a real network ideally.

### TODO 
- [x] #266 
- [x] #702 
- [x] https://github.com/celestiaorg/test-infra/pull/27

**Comment by Wondertan** [comment]
Some figures captured by @musalbas on Mamaki testnet:
```
average times for 8x8: ~0.5s
average times for 16x16: ~1s
average times for 32x32: 3-5s
average times for 64x64: 5-10s
average times for 128x128: 10s-30s
average times for 256x256: 80-250s
```

**Comment by Bidon15** [comment]
Ref: https://github.com/celestiaorg/celestia-node/issues/1156
