### ISSUE TITLE
Use tagged releases for Celestia dependencies

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-node#606]

**Comment by liamsi** [comment]
currently:
https://github.com/celestiaorg/celestia-node/blob/16dba9747d46b8b26cffc9385054703b3a8d8b9c/go.mod#L9

**Comment by liamsi** [comment]
Also, it would be good if a linter could automatically check for this. So we won't miss these again. The line above was introduce in #420 and approved by 3 reviewers...

**Comment by Wondertan** [comment]
True, we should've caught this
