### ISSUE TITLE
build: Network Types

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#62]
## Goal
We should have software-level support for different network types, e.g. `celestia-devent` or `celestia-mainnet`

## Current solution
In upcoming https://github.com/celestiaorg/celestia-node/pull/57 this is solved by simply extending Config with a network type field.

## Desired solution
The network type should be hardcoded in binary, as different network types usually run over different software versions, and allowing users to manually change network type is a source of bugs coming from users joining a network with a software version we were not expecting.

**Comment by Wondertan** [comment]
We will also need to define and formalize a list of running network types with supporting bootstrap peers.

**Comment by renaynay** [comment]
Need a hardcoded list of peers for `DEVNET`.

**Comment by liamsi** [comment]
> In upcoming #57 this is solved by simply extending Config with a network type field.

I still think the easiest is to create a directory to contain the genesis & config file. It is common that these are either in a separate repo (example: https://github.com/osmosis-labs/networks) or in the main repo itself ([example1](https://github.com/umee-network/umee/tree/main/networks), [example2](https://github.com/osmosis-labs/osmosis/tree/main/networks)).

> Need a hardcoded list of peers for DEVNET.

I think a set of bootstrap peers could be part of the above directory.

**Comment by Wondertan** [comment]
@liamsi, It has to be part of the binary so its hash commits to network params

**Comment by jbowen93** [comment]
Based on my investigations over in [devops-test/devnet](https://github.com/celestiaorg/devops-test/tree/main/devnet) I'd recommend we only include the `genesis.json` and `gentx` files and *not* the config. 

See my recent PRs that moved from mounting config files to using a flag in [docker-compose](https://github.com/celestiaorg/devops-test/pull/51) and [k8s](https://github.com/celestiaorg/devops-test/pull/53).

If we wanted to provide a recommendation for initial peer setup I think we should use an `env` file.

**Comment by Wondertan** [comment]
Actually, hard coding genesis hash only would work well enough.
