### ISSUE TITLE
`GetSharesByNamespace` returns shares in non-deteministic order

### ISSUE THREAD

**Issue by tzdybal** [celestiaorg/celestia-node#621]
[`GetSharessByNamespace`](https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L153) spawns a goroutine for each `roodCID`, and results are returned via channel, and appended to an array:
https://github.com/celestiaorg/celestia-node/blob/28020da54d46b2dec29763a51c6c434b157e84dd/service/share/share.go#L188

Because of this, the order of returned shares is non-deterministic.

**Comment by Wondertan** [comment]
True, we didn't think about ordering once this was implemented. Thank your for reporting

**Comment by liamsi** [comment]
A good reminder that we shouldn't do any optimisations yet. And if, correctness goes obviously over any performance. Also optimisations must be backed by: 1) proof for an existing bottleneck and 2) benchmarks that show an actual improvement.

**Comment by Wondertan** [comment]
@limasi, this case is different from your reasoning. We didn't do this on purpose just because we wanted to optimize something, but that was Slava’s choice to contribute before he even joined. We just had an issue for this obvious thing to implement.

**Comment by Wondertan** [comment]
Furthermore, the issue still persists as per results and investigations out of https://github.com/celestiaorg/celestia-node/pull/626

**Comment by tzdybal** [comment]
> I suspect this boils down to the append we do in the recursive GetLeavesByNamespace, which we should do before going deeper into recursion rather than after to preserve the order.

Changing order in https://github.com/celestiaorg/celestia-node/blob/2e311d94ba2a84b75dafb73197e9259215bee7b4/ipld/read.go#L268 to `out = append(out, nds...)` indeed fixes the test. But it's just a happy one-liner, and more testing is needed.

**Comment by vgonkivs** [comment]
Did not see your comment @tzdybal :) 
I have changed the appending as you'd mentioned and test passes. Also, all unit tests for GetLeavesByNamespace pass

**Comment by vgonkivs** [comment]
But I don't see the reason why we should prepend fetched leaves instead of appending.
