### ISSUE TITLE
ipld: GetLeaves should return fetched shares even on error

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#650]
We use GetLeaves to retrieve shares of any row or column. Currently, it returns either all the shares in the success case or nothing, even if some shares were retrieved. To increase the success rate of reconstruction, we have to change this to (1) request as many shares as possible(configurable amount of blocking goroutines) at the same time and (2) return fetched ones.

**Comment by Wondertan** [comment]
Another way of doing so might be removing `GetLeaves` and making the logic part of `ipld.Retriever` implemented in https://github.com/celestiaorg/celestia-node/pull/623. This way downloading multiple rows and blocks(e.g. syncing) might be much more efficient in resource usage, as each data retrieval could reuse the same set of workers.

**Comment by renaynay** [comment]
@Wondertan was this closed by #623 ?

**Comment by Wondertan** [comment]
ehm, it will be closed by #682, there are related via GH
