### ISSUE TITLE
ipld: Consider removing the concept of a `Share` from ipld pkg 

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#666]
![Screenshot 2022-05-03 at 18 36 04](https://user-images.githubusercontent.com/41963722/166498997-61269082-0972-4379-a35e-146deedc86de.png)
![Screenshot 2022-05-03 at 18 36 25](https://user-images.githubusercontent.com/41963722/166499088-205538de-0449-4072-bf0f-f5cc63a20b86.png)

___________________________________________________________________________

![Screenshot 2022-05-03 at 18 37 28](https://user-images.githubusercontent.com/41963722/166499263-1b912f30-f3d3-40e7-91cc-842b18c187fa.png)

**Comment by liamsi** [comment]
@adlerjohn are you suggesting that the NMT should use a type `Share` instead of raw bytes? Mind opening an issue in NMT if so? Also what is a `Share` in the NMT context? a pair (nid, data) where nid and data are essentially bytes and both are essentially always the of same size?

**Comment by adlerjohn** [comment]
Yes to all the above

**Comment by renaynay** [comment]
Let's close this now in favour of consolidating `Namespace` among the three repos (nmt, node + app)
