### ISSUE TITLE
test: Ensure our tests are consistent in usage of `t.Cleanup` and `defer`

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#668]
Somewhere we use t.Cleanup and somewhere defer. Define which one to use and change the code to only use it. Especially in the context cancellation.

Ref: https://github.com/celestiaorg/celestia-node/pull/661#discussion_r863606108

**Comment by saudch007** [comment]
Can I work on this one? @Wondertan @renaynay

**Comment by Wondertan** [comment]
Hey @saudch007. Thanks for your interest. In general, you don't need to ask for permission to work on any issue. Choose the issue you like the most and submit a PR🙂
