### ISSUE TITLE
cmd/celestia: change randomness seed

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#678]
Changes randomness seed in the main so that it is not deterministic via `rand.Seed`. Specifically, this way, Full Nodes will sample quadrants randomly. The whole change is as simple as the following:
```go
import rand
...
func main() {
	rand.Seed(time.Now().UnixNano())
	...
}
```

**Comment by liamsi** [comment]
Doesn't this use crypto/rand? Please do if real randomness is an actual concern here.

**Comment by adlerjohn** [comment]
Using insecure randomness could open the door for interesting attacks where if an attacker knows a node's clock they'll know which quadrant will be sampled.

**Comment by Wondertan** [comment]
There are 8 quadrant in total. 4 for each row/col axis. The randomness here defines the order of those quadrants for retrieval from disk or network until the square is reconstructed.

Why is crypto randomness a concern for the above? Why knowing which quadrant you sample is an attack?
