### ISSUE TITLE
docker: Create CI pipeline to build docker image and push on every release to dockerhub

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#68]
Create a way for us to build a new docker image on every release and push it to dockerhub for easy pull + testing.

**Comment by jbowen93** [comment]
Let's use Github's built in [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) for this. It allows us to have all artifacts in a single page. See [devops-test](https://github.com/celestiaorg/devops-test/pkgs/container/devops-test) as an example.
