### ISSUE TITLE
Enable automatic deletion of head branches

### ISSUE THREAD

**Issue by adlerjohn** [celestiaorg/celestia-node#687]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by renaynay** [comment]
Or we could all just use forks instead :) is nice and clean

**Comment by liamsi** [comment]
Just checked, already on:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7441766/168421317-95c7f219-afed-4f35-8f48-86d7bbac47d1.png">
