### ISSUE TITLE
docker: Create docker image for Celestia-Node

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#69]
Create a docker image for `celestia-node` binary. This issue is **blocked** until we have an executable.

**Comment by sysrex** [comment]
I can help with this, and create an initial docker file

**Comment by Bidon15** [comment]
Hey @sysrex, thank you for being pro-active here 🥳 
Please, go ahead with the initial PR for this - this will be awesome

**Comment by jbowen93** [comment]
Hey @sysrex what's your status on this? I just threw together a quick Dockerfile for my own uses. 
```
FROM ubuntu:latest
RUN apt update
RUN apt install -y git wget make gcc

# Golang stuff
RUN wget -P /tmp https://golang.org/dl/go1.17.3.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf /tmp/go1.17.3.linux-amd64.tar.gz
RUN rm /tmp/go1.17.3.linux-amd64.tar.gz
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

# Clone from private repository
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh git clone git@github.com:celestiaorg/celestia-node.git

# Celestia node stuff
WORKDIR "/celestia-node"
RUN make install
WORKDIR "/"
CMD celestia dev start
```
Build on M1 Mac: `docker build --ssh default --platform linux/x86_64 .`
Run on M1 Mac: `docker run -it --platform linux/x86_64 <image sha>`

**Comment by renaynay** [comment]
@jbowen93 would you be able to make a PR for this (under new dir `docker` with README.md and this `Dockerfile`) 🙏🏻

**Comment by jbowen93** [comment]
This is resolved by https://github.com/celestiaorg/celestia-node/pull/295
