### ISSUE TITLE
ipld: concurrent GetSharesByNamespace

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#697]
Stricly an optimization that would speed the time it takes to fetch shares for a namespace. Currently, we do it sequentially. The way to approach this should be taken from https://github.com/celestiaorg/celestia-node/pull/682

**Comment by renaynay** [comment]
Is this issue resolved? @Wondertan Or is there some other optimisation you're thinking of? If so, can you describe?

**Comment by Wondertan** [comment]
No, it is not implemented. Take another look at the new concurrent `GetShares`(https://github.com/celestiaorg/celestia-node/pull/682).`GetSharesByNamespace` can be concurrent in the same way to speed up fetching. Right now, it is sequentially via recursiveness.

**Comment by distractedm1nd** [comment]
How important is the order of the shares returned when we're just retrieving for a namespace?

**Comment by Wondertan** [comment]
> How important is the order of the shares returned when we're just retrieving for a namespace?

It is _really_ important. Applications encode custom data that is spread over multiple shares, and if shares are in the wrong order, then the application won't be able to decode things correctly. We had a bug in the past regarding the order, that was breaking Optimint
