### ISSUE TITLE
Cleanup global variables

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#709]
In multiple places in the code, we rely on global variables, which is usually not that bad but has its downsides. Eventually, we should allocate some time to clean them up, which includes:
* "Deglobalization" of vars. It should be straightforward to configure those via direct optionable configuration of the structs/logic that those vars affect. Currently, it's not obvious to newcomers that those do exist and that they can be configurable.
* Pass those options/direct configurations into the Node configs, so that node operators can control them and fine-tune 
according to their setup
* Consistent naming

**Comment by Bidon15** [comment]
Putting into Q3 Roadmap as we have a refactoring planning ahead

**Comment by derrandz** [comment]
I think we can close this @Wondertan
