### ISSUE TITLE
[bug] node/rpc: `DefaultConfig()` for rpc is never invoked for users running older version of node

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#718]
From @tzdybal: 

> I found one issue - default config is not used. and you need to explicitly set --rcp.port to be able to use RPC endpoints.  After debugging, found that config is empty, and DefaultConfig is never invoked.
> After removing existing config and running `init`, finally default RPC port is set. But this means you need to manually merge configurations on update, etc

Ref: https://github.com/celestiaorg/celestia-node/pull/696

**Comment by Bidon15** [comment]
Ref: https://github.com/celestiaorg/celestia-node/issues/895

**Comment by renaynay** [comment]
Resolved by #997 `Validate` functionality on the config(s)
