### ISSUE TITLE
service: Add flag for stopped services

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#724]
We should add a flag that will prevent the service from being stopped twice.

#Why
Currently, all our Stop calls depends on fx.Lifecycle which guarantees it will be called once. Receiving of BEFP also cause service stopping. The second Stop call can either crash or freeze the node.

**Comment by vgonkivs** [comment]
As discussed with @Wondertan and @renaynay we should properly design such service and after that start implementation. We agreed that stopping flag  is not enough for a separate service and it should include more features.

**Comment by Wondertan** [comment]
> Currently, all our Stop calls depends on fx.Lifecycle which guarantees it will be called once. Receiving of BEFP also cause service stopping. The second Stop call can either crash or freeze the node.

This was fixed by https://github.com/celestiaorg/celestia-node/pull/2091, so closing
