### ISSUE TITLE
fix(gateway): Ensure r.Context is getting canceled once the processing of the request ends with error or success or anything else.

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#726]
Pls double check that this Context is getting canceled once the processing of the request ends with error or success or anything else. If is not closed automatically, then we need to add to each handler:
```go
ctx, cancel := context.WithCancel(r.Context())
defer cancel()
```

_Originally posted by @Wondertan in https://github.com/celestiaorg/celestia-node/pull/723#discussion_r874813310_

**Comment by Wondertan** [comment]
Yeah, otherwise we leaking resources in most cases.
