### ISSUE TITLE
chore/tests: create dockerfile that replicates close to CI env

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#731]
Currently, tests have a completely different behaviour locally(tbe for macOS) comparing to what we have in CI. 
Thus creating a dockerfile that is replicating CI like behaviour locally for tests execution is beneficial. 

The dockerfile should just contain:
- env/args vars for which type of tests are executed(unit/swamp/race/non/race)
- tailoring to our makefile

**Comment by Wondertan** [comment]
@Bidon15, should we move this to some devops repo?
