### ISSUE TITLE
org: Create a code of conduct doc

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#75]
We need to identify what is the code of conduct for celestia to inform future contributors what are the rules and the processes of moderation

A good example/starting point to start reading is from [tendermint's coc](https://github.com/tendermint/tendermint/blob/master/CODE_OF_CONDUCT.md)

**Comment by liamsi** [comment]
@YazzyYaz do you think we should have one? If so, this is not only node-specific but should be applied across repos. Can we close this otherwise?

**Comment by YazzyYaz** [comment]
@liamsi yes, we should definitely have one.

We can use one like this https://www.contributor-covenant.org/

We can also add it to our docs.

**Comment by YazzyYaz** [comment]
@renaynay it's in this PR https://github.com/celestiaorg/docs/pull/50

**Comment by renaynay** [comment]
Awesome -- we should link to it in our README once it's merged

**Comment by YazzyYaz** [comment]
It's merged: https://docs.celestia.org/community/coc

**Comment by renaynay** [comment]
Awesome

**Comment by renaynay** [comment]
https://docs.celestia.org/community/coc
