### ISSUE TITLE
[Feature Request | Swamp]: Bridge Nodes should have 1 per 1 ratio to CoreClients instead of using 1 CoreClient for N BNs

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#750]
### Implementation ideas

With current implementation of swamp, all Bridge Nodes share 1 CoreClient created by the swamp. 
This is causing issues with subscriptions that are failing test logic. 

Current approach should be adapted to new ration of M-M to mitigate this behaviour. 

H/t @Wondertan for the finding

Ref: https://github.com/celestiaorg/celestia-node/pull/736

**Comment by Bidon15** [comment]
For the record: on older versions of tendermint/core this behaviour was not reproduced 🧐

**Comment by renaynay** [comment]
Is this still an issue? I don't think we should be spinning up that many core nodes for our swamp tests FWIW. It shouldn't be necessary and it's quite heavy weight.

**Comment by Bidon15** [comment]
Agreed, considering that we have now knuu for that purposes. Closing as not planned
