### ISSUE TITLE
params: Decide on how to set and provide the current network of the node

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#754]
Currently, we use the `defaultNetwork` variable inside the `params` pkg to store the name of the current network (whether it is truly the default network used by the node, or `Private`, or some network set by `CELESTIA_CUSTOM`.

We need to decide how we will 1. manage networks, and 2. provide current network information to the rest of running services, which is now necessary with the change introduced in #753 .

**Comment by Bidon15** [comment]
Closing as we have a diff strategy
