### ISSUE TITLE
tests: flaky TestMakeExtendedHeaderForEmptyBlock

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#759]
![image](https://user-images.githubusercontent.com/22449364/170253618-f657cd76-0402-4675-a258-c2302b7c72ec.png)

**Comment by renaynay** [comment]
Is this closed by #756 @Wondertan ?

**Comment by Wondertan** [comment]
No, look at the PR linked. I saw this for the first time while was fixing other flakiness. It is rarible and happens only on full moon with a small chance.

**Comment by Bidon15** [comment]
Same error msg as here: https://github.com/celestiaorg/celestia-node/issues/759

**Comment by renaynay** [comment]
closing as haven't seen in a long time
