### ISSUE TITLE
Passing IP Address with a https://, tcp:// or http:// prefix results in "Too Many Colon" Error

### ISSUE THREAD

**Issue by YazzyYaz** [celestiaorg/celestia-node#766]
### Celestia Node version

latest

### OS

Ubuntu

### Steps to reproduce it

```sh
celestia bridge start --core.grpc http://localhost:9090
```

will result in an error of too many colons but:

```sh
celestia bridge start --core.grpc localhost:9090
```

won't.

It would be good to have both options supported from a UX point of view.

### Expected result

```sh
celestia bridge start --core.grpc http://localhost:9090
```
Should work

### Actual result

Only

```sh
celestia bridge start --core.grpc localhost:9090
```
works

**Comment by dabit3** [comment]
+1 on this. Right now if a user follows the docs exactly as they are, they will run into this issue when attempting to interact or query the local network when running a Celestia light node:

Running:
```
curl -X GET http://127.0.0.1:26658/balance
```

Returns

```
"querying client for balance: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address http://143.198.7.120:9090: too many colons in address\""root@nader-light-recording:~/celestia-node#
```

**Comment by Wondertan** [comment]
Cc @renaynay

**Comment by renaynay** [comment]
@dabit3 for the second command, you're trying to connect to a validator running on localhost:9090

**Comment by dabit3** [comment]
@renaynay hey thank you, I've updated my comment, I guess my issue ends up being the exact same as Yaz and the curl command works when `--core.grpc` is set without `http://` or `https://` prefix

**Comment by renaynay** [comment]
@dabit3 in your updated comment, the commands are the same. 

Also, I've tried to reproduce on main, but when I run 
```
 ./build/celestia light start --core.grpc https://rpc-mamaki.pops.one:9090
```
It works just fine.

Please make sure you're running on the latest `main` and see if the issue persists.
