### ISSUE TITLE
Probably not the correct way ./cel-key is looking at keys?

### ISSUE THREAD

**Issue by mindstyle85** [celestiaorg/celestia-node#784]
### Celestia Node version

Semantic version: v0.3.0-rc1-7-g45f23d8 Commit: 45f23d8ecab4c3526a7729cd4bc9a0ebe561846e

### OS

Ubuntu 20.04

### Steps to reproduce it

I was trying to find my key's address that the bridge node generated for me when i started it. In the end i managed to fetch it by:

`./cel-key list --home /home/pops/.celestia-bridge/keys/ --keyring-backend=test`

while using:
`./cel-key list --node.type bridge`
got me the list of celestia-app keys, same as it would without the node.type flag

### Expected result

`./cel-key list --node.type bridge` fetches the bridge's keys, not celestia-app's

### Actual result

n/a - see above

**Comment by renaynay** [comment]
@mindstyle85 

Can you try 

```
./cel-key list --node.type bridge --keyring-backend test
```
 and let me know if it outputs the correct keys?

**Comment by mindstyle85** [comment]
yeah this works, let me change it in the PR

**Comment by renaynay** [comment]
Can you link pr pls?

**Comment by renaynay** [comment]
Can I close this? @mindstyle85

**Comment by mindstyle85** [comment]
ah, yeah sure let me do it :)
