### ISSUE TITLE
flaky TestSharesAvailable_Full

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#787]
![image](https://user-images.githubusercontent.com/22449364/171441706-ba0f6b13-4775-4f06-81d0-901017fb8f84.png)

**Comment by liamsi** [comment]
A simple while loop and dumping the shares when the test fails (e.g. by temporarily introducing a global var for that) could get the job done (in a hacky way). I'm currently running `while go test -v -test.run TestSharesAvailable_Full; end` for this. Will dump any test-vector here. It's easier to reproduce with a 32x32 square but that yields a massive test-vector.

**Comment by liamsi** [comment]
These shares are used in one faileing test: https://gist.github.com/liamsi/34bb1269e311392184581c0191c1cfab

**Comment by adlerjohn** [comment]
Yeah, there's no way to pinpoint any bugs without shares to repro

**Comment by liamsi** [comment]
Yeah, the problem is that even with the shares above (with which the test failed), I can not repro the failure. So the bug must either really be in the decoding of rsmt2d (unlikely), or, in the Retrieve method itself (more likely because go-routines are almost the only source of non-determinism here).

**Comment by liamsi** [comment]
So if I ran my modified test with the same testvector it also passes +99% of the time. But also fails rarely with:
```
2022-06-02T02:41:52.420+0200	ERROR	share	share/full_availability.go:35	availability validation failed	{"root": "cXf4EqqtzHAJxmfZmEG91DaH+4mtJ6SppB2A3kq2/iQ=", "err": "byzantine error. isRow:false, Index:16"}
    full_availability_test.go:39: 
        	Error Trace:	full_availability_test.go:39
        	Error:      	Received unexpected error:
        	            	byzantine error. isRow:false, Index:16
        	Test:       	TestSharesAvailable_Full_TC
```
So it is not really reproducible via the input. The only interesting thing about this is that it is also the same Index, namely 16 as in Hlib's screenshot. Maybe additionally a stack trace whenever we encounter an unexpected byzantine error could help here.

**Comment by liamsi** [comment]
@Wondertan how do I print out the debug logs during tests? Specifically this one:
https://github.com/celestiaorg/celestia-node/blob/1c45a6659733b00efcc5b0f47f8ae64f30363e33/ipld/retriever.go#L151

**Comment by liamsi** [comment]
My hypothesis is that the bug is somewhere in https://github.com/celestiaorg/celestia-node/blob/1c45a6659733b00efcc5b0f47f8ae64f30363e33/ipld/retriever.go#L60 and not in rsmt2d

It could also simply have to do sth with the last quadrant but then I would expect we would see this more often.

**Comment by liamsi** [comment]
Also, when I always fetch from the 1st quadrant by commenting out this line:
https://github.com/celestiaorg/celestia-node/blob/e8751aa194b850bbb0ce71b48a38d6b50f0946d2/ipld/retriever_quadrant.go#L74-L75
It also works more reliably. Do I use the last quadrant  (by not shuffling and explicitly using it) and with width 32, the test reliably fails.

**Comment by Wondertan** [comment]
@liamsi, I also believe this is something with retrieval logic and not with rsmt2d. I am able to reproduce the issue in my reconstruction tests in https://github.com/celestiaorg/celestia-node/pull/702 now. Moreover, they always fail with the same error which was not the case before. 

Now I am trying to understand which PR caused the regression. My first suspect was https://github.com/celestiaorg/celestia-node/pull/738, but it was merged after the issue appeared, so it is not it. Continue investigation

**Comment by Wondertan** [comment]
Some alpha https://github.com/celestiaorg/rsmt2d/issues/83 fixes the bug completely.

**Comment by Wondertan** [comment]
The current workaround is to reimport the square each reconstruction attempt.

**Comment by Wondertan** [comment]
Mainly we need the share to be set like [this](https://github.com/celestiaorg/rsmt2d/blob/master/datasquare.go#L245-L246), so it's set into axis slice.

**Comment by Wondertan** [comment]
I was able to deflake the test and reproduce the issue with 100% chance. Then to see how reimporting fixes it.

**Comment by adlerjohn** [comment]
What is the bug specifically?
