### ISSUE TITLE
ci: pull requests template

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-node#79]
- [ ] Create a pull request template
- [ ] ~~Look into how to stop issue to be closed automatically on merging of linked PR~~

EDIT: MSevey Nov 2, 2022, cross out outdated action item

**Comment by Wondertan** [comment]
Nice to have sections:
* Context/Background/Goal/Rationale
* Changes/Content
* TODOs

**Comment by Bidon15** [comment]
cc: @MSevey we have been thinking about this for quite some time 😅
