### ISSUE TITLE
ipfs: more light-weight node

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#8]
Currently, we spin up a full ipfs node which is kinda bloated for what we are trying to achieve. 

@Wondertan brought up some very good alternatives:

 - https://github.com/hsanjuan/ipfs-lite the most barebones approach that would e.g. allow use using the the same data store as for the tendermint Store (#182) but it require providing a DHT and libp2p host
 - https://github.com/ipfs/go-ipfs-http-client is an alternative http client which fully implements the IPFS CoreAPI - this is quite the opposite of the above but it's still interesting to consider this, as it would very easily allow nodes to run ipfs in a different process (not together with the tendermint node, maybe even on a different machine)

We should carefully understand the pros/cons before we jump into either of these. I'm leaning towards the first approach as it is the most light-weight and gives us more freedom on how to interact with ipfs. It would especially be the most reasonable approach if we ever go all-in and replace the tendermint p2p stack with something libp2p based. This is also related to the work over at optimint: https://github.com/lazyledger/optimint/labels/C%3Ap2p

**Comment by Wondertan** [comment]
We agreed upon using only required protocols from IPFS and that's even more lightweight than ipfs-lite, so I am closing this.
