### ISSUE TITLE
header/sync: Syncer stalled for a long time on fetching header 37294.

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#803]
Light node stalled for about 10 minutes at local height 37293 even though it is receiving new pending heads from the network.

A sync routine was kicked off: 

```
2022-06-08T11:41:50.402Z	INFO	header/sync	sync/sync.go:257	syncing headers	{"from": 37292, "to": 37298}
```

Sync was stalled on fetching header 37294 for about 10 minutes even though general node connectivity was fine.

**Comment by renaynay** [comment]
Also another thing: 

shut down the node (last `new head` log was at 37295, but once i restarted the node, the loaded head was at 37229: 

```
2022-06-08T12:13:18.819Z	INFO	header/store	store/store.go:161	loaded head	{"height": 37229, "hash": "055C9AC284DB27AA69B23920A55F9BDC3ED51FEADF313FFA8E0785549DAB5C83"}
```

**Comment by Wondertan** [comment]
@renaynay, I think we can close this as we discovered that slowness was a combination of DO issues + one core only.

**Comment by Wondertan** [comment]
Regarding the new head mismatch. Are you sure you didnt close the node with two CTRL+C's? If so, then the head mismatch problem is unravelled, because second ctrl+c prevents all the writes and closes the node immediately.

**Comment by renaynay** [comment]
I am not 100 percent sure but let's close issue regardless. If it comes up again, we can reopen.
