### ISSUE TITLE
fraud: Service interface and serialization

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#813]
There was a discourse about the `fraud.Service` interface and about it being too abstracted. It seems like the main source of confusion was about these two methods, which _pollute_ the `Subscriber` interface:
```go
	// RegisterUnmarshaler registers unmarshaler for the given ProofType.
	// If there is no unmarshaler for `ProofType`, then `Subscribe` returns an error.
	RegisterUnmarshaler(ProofType, ProofUnmarshaler) error
	// UnregisterUnmarshaler removes unmarshaler for the given ProofType.
	// If there is no unmarshaler for `ProofType`, then it returns an error.
	UnregisterUnmarshaler(ProofType) error
```

Instead, the interface should be simple and have only `Subscribe` method. The long-term idea that @vgonkivs and I discussed was about generics that properly fix this. And while having this in my mind, we thought it would be fine to keep those for a release or two until generics become fully stable. However, @renaynay and @liamsi were a bit out of the loop and did not agree that those serialization methods are good to be kept(correct me if I am wrong) and raised a concern. 

For us to be on the same page and alleviate the concern. I propose 3 ways on how we can proceed with this, besides keeping this as it is:
1. Remove those methods from the `Subscriber`, then register and keep them on the pkg level globally(this was the original idea in my head until I suggested @vgonkivs to make it runtime rather than build time). Basically, instead of those methods, we would have: 
	  ```go
	  package fraud 
	  
	  func RegisterProofUnmarshaller(ProofUnmarshaler)) 
	  func Unmarshal([]byte) Proof
	  ```
	and next to BEFP or any other FP, there would be an init func that would do `RegisterProofUnmarshaller` for the FP type.
2. Simply remove those methods from the `Subscriber` interface but keep those methods on the implementation. Nothing really changes from the current implementation, while we have a less polluted/cleaner interface + no global state.
3. Wait for generics

I prefer 2, as it keeps things cleaner with minimal changes. The long-term approach is still generics, but it is a completely different story.

**Comment by vgonkivs** [comment]
The question is when are we going to update go to 1.18?

**Comment by Wondertan** [comment]
We haven set any rules about that. Maybe once 1.19 come in or we can do it before release.

**Comment by Wondertan** [comment]
I think is fixed now, and we settled on serialization for frauds, so closing. 
Please reopen if I missed something
