### ISSUE TITLE
tests(share): enable race detector for reconstruction tests once we migrate to go1.19 

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#825]
The tests were introduced in https://github.com/celestiaorg/celestia-node/pull/702

**Comment by Wondertan** [comment]
As https://github.com/celestiaorg/celestia-node/pull/1067 landed, we can now enable a race detector for those files.

**Comment by ramin** [comment]
integration tests have been reworked with race enabled/disabled where flakeyness allows
