### ISSUE TITLE
service: Implement processing of BadEncodingFraudProof and StateFraudProof

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/celestia-node#84]
Implement processing of BadEncodingFraudProof and StateFraudProof to check if the fraud proof is valid or not.

If a fraud proof is valid, the node should halt (https://github.com/celestiaorg/celestia-node/issues/82). This is because, under Tendermint BFT:
* in order for a fraud proof to be valid it must be in a block that has consensus, which means it must be signed by 2/3 of validators;
* in order to "replace" that invalid block which has consensus, 2/3 of validators must equivocate;
* if 2/3 of validators equivocate, Tendermint halts and kicks into "manual recovery" mode (https://blog.cosmos.network/the-4-classes-of-faults-on-mainnet-bfabfbd2726c).

**Comment by liamsi** [comment]
Full nodes will also halt, we need to think about who will actually be around in the network to notify light nodes
some copy pasta from slack:
> ismail: if everyone immediately stops the node whenever they see a fraud proof, aren’t odds hight that a) the fraud proofs does not gossip the fraud proof fast enough and b) especially for historic headers no one will be left to actually serve that fraud proof?
> hlib: Should sharing the fraud proof to your peers before stopping solve this?

**Comment by adlerjohn** [comment]
By induction, only a single block is needed to be proven invalid, and that block is exactly the one that halts the full nodes. There is no need to produce fraud proofs for blocks that descend from that first invalid block, even if they themselves are invalid. The process of halting on an invalid block MUST also produce a fraud proof, and that fraud proof alone is sufficient for allowing light nodes to orphan all descendant blocks.

**Comment by renaynay** [comment]
Closing in favour of https://github.com/celestiaorg/celestia-node/issues/528
