### ISSUE TITLE
header/store: Use `RLock` instead of `Lock` inside `Append` during adjacency verification

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#864]
Ref https://github.com/celestiaorg/celestia-node/issues/861#issuecomment-1167378119

**Comment by Wondertan** [comment]
While `syncLoop` syncs and appends new headers to the store, the Lock might betaken by the `processIncoming` in Syncer for a fraction of a millisecond on every new header rcvd from the network, every  ~30-60sec, which is negligible so I would say this have pretty low priority and very minor optimization.
