### ISSUE TITLE
das: fix remaining comments on #849

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#869]
![image](https://user-images.githubusercontent.com/22449364/176209904-72d37730-9db8-4a01-9ff3-20f8cf5a91a6.png)

**Comment by Wondertan** [comment]
Assigning you, so you can also double-check the correctness of logs there.

**Comment by renaynay** [comment]
Fixed in #848

**Comment by distractedm1nd** [comment]
#848 was closed, I think this issue can be closed as well
