### ISSUE TITLE
node: Separate out construction of `CacheAvailability` into separate function that accepts an `Availability`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#879]
Separate out construction of `CacheAvailability`, have it accept a general availability. 

[Here](https://github.com/celestiaorg/celestia-node/blob/main/node/services/service.go#L171-L176) and [here](https://github.com/celestiaorg/celestia-node/blob/main/node/services/service.go#L181-L186)

**Comment by distractedm1nd** [comment]
Hey renaynay, could I get a bit more context here? Would `services.FullAvailability` and `services.LightAvailability` even need to exist then, or could we just use `share.NewFullAvailability` and `share.NewLightAvailability` instead?

Or alternatively, is this more like what you meant? 
```go
// LightAvailability constructs light share availability wrapped in cache availability.
func LightAvailability(
	lc fx.Lifecycle,
	bServ blockservice.BlockService,
	ds datastore.Batching,
) share.Availability {
	la := share.NewLightAvailability(bServ)
	ca := share.NewCacheAvailability(la, ds)
	return ca
}

// FullAvailability constructs full share availability wrapped in cache availability.
func FullAvailability(lc fx.Lifecycle, bServ blockservice.BlockService, ds datastore.Batching) share.Availability {
	fa := share.NewFullAvailability(bServ)
	ca := share.NewCacheAvailability(fa, ds)
	return ca
}

func CacheAvailability(lc fx.Lifecycle, ds datastore.Batching, avail share.Availability) *share.CacheAvailability {
	ca := share.NewCacheAvailability(avail, ds)
	lc.Append(fx.Hook{
		OnStop: ca.Close,
	})
	return ca
}
```

**Comment by renaynay** [comment]
Yes you're right regarding the `fx` package. The issue is that fx does not accept two instances of the same type, in this case, `share.Availability`.

**Comment by distractedm1nd** [comment]
ok thanks sounds fun will report back
