### ISSUE TITLE
p2p: limit the number of routines(to handle new peers) during peer discovery

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#883]
Initially proposed by @Wondertan :

We need to limit the number of possible routines. Some adversaries could create bots advertising them as "full" which would eventually over spawn the number of routines. The problem would also be visible on big networks in normal operation, but it is still there.

The easiest solution: just do a buffered throttling channel. Write to it once handling started and read on the finish. This way the buffer of the chan would be a limit of concurrent routines/handlers/connectors.
A bit more work, while more efficient is to preallocate a limited number of workers who rcv handling jobs from findPeers.

Supplement for #599

**Comment by Wondertan** [comment]
We rewrote discovery, and we now have a goroutine limit there, so closing 

#2117
