### ISSUE TITLE
Auto generate binaries for different platforms on releases

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#885]

**Comment by iofq** [comment]
What platforms would we target? amd64, arm64, windows, mac?

Currently we don't tag any docker builds besides sha commit tags, would `latest` and semver tags be appropriate on release?

What would the preferred release workflow be? Create a release and then upload assets during the workflow? Or create a semver tag, have the workflow create a release draft with assets attached, and then finalize that release manually?

**Comment by renaynay** [comment]
> What platforms would we target?

amd64, arm64 and mac are higher prio -- windows would also be cool :) 

> Currently we don't tag any docker builds besides sha commit tags, would latest and semver tags be appropriate on release?

Yes ( cc @sysrex ) 

> What would the preferred release workflow be? Create a release and then upload assets during the workflow? Or create a semver tag, have the workflow create a release draft with assets attached, and then finalize that release manually?

@sysrex @Wondertan do you guys have any thoughts? I think we should go with the latter?

**Comment by iofq** [comment]
Following up on this:

For windows, the [fslock package](https://github.com/celestiaorg/celestia-node/tree/main/libs/fslock) doesn't appear to support windows yet, which would need to happen first.

For mac/darwin, a dependancy of libp2p, [elastic/gosigar](url), doesn't want to build under `GOOS=darwin` for me. But I may be missing something here.

**Comment by Wondertan** [comment]
@iofq, true, I just tried me to cross-compile for darwin and saw the same issue with gosigar. This is weird because I know some of our folks are using mac with no issues

**Comment by Wondertan** [comment]
Ok so this is definitely related: https://github.com/elastic/go-sysinfo/issues/127

**Comment by renaynay** [comment]
I've run into issues with gosigar before and basically had to fork and maintain a fork of gosigar in order to prevent this issue. It was a long time ago though.

**Comment by renaynay** [comment]
https://github.com/gballet/gosigar

go-ethereum used to indirectly depend on it I think bc of this dep: https://github.com/olebedev/go-duktape which has since been deprecated.

**Comment by ramin** [comment]
closing this issue as it was taken care of by https://github.com/celestiaorg/celestia-node/pull/2661. once we have ci/release flakey tests passing and the entire release process continues we'll have the binaries
