### ISSUE TITLE
lint: Add structslop linter to golangci-linter

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#893]
The linter(https://github.com/orijtech/structslop) would allow us to do small but on a big code scale noticeable optimizations and would in general teach our devs how fields on the structs should be organized with performance in mind. Also, the feasibility of adding it to the golangci-linter needs to be double-checked.

**Comment by liamsi** [comment]
I think that is fine as long as readability always has priority over the optimal memory layout.
