### ISSUE TITLE
IPLD: Optimize network roundtrips

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-node#9]
Consider using [graphsync](https://github.com/ipfs/go-graphsync/blob/master/docs/architecture.md) instead of [bitswap](https://docs.ipfs.io/concepts/bitswap/)

- gaphsync spec: https://github.com/ipld/specs/blob/master/block-layer/graphsync/graphsync.md
- graphsync architecture: https://github.com/ipfs/go-graphsync/blob/master/docs/architecture.md
- bitswap: https://docs.ipfs.io/concepts/bitswap/

Note that this currently has low priority. Only in case bitswap performs unacceptably for our case (which does not seem like it does: https://github.com/lazyledger/ipld-plugin-experiments/pull/9#issue-545035075), we need to reprioritize this before launch.

**Comment by Wondertan** [comment]
NOTE: The current preferred trajectory is designing our own protocol

**Comment by adlerjohn** [comment]
Can we close this then?

**Comment by Wondertan** [comment]
Not sure. Closing this means we are not considering/investigating this vector which requires a consensus of all leadership teams.

**Comment by liamsi** [comment]
I think for initial block sync from the DA network we can simply roll our own protocol. But even for that we need some evidence that just using bitswap is too slow first. I think the experiments that @Bidon15 is working on will clarify this.
Also, I think we can close this issue as it is not specific enough for now and not really actionable?

**Comment by Wondertan** [comment]
SGTM
