### ISSUE TITLE
node: host is not closed if it was passed via option

### ISSUE THREAD

**Issue by vgonkivs** [celestiaorg/celestia-node#902]
We are replacing `libp2p.Host` in case of passing it through the [option](https://github.com/celestiaorg/celestia-node/blob/0374d4fdcefd7a2e719aa80234aa8dd24d4fb837/node/settings.go#L64) so it is not closed properly by lifecycle when node stops.

**Comment by Wondertan** [comment]
There is a question here that needs to be answered. Who is responsible for the lifecycle of a dependency given as an option? 

Managing it ourselves is less error-prone for our code while it might cause problems for the user. However, though, if probably documented, the user will be glad to do do less work, delegating lifecycling to us, while we have better control.

The soon-to-be-released FX feature to add lifycling through annotations will facilitate the fix here.

**Comment by Bidon15** [comment]
Ref: https://github.com/celestiaorg/celestia-node/issues/923

**Comment by renaynay** [comment]
This can be closed

**Comment by Wondertan** [comment]
I am not sure we closed it. The lyfecycling for provided hosts is not figured out
