### ISSUE TITLE
node/config: All time related config fields are in nanoseconds

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#912]
The default values for `GracePeriod` and `RoutingTableRefreshPeriod` are set as `time.Minute`, however, in the config it is written in nanoseconds which is not very human-friendly.

Instead, it should be a string that is parsed via `time.ParseDuration`

**Comment by Wondertan** [comment]
Tentatively assigning @vgonkivs

**Comment by HoytRen** [comment]
It seems this is done? in the config.toml, I see 'GracePeriod = "1m0s"', and I believe it's spf13/viper handling the duration string.

**Comment by derrandz** [comment]
Yeah I suppose this is done cc @Wondertan
