### ISSUE TITLE
cmd: shutdown for OTel exporters

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#935]
OTel exporters for both tracing and metrics are not gracefully closed. Even though exporters are running the whole Node runtime, and anyway, once the node stops, they are stopped, we still should gracefully close them to be nice and follow best practices. Also, this will be more relevant with [runtime switchability](https://github.com/celestiaorg/celestia-node/issues/937)for telemetry

**Comment by Wondertan** [comment]
This is closed for metrics and not for the traces so reopening

**Comment by dougEfresh** [comment]
@Wondertan see #1524
