### ISSUE TITLE
Implement remaining transaction type proxies in `coreAccessor`

### ISSUE THREAD

**Issue by renaynay** [celestiaorg/celestia-node#946]
- [ ] Implement each transaction type proxy inside of `core_access.go`
- [ ] expose these methods via higher level `Accessor` interface and have `Service` proxy to the accessor's impl of them
- [ ] expose via RPC

**Comment by distractedm1nd** [comment]
https://docs.cosmos.network/v0.44/modules/staking/09_client.html#transactions

**Comment by distractedm1nd** [comment]
So, from my understanding, the transaction types we need to proxy are `sdk.Msg`'s which are defined in the cosmos-sdk [modules](https://github.com/cosmos/cosmos-sdk/tree/main/x). For example, [bankypes.NewMsgSend](https://github.com/cosmos/cosmos-sdk/blob/71035879e4af4551b9bcf16f79bc52785793602e/x/bank/types/msgs.go#L22-L26) for our `ca.Transfer`.

Is this correct @renaynay ? I cannot find any comprehensive list of all `Msg` types supported by the standard modules, and it looks like we don't need all of them (unsure though)

**Comment by renaynay** [comment]
We need: 

```
TypeMsgUndelegate                = "begin_unbonding"
TypeMsgCancelUnbondingDelegation = "cancel_unbond"
TypeMsgDelegate                  = "delegate"
TypeMsgBeginRedelegate           = "begin_redelegate"
```
