### ISSUE TITLE
ci: Lint Markdown files

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#947]
### Implementation ideas

celestia-node contains ADRs in [docs/adr](https://github.com/celestiaorg/celestia-node/tree/main/docs/adr) that could benefit from consistent styling in Markdown files. One idea is to use [Markdownlint](https://github.com/markdownlint/markdownlint).

Originally motivated by: https://github.com/celestiaorg/celestia-node/pull/922#discussion_r930044696

**Comment by adlerjohn** [comment]
https://github.com/FuelLabs/fuel-indexer/blob/a96f8ec9e9b3edd35d564f4d079a2739a3bb0a7c/.github/workflows/ci.yml#L217-L227
