### ISSUE TITLE
Provide VSCode extension recommendations

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#949]
### Implementation ideas

It is possible for a repo to provide extension recommendations when the repo is opened in VSCode ([article](https://tattoocoder.com/recommending-vscode-extensions-within-your-open-source-projects/)). 

Given some contributors to celestia-node use VSCode, we may improve their development experience by providing a set of extension recommendations that the team finds helpful while working on this codebase.

A minimal `extensions.json` could be:

```json
{
    "recommendations": [
        "DavidAnson.vscode-markdownlint"
    ]
}
```

**Comment by Wondertan** [comment]
I don't think we should pollute our repo with IDEs configurations. Not everyone uses VSCode, and some use IntellijIdea or Vim/Emacs. If we allow configuration for one IDE, then others should also be allowed to be neutral, which is not a good practice. We can have our recommendations/configs in a separate or the docs repo if we want to.
