### ISSUE TITLE
ci: lint Prometheus metric names

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-node#950]
### Implementation ideas

[golangci-lint](https://golangci-lint.run/) has a linter for Prometheus metric names called: [promlinter](https://golangci-lint.run/usage/linters/#promlinter). Since https://github.com/celestiaorg/celestia-node/pull/907 introduces Prometheus metrics, I think we should consider enabling it.

Any objections @Wondertan ?

**Comment by Wondertan** [comment]
We should follow best practices from OpenTelemetry, not from Prometheus, if they are equal, then I am totally ok with doing this

**Comment by rootulp** [comment]
OpenTelemetry naming conventions: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md

Promlint makes no mention of OpenTelemetry so this issue needs investigation on whether promlint would encourage any naming patterns that don't conform to OpenTelemetry.

**Comment by rootulp** [comment]
promlint [README](https://github.com/yeya24/promlinter#usage) doesn't describe good / bad conventions that the linter flags so it's not easy to compare what promlint recommends versus https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md

For the moment will close this issue as not planned.
