### ISSUE TITLE
cmd: Drop `Env` in favour of vanilla context.WithValue wrappers

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/celestia-node#965]
Env, in fact, only keeps some additional and often optional fields taken from flags which we can keep in the context using `WithValue`

**Comment by renaynay** [comment]
Could probably tackle this along with #958 , would help avoid some cyclical dependency issues I'm running into.

**Comment by Wondertan** [comment]
Ok. Anyway would like to know what issues your are facing in detail
