### ISSUE TITLE
rpc: Move sanity check logic from rpc handlers to implementations

### ISSUE THREAD

**Issue by distractedm1nd** [celestiaorg/celestia-node#998]
There is some sanity check logic in our rpc handlers as discussed here: https://github.com/celestiaorg/celestia-node/pull/984#discussion_r938706320. This should be moved down and handled by the implementation beneath it, so that the checks don't only occur for RPC users, but also for those using the public API directly.

**Comment by HoytRen** [comment]
I'm working on this, but because I can't get the unmodified code pass the unit test, I can't create the PR now.

**Comment by distractedm1nd** [comment]
Hey there @HoytRen, you should be able to create the PR from your fork without needing to first pass unit tests - and then we can check out what is wrong with the CI :) Thank you for taking this up!
